/*
----
This file is part of SECONDO.

Copyright (C) 2004-2008, University in Hagen, Faculty of Mathematics and 
Computer Science, Database Systems for New Applications.

SECONDO is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation; either version 2 of the License, or
(at your option) any later version.

SECONDO is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with SECONDO; if not, write to the Free Software
Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
----

DO NOT EDIT THIS FILE - it is machine generated 

Header file for the SecondoKernel.cpp.

Remarks

This file gets generated by javah when javah 
processes the file SecondoKernel.java.
This header file defines several native methods which are
implemented in the SecondoKernel.cpp file.

Includes and Constants

*/
#include <jni.h>

/* 
Header for class util\_secondo\_SecondoKernel 

*/
#ifndef _Included_util_secondo_SecondoKernel
#define _Included_util_secondo_SecondoKernel
#ifdef __cplusplus
extern "C" {
#endif

JNIEXPORT jboolean JNICALL Java_util_secondo_SecondoKernel_initialize
  (JNIEnv *, jclass, jstring);


JNIEXPORT jobject JNICALL Java_util_secondo_SecondoKernel_query
  (JNIEnv *, jclass, jstring, jboolean);


JNIEXPORT void JNICALL Java_util_secondo_SecondoKernel_setDebugLevel
  (JNIEnv *, jclass, jint);


JNIEXPORT jstring JNICALL Java_util_secondo_SecondoKernel_errorMessage
  (JNIEnv *, jclass);


JNIEXPORT void JNICALL Java_util_secondo_SecondoKernel_shutdown
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
