#!/bin/bash

if [ -z "$SECONDO_WORK_DIR" ]; then
	echo '$SECONDO_WORK_DIR is not defined, check your SECONDO installation'
	exit -1
fi

if [ ! -d $SECONDO_WORK_DIR/optimizer ]; then
	echo "$SECONDO_WORK_DIR/optimizer not found, check your SECONDO installation"
	exit -1
fi

echo "Preparing the SECONDO Optimizer in $SECONDO_WORK_DIR/optimizer"
cd $SECONDO_WORK_DIR/optimizer

rsync -rt $SECONDO_BUILD_DIR/Optimizer/* .

export SECONDO_PARAM_RTFlags="DEBUG:DemangleStackTrace,CMSG:Color,SMI:NoTransactions,CTLG:SkipExamples,SI:PrintCmdTimes"

$SECONDO_BUILD_DIR/bin/SecondoBDB -pltty -L256M -G256M $* pl -g true 

