########################################################################
#
#  SECONDO build configuration file
#
########################################################################

# Uncomment one (and only one) of the following platform lines
# to build for the target platform:

# Uncomment next line for Linux
#platform = linux

# Uncomment next line for Windows 9x/ME/NT/2000
#platform = win32

# Uncomment next line for Sun/Solaris
#platform = solaris

########################################################################

