
all: createText createRandomText createRandomTextRelation

createText: createText.cpp
	g++ -o $@ $< 

createRandomTextRelation: createRandomTextRelation.cpp
	g++ -o $@ $< 

createTextRelationsWithSel: createTextRelationsWithSel.cpp
	g++ -o $@ $< 

