#!/bin/bash

g++ -o /dev/null $SECONDO_BUILD_DIR/CM-Scripts/recodetest.cpp 2>/dev/null

OK=$?

if [ "$OK" == "0" ]; then
  echo "true"
  export SECONDO_HAS_RECODE="true"
else
  echo "false" 
  export SECONDO_HAS_RECODE="false"
fi




