# !/bin/bash
#
# cvs-make.sh: 
# 
# This bash-script checks out the last SECONDO sources
# and runs make to compile them.
#
# 03/02/28 M. Spiekermann: initial version
# 04/01/27 M. Spiekermann: port from csh to bash 
# 05/01/27 M. Spiekermann: major revision, automatic test runs
# July 2005 M. Spiekermann: cvsDir was not set correctly.
#
# July-August 2005, M. Spiekermann: The script will now only
#  compile SECONDO if there are changes in the CVS repository.
#  Moreover, the CVS history will be shown and the users who made
#  changes are extracted and their email addresses are retrieved.
#
# August 2005, M. Spiekermann: A new function makeSecondo was introduced. Now
#  SECONDO will be compiled twice: first with all algebra modules activated
#  and second with the algebras as defined in makefile.alsgebras.sample. 
#  Moreover, if the script is successful, a new tag LAST_STABLE will be set
#  for the file's revision numbers.
#
# January 2006, M. Spiekermann: A backup dir for mails and test outputs
#   was implemented. 
#
# October 2006, M. Spiekermann: Support for multiple SDKs and cvs modules added.

# Configuration Options

# root for created local directories and files
rootDir=$HOME


# cvs configuration
cvsDir=/home/cvsroot
coTag="HEAD"
cvsHistServer="zeppelin"
#cvsHistRootDir="/tmp/spieker/testrun-errors"
cvsHistRootDir="/home/secondo/testrun-errors"

waitMax=900

# options for automatic mails  
LU_SENDMAIL="true"
failedBuild_DefaultRecipients="spieker@zeppelin behr@zeppelin"

# define mail bodys
mailHeader="
This message was generated by $0!  

"

mailFooter="
Please contact the involved people in order to find out 
who should fix the problem! A history of the old error log
files is stored in $cvsHistRootDir on server $cvsHistServer."

mailBody1="
$mailHeader

You will find the output of make in the attached file.
$mailFooter
"

mailBody2="
$mailHeader

You will find the log files of the failed tests in the attached file.
$mailFooter"

mailBody3="
$mailHeader

You will find the log file of make realclean in the attached file.

List of unremoved files:

"



#############################################################
#                IMPLEMENTATION PART                        #                               
#############################################################

sdkRootDir=""
sdkDir=""
coModule=""

baseDir=$HOME/${0%/*}

# include function definitions
# libutil.sh must be in the search PATH 
if [ -s $baseDir/libutil.sh ]; 
then
  if ! source $baseDir/libutil.sh; then exit 1; fi
else
  if ! source libutil.sh; then exit 1; fi
fi


# makeModule $1 $2
#
# $1 file name for make's output
# $2 subject for email
function makeModule() {

local msgFile=$1
local subject=$2

cd $cbuildDir
CM-Scripts/catvar.sh > $msgFile 2>&1

if isCmdPresent "nice"; then
  local niceOpt="nice -n 19"
fi

checkCmd "$niceOpt make" >> $msgFile 2>&1

local rc=$?
# proceed if last command was successful
if [ $rc -ne 0 ]; then

  printf "%s\n" "Problems during build, sending a mail."

  mkMailStr "$mailBody1"
  sendMail "$subject" "$mailRecipients $failedBuild_DefaultRecipients" "$MAIL_STR" "$cvsHistMailBackupDir" "$msgFile" 

  return $rc 
fi

}


tmpDir=/tmp/cvs-make-$USER

if [ ! -d $tmpDir ]; then
  mkdir $tmpDir
fi

declare -i numOfArgs=$#
let numOfArgs++

while [ $# -eq 0 -o $numOfArgs -ne $OPTIND ]; do

  getopts "hnm:r:w:c:s:t:d:" optKey
  if [ "$optKey" == "?" ]; then
    optKey="h"
  fi

  case $optKey in

   h) showGPL
      printf "\n%s\n" "Usage of ${0##*/}:" 
      printf "%s\n"   "  -r<root-dir> => Mandatory argument"
      printf "%s\n"   "Options:"
      printf "%s\n"   "  -h print this message and exit."
      printf "%s\n"   "  -n send no mails. Just print the message to stdout."
      printf "%s\n"   "  -s<sdk-root> => \"${sdkRootDir}\" "
      printf "%s\n"   "  -d<sdk-dir> => \"${sdkDir}\" "
      printf "%s\n"   "  -t<version-tag> => \"${coTag}\" "
      printf "%s\n"   "  -m<cvs-module> => \"${coModule}\" "
      printf "%s\n"   "  -w<seconds> (timeout for tests!) => \"${waitMax}\" "
      printf "%s\n\n" "  -c<checkout-dir> => \"tmp_secondo_<date>\""
      printf "%s\n"   "The script checks out a local copy of <cvs-module> into the directoy"
      printf "%s\n"   "into <root-dir>/<checkout-dir> and runs make, various tests, etc."
      printf "%s\n\n" "In case of a failure an email will be sent to the CVS users."
      exit 0;;
   
   r) rootDir=$OPTARG;;
   
   s) sdkRootDir=$OPTARG;;

   d) sdkDir=$OPTARG;;

   t) coTag=$OPTARG;;
   
   c) coDir=$OPTARG;;

   w) waitMax=$OPTARG;;

   m) coModule=$OPTARG;;
   
   n) LU_SENDMAIL="false";;

  esac

done

printSep "Variable values"

coDir=tmp_${coModule}_${date_ymd}_${date_HMS}

showValue rootDir
showValue cvsDir
showValue coDir
showValue coTag
showValue coModule
showValue LU_SENDMAIL
showValue waitMax

if [ "$coModule" == "" ]; then
  echo -e "Error: a module needs to be specified!"
  exit 1;
fi



# set up environment for secondo
source ~/.bashrc # this is needed when started by cron

# overwrite SECONDO_SDK and set up
# the compiler and other tools needed by secondo
if [ "$sdkRootDir" == "" ]; then
  echo -e "Error: The SDK root needs to be specified!"
  exit 1;
fi

if [ "$sdkDir" == "" ]; then
  echo -e "Error: The SDK dir needs to be specified!"
  exit 1;
fi

export SECONDO_SDK=$sdkRootDir/$sdkDir

showValue SECONDO_SDK 

if ! source ~/.secondorc ""; then exit 1; fi

# derive some other important directories
cbuildDir=${rootDir}/${coDir}
scriptDir=${cbuildDir}/CM-Scripts
startDate=$(date)
scriptFile="${PWD}/$0"

showValue startDate
showValue scriptFile
showValue scriptDir
showValue cbuildDir
 
## check if files in the module secondo were changed
## since the last run
cvsHistRootDir="$cvsHistRootDir/$sdkDir/$coModule"
lastDateFile="$cvsHistRootDir/lastrun"
lastDateFileHeader="#This file was generated by $0! It stores the date of the last run."

createDir $cvsHistRootDir

cvsHistFile="$cvsHistRootDir/cvs-make-history"
cvsHistMailBackupDir=$cvsHistRootDir/${date_ymd}_${date_HMS}

showValue cvsHistRootDir
showValue lastDateFile
showValue cvsHistFile
showValue cvsHistMailBackupDir

# mkMailStr
# $1 body 
function mkMailStr {

  MAIL_STR="Used SECONDO_SDK=<"$SECONDO_SDK">

$cvsChanges

$1"
}


# cvsChanges
#
# $1 file last date
# $2 cvs module

function cvsChanges()
{
# retrieve date of last run and store it in the first
# line. This is more secure since time stamps of the file
# may be modified by backup-script etc.

local file=$1
local module=$2
lastDate="1-day-ago"

if [ -e $file ]; then
  lastDate=$(tail -n1 $file)
fi
showValue lastDate

# Note: The -p"prefix" option of the history commands selects files starting with the
# given prefix. Since we have other repositories starting with "secondo" we need to filter 
# the output using grep.
local cvsHistCmd="cvs history -xMAR -a -D\"$lastDate\" -p\"$module\" | sed -nre \"/$module[/ ]|No records/p\""
showValue cvsHistCmd

cvsHistory=$(eval $cvsHistCmd)
#showValue cvsHistory

# store current date in file
local currentDate=$(date +"%Y-%m-%d %H:%M")

echo $lastDateFileHeader > $file
echo $currentDate >> $file

cvsChanges="
-----------------------------------------------------------
${currentDate}: Changes since last run (${lastDate})
-----------------------------------------------------------
$cvsHistory"
echo -e "$cvsChanges" >> $cvsHistFile

# extract the 1st line of cvs history 
local cvsHist_1st=$(echo $cvsHistory | head -n1)

#showValue cvsHist_1st
if [ "$cvsHist_1st" == "No records selected." ]; then 
  return 1
else  
  return 0 
fi  

}


cvsChanges "$lastDateFile" "$coModule"
cvsChanges_rc=$?
showValue cvsChanges_rc

if [ $cvsChanges_rc -ne 0 ]; then
 
  printf "\nNo changes since ${lastDate}! \n\n"
  exit 0;

else
  echo -e "\n$cvsChanges"

  cvsUsers=$( echo -e "$cvsHistory" | 
	      awk '/./ { print $5 }' | sort | uniq | tr "\n" " " )

  mailRecipients=""
  for userName in $cvsUsers; do

    mapStr "${cvsDir}/CVSROOT/users" "$userName" ":"
    mailRecipients="$LU_MAPSTR $mailRecipients"

  done

  printf "\n%s\n" "CVS user(s)     : $cvsUsers"
  printf "%s\n"   "Mail address(es): $mailRecipients"
  
fi


## report host status 
printSep "host status"
printf "%s\n" "uptime"
uptime
printf "\n%s\n" "disk free"
df -k
printf "\n%s\n" "memory usage"
free -m


## checkout work copy
printSep "Checking out work copy"
setvar $cbuildDir
printSep "Environment settings"
catvar

printSep "Alias definitions"
alias

cd $rootDir
checkCmd "cvs -Q checkout -d $coDir -P $coModule"

## run make
printSep "Compiling $coModule"

declare -i errors=0
cd $cbuildDir
printf "\n%s\n" "Entering directory $PWD"

export SECONDO_ACTIVATE_ALL_ALGEBRAS="true"
export SECONDO_YACC="/usr/bin/bison"

logFile=$tmpDir/make-all-1.log
makeModule "$logFile" "Building $coModule with all algebras failed!"

printSep "Cleaning $coModule"
logFile=$tmpDir/make-realclean.log
checkCmd "make realclean" > $logFile 2>&1

printf "\n%s\n" "files unkown to CVS:"
leftFiles=$(cvs -nQ update | grep "^? ") 
if [ "$leftFiles" != "" ]; then 
  printf "\n make realclean has left some files: \n"
  printf "\n $leftFiles"
  mkMailStr "$mailBody3 $leftFiles"
  sendMail "make realclean has left some files" "$mailRecipients" "$MAIL_STR" "$cvsHistMailBackupDir" "$logFile"
  fi

printSep "Compile Again"
logFile=$tmpDir/make-all-2.log
unset SECONDO_ACTIVATE_ALL_ALGEBRAS
makeModule "$logFile" "Building $coModule failed!"


## run tests

if [ $? == 0 ]; then

  printSep "Running automatic tests"
  cd $scriptDir
  checkCmd "run-tests.sh -tty $cvsHistRootDir $waitMax"

  if [ $? -ne 0 ]; then
    
    printf "%s\n" "Problems during test, sending a mail"
  
    attachment2="$cbuildDir/failedTests.tar.gz"
    subject2="Automatic tests failed!"

    failedHist="

List of failed tests:
---------------------
$(find $cvsHistRootDir -name "_failed_*" -exec cat {} \;)
"

    mkMailStr "$mailBody2 $failedHist"   
    sendMail "$subject2" "$mailRecipients" "$MAIL_STR" "$cvsHistMailBackupDir" "$attachment2"
    let errors++

  fi

fi


if [ $[errors] != 0 ]; then

  printf "\n *** There were $errors errors in the automatic tests! ***\n"

else

  # Move label for stable version
  cd $cbuildDir
  tagSym="LAST_STABLE"
  tagMsg="Moving CVS tag $tagSym"
  printSep $tagMsg
  echo -e "Automatic regression test was successful. ${tagMsg}!" >> $cvsHistFile
  cvs -Q tag -d $tagSym 
  cvs -Q tag $tagSym
  make tag=$tagSym src-archives
  #Backup to /www switched of since the server has problems
  cp /tmp/make-$USER/secondo-$tagSym* $HOME/Backup 

  # clean up
  rm -rf $cbuildDir
  rm -rf $tmpDir
  rm -rf /tmp/make-$USER

fi

exit $errors
