#!/bin/bash


if [ "$1" = "--win" ]; then
   createWin=true;
	shift
fi

if [ -n "$1"  ]; then
   REV=" -r $1 "
   VERSION=$1
else
   REV=" -D now "
   VERSION=current
fi

echo "Create public version from revision number " $VERSION

if [ -d secondo ] ; then
  echo "directory secondo exists"
  exit 1
fi


cvs -q export $REV  secondo >/dev/null

if [ $? != "0" ] ; then
  echo "problems with cvs export"
  exit 1
fi

secondo/CM-Scripts/mkpublic.sh secondo/nonpublic.filelist publicsecondo_filelist


if [ -f "secpub.tar" ] ; then
  echo secpub.tar exists
  exit 1
fi

cat publicsecondo_filelist | sed "s/.*/tar -rf secondo-$VERSION-LAT1.tar \"&\"/g" | sh

if [ "$SECONDO_PLATFORM" = "win32" ]; then
  echo "create windows version"
  rm -r secondo
  tar -xf secondo-$VERSION-LAT1.tar
  rm secondo-$VERSION-LAT1.tar
  zip -r secondo-$VERSION-CP1252.zip secondo  
  rm -rf secondo
elif [ -n  "$createWin" ]; then
  echo "Create windows archive on linux system"
  rm -rf secondo
  tar -xf secondo-$VERSION-LAT1.tar
  rm secondo-$VERSION-LAT1.tar
	find secondo -iname "*.c" -o -iname "*.cpp" -o  -iname "*.h" -o -iname "*.txt" -o -iname "read*" -o -iname "*.pl" -exec recode utf-8..windows-1252 {} \;
  zip -r secondo-$VERSION-CP1252.zip secondo  
  rm -rf secondo
else
  echo "create linux version"
  gzip secondo-$VERSION-LAT1.tar
  rm -r secondo
fi

echo "archive created"





