operator abs alias ABS pattern op ( _ )
operator zero alias ZERO pattern op ()
operator periods2mint alias PERIODS2MINT pattern op ( _ )
operator rough_center alias ROUGH_CENTER pattern op ( _ )
operator area alias AREA pattern op ( _ )
operator perimeter alias PERIMETER pattern op ( _ )