#!/bin/bash

bin=`dirname "$0"`
bin=`cd "$bin"; pwd`
source $bin/ps-functions

ADDPAR=""  # Additional startup parameters for each slave
SLONLY=false
# Process the parameters
declare -i numOfArgs=$#
let numOfArgs++

while [ $numOfArgs -ne $OPTIND ]; do

  getopts "hsop" optKey
  if [ "$optKey" == "?" ]; then
    optKey="h"
  fi

  case $optKey in 
    h)
      echo -en "\nUsage of ${0##*/}:\n\n"
      echo -en "Start up the Secondo Monitors on machines inside the cluster.\n"
      echo -en "Machine's IP addresses are listed in the file\n$PARALLEL_SECONDO_SLAVES \n$PARALLEL_SECONDO_MASTER\n\n"
      echo -en "  -h Print this message and exit. \n\n"
      echo -en "  -s Start up the monitors only on Slave nodes. \n\n"
      echo -en "  -o Start the Secondo Monitors base on Own configuration \n"
      echo -en "     $HOME/.parasecrc \n\n"
      echo -en "  -p Profile the Secondo Monitors\n\n"
      exit 0
      ;;
    s)
      SLONLY=true
      ;;
    o)
      ADDPAR="$ADDPAR -o"
      ;;
    p)
      ADDPAR="$ADDPAR -p"
  esac

done

if $SLONLY ; then
  IPLIST=$(get_slaveIPs)
else
  IPLIST=$(get_slaveIPs -m)
fi

for node in $IPLIST; do
  echo -n "Switch ON Monitor on $node ... ... "
  ssh $node "ps-startMonitors ${ADDPAR}" >/dev/null #2>&1
  if [ $? -ne 0 ]; then 
    echo -e "\nStart up fail."
  else
    echo "Done!"
  fi
done

