#!/bin/bash

bin=`dirname "$0"`
bin=`cd "$bin"; pwd`
source $bin/ps-functions

DISCL=false
DISLC=false

# Process the parameters
declare -i numOfArgs=$#
let numOfArgs++

while [ $# -eq 0 -o $numOfArgs -ne $OPTIND ]; do

  getopts "hlco" optKey
  if [ "$optKey" == "?" ]; then
    optKey="h"
  fi

  case $optKey in
   
    h) echo -en "\nUsage of ${0##*/}:\n\n"
       echo -en "  -h Print this message and exit.\n\n"
       echo -en "  -l Distribute the packed mini Secondo to the Local node.\n\n"
       echo -en "  -c Distribute the packed mini Secondo to the Cluster nodes,\n"
       echo -en "     according to the PARALLEL_SECONDO_SLAVES list.\n\n"
       echo -en "  -o Pack and distribute the mini Secondo based on Own configuration \n"
       echo -en "     $HOME/.parasecrc \n\n"
       exit 0;;
    l) DISLC=true;;
    c) DISCL=true;;
    o) if [ ! -f "$HOME/.parasecrc" ]; then
         echo -e "The local parallel secondo configuration $HOME/.parasecrc doesn't exist."
         exit -1;
       else
         source $HOME/.parasecrc
       fi
  esac
done

# Find the actual secondo path
SECPATH="$PARALLEL_SECONDO_BUILD_DIR"
while [ -h "$SECPATH" ]; do
#-h file True if file exists and is a symbolic link.
  ls=`ls -ld "$SECPATH"`
  link=`expr "$ls" : '.*-> \(.*\)$'`
  if expr "$link" : '.*/.*' > /dev/null; then
    SECPATH="$link"
  else
    SECPATH=`dirname "$SECPATH"`/"$link"
  fi
done

if [ ! -d "$SECPATH" ]; then
  echo "Cannot access \$SECPATH: No such directory"
  echo "The value of \$SECPATH is: ${SECPATH}"
fi

# If multiple mini secondos are defined
ARVNAME="secondo.tar.gz"
MSARV="${PARALLEL_SECONDO_MAINDS}/${ARVNAME}"
echo "=============== Build Mini Secondo ================"

echo "The mini Secondo is built based on: $SECPATH" 

if [ -f "${MSARV}" ]; then
  rm "${MSARV}"
  echo "Delete the exist mini secondo archive: ${MSARV}"
fi

echo -e "\n---- The Mini Secondo contains ----"
cat "${bin}/miniSec_list"
echo -e "---- End Mini Secondo File List ---\n"

cat "${bin}/miniSec_list" | xargs tar czf "${MSARV}" -C "$SECPATH"
echo "The mini secondo archive is built in ${MSARV}"

echo -e "============= End Building Mini Secondo ===========\n"

declare -r CONFNAME="SecondoConfig.ini"
# Deploy the mini Secondo to local node
if [ $DISLC = true ]; then
  echo "===== Start Deploy mini Secondo Local ====="
  IFS=':'
  declare -a MINISECS=(${PARALLEL_SECONDO})
  declare -a MINISECONS=(${PARALLEL_SECONDO_DBCONFIG})

  if [ ${#MINISECS[*]} -ne ${#MINISECONS[*]} ]; then
    echo "Error! The configuration of mini Secondo and the configuration doesn't match"
    echo "PARALLEL_SECONDO is : ${#MINISECS[*]}"
    echo "PARALLEL_SECONDO_DBCONFIG is : ${#MINISECONS[*]}"
    exit -1
  fi

  declare -i CNT=0
  while [ ${CNT} -lt ${#MINISECS[*]} ]; do
    MINISEC="${MINISECS[$CNT]}/${PARALLEL_SECONDO_DATASERVER_NAME}/${PARALLEL_SECONDO_MINI_NAME}"
    SECCONF="${MINISECONS[$CNT]}"
    if [ -d "${MINISEC}" ]; then
      echo "Delete the exist mini secondo: ${MINISEC}"
      if [ -w "${MINISEC}" ]; then 
        rm -rf "${MINISEC}"
      else
        echo "You don't have the authority to delete the path ${MINISEC}"
        exit -1;
      fi
    else
      if [ -f "${MINISEC}" ]; then
        echo "The ${MINISEC} should be a directory, not a file."
        exit -1;
      fi 
    fi

    mkdir "$MINISEC"
    tar -xzf "${MSARV}" -C "${MINISEC}"
    cp -v "${SECCONF}" "${MINISEC}/bin/${CONFNAME}"
    chmod -R 775 ${MINISEC}/bin
    echo -e "The mini secondo is deployed in local: ${MINISEC}\n"

    let CNT++
  done
  echo "===== End Deploy mini Secondo Local ====="

fi

# Deploy the mini Secondo to cluster nodes
# Also the master and slave lists
if [ $DISCL = true ]; then
  echo "===== Deploy mini Secondo Cluster ====="
  echo "Distribute the mini secondo to every node inside the cluster, including the master node."
  RARVNAME="DTR_secondo.tar.gz"
  IPLIST="$(get_slaveIPs -m)"

  for NODE in $IPLIST; do
    CNT=0
  
    #Distribute the master and slave lists
#    RCONF=`ssh $NODE "echo \\\$PARALLEL_SECONDO_CONF"`
#    scp ${PARALLEL_SECONDO_MASTER} ${PARALLEL_SECONDO_SLAVES} $NODE:$RCONF

    RSEC=$(ssh $NODE "echo \$PARALLEL_SECONDO")  # Remote mini Secondo
#    RSECON=$PARALLEL_SECONDO_DBCONFIG
    RSECON=$(ssh $NODE "echo \\$PARALLEL_SECONDO_DBCONFIG")  # Use nodes' local description
    declare -a RSA=($(echo $RSEC | tr ':' ' '))
    declare -a RSCA=($(echo $RSECON | tr ':' ' '))

    if [ ${#RSA[@]} -ne ${#RSCA[@]} ]; then
      echo "In node $NODE, the PARALLEL_SECONDO doesn't match with its PARALLEL_SECONDO_DBCONFIG"
      echo "PARALLEL_SECONDO is: $RSEC"
      echo "PARALLEL_SECONDO_DBCONFIG is: $RSECON"
      continue
    fi  
    
    while [ $CNT -lt ${#RSA[@]} ]; do
       fLoc="${RSA[$CNT]}/${PARALLEL_SECONDO_DATASERVER_NAME}"
       echo "Distribute mini Secondo -> $NODE:$fLoc ... "
       scp "$MSARV" "$NODE:${fLoc}/${RARVNAME}"
       rsLoc="${fLoc}/${PARALLEL_SECONDO_MINI_NAME}"
       ssh "$NODE"  "rm -rf ${rsLoc}"
       ssh "$NODE"  "mkdir ${rsLoc}"
       ssh "$NODE"  "tar -xzf ${fLoc}/${RARVNAME} -C ${rsLoc}"
       # Changed the access mode after distribute the data
       ssh "$NODE"  "chmod -R 775 ${rsLoc}/bin"
#       echo "Changed the access mod of mini Secondo"
#       ssh "$NODE"  "ls -ld ${rsLoc}/bin"       
       ssh "$NODE"  "cp ${RSCA[$CNT]} ${rsLoc}/bin/${CONFNAME}"
       echo -e "Use ${RSCA[$CNT]} to set data server ${NODE}:$(($CNT + 1)) \n"

       let CNT++
    done

  done

  echo "===== Deploy mini Secondo Cluster ====="

fi

exit 0

