include ../../makefile.inc

.PHONY: all
all:
	make -C decoder all
	make -C player all
	make -C converter all

.PHONY: clean
clean:
	make -C decoder clean
	make -C player clean
	make -C converter clean
