/*
----
This file is part of SECONDO.

Copyright (C) 2004, University in Hagen, Department of Computer Science,
Database Systems for New Applications.

SECONDO is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation; either version 2 of the License, or
(at your option) any later version.

SECONDO is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with SECONDO; if not, write to the Free Software
Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
----

//paragraph [1] Title: [{\Large \bf \begin{center}] [\end{center}}]
//characters [1] Type: [] []
//characters [2] Type: [] []
//[ae] [\"{a}]
//[oe] [\"{o}]
//[ue] [\"{u}]
//[ss] [{\ss}]
//[Ae] [\"{A}]
//[Oe] [\"{O}]
//[Ue] [\"{U}]
//[x] [$\times $]
//[->] [$\rightarrow $]
//[toc] [\tableofcontents]

[1] Implementation of operation foreverStream.

[toc]

1 Operation foreverStream implementation

Produces an optionally never ending stream of tuples of the 
format...

*/

#include <stdlib.h>
#include <string>

namespace continuousqueries {

struct ForeverHelper {
    static std::string smallStringList[12];
    static std::string bigStringList[500];

    static std::string getUniqueId(const int len=40)
    {
        static const char alphanum[] = "0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ"
                                       "abcdefghijklmnopqrstuvwxyz";

        std::string s;

        for (int i = 0; i < len; ++i) {
            s = s + alphanum[rand() % (sizeof(alphanum) - 1)];
        }

        return s;
    }

    static int getInt(int upto=100)
    {
        if (upto <= 0) upto = 100; 
        return rand() % upto + 1;
    }
    
    static std::string getSmallString(int upto=12)
    {
        if (upto > 12) upto = 12;
        if (upto <= 0) upto = 12; 
        return smallStringList[rand() % upto];
    }

    static std::string getBigString(int upto=500)
    {
        if (upto > 500) upto = 500;
        if (upto <=  0) upto = 500; 

        return smallStringList[rand() % upto];
    }

    static double getDouble(int upto=10)
    {
        if (upto <= 0) upto = 10; 
        
        double f = (double) rand() / RAND_MAX;
        return 0 + f * (upto);
    }

    static bool getBool(int chanceOfFalse=50)
    {
        if (chanceOfFalse <= 0) return true;
        return (rand() % 100 + 1) > chanceOfFalse;
    }
};

std::string ForeverHelper::smallStringList[12] = {
    "Januar", "Februar", "März", "April", "Mai", "Juni", "Juli",
    "August", "September", "Oktober", "November", "Dezember"
};

std::string ForeverHelper::bigStringList[500] = { 
    "Berlin", 
    "Hamburg", 
    "München", 
    "Köln", 
    "Frankfurt am Main", 
    "Stuttgart", 
    "Düsseldorf", 
    "Dortmund", 
    "Essen", 
    "Leipzig", 
    "Bremen",
    "Dresden",
    "Hannover",
    "Nürnberg",
    "Duisburg",
    "Bochum",
    "Wuppertal",
    "Bielefeld",
    "Bonn",
    "Münster",
    "Karlsruhe",
    "Mannheim",
    "Augsburg",
    "Wiesbaden",
    "Mönchengladbach",
    "Gelsenkirchen",
    "Braunschweig",
    "Kiel",
    "Chemnitz",
    "Aachen",
    "Halle (Saale)",
    "Magdeburg",
    "Freiburg im Breisgau",
    "Krefeld",
    "Lübeck",
    "Mainz",
    "Erfurt",
    "Oberhausen",
    "Rostock",
    "Kassel",
    "Hagen",
    "Saarbrücken",
    "Hamm",
    "Potsdam",
    "Mülheim an der Ruhr",
    "Ludwigshafen am Rhein",
    "Oldenburg",
    "Osnabrück",
    "Leverkusen",
    "Heidelberg",
    "Solingen",
    "Darmstadt",
    "Herne",
    "Neuss",
    "Regensburg",
    "Paderborn",
    "Ingolstadt",
    "Offenbach am Main",
    "Würzburg",
    "Fürth",
    "Ulm",
    "Heilbronn",
    "Pforzheim",
    "Wolfsburg",
    "Göttingen",
    "Bottrop",
    "Reutlingen",
    "Koblenz",
    "Recklinghausen",
    "Bremerhaven",
    "Bergisch Gladbach",
    "Jena",
    "Erlangen",
    "Remscheid",
    "Trier",
    "Salzgitter",
    "Moers",
    "Siegen",
    "Hildesheim",
    "Cottbus",
    "Kaiserslautern",
    "Gütersloh",
    "Witten",
    "Hanau",
    "Schwerin",
    "Gera",
    "Ludwigsburg",
    "Esslingen am Neckar",
    "Iserlohn",
    "Düren",
    "Zwickau",
    "Tübingen",
    "Flensburg",
    "Gießen",
    "Ratingen",
    "Lünen",
    "Villingen-Schwenningen",
    "Konstanz",
    "Marl",
    "Worms",
    "Dessau-Roßlau",
    "Velbert",
    "Minden",
    "Neumünster",
    "Norderstedt",
    "Delmenhorst",
    "Bamberg",
    "Viersen",
    "Wilhelmshaven",
    "Marburg",
    "Rheine",
    "Gladbeck",
    "Dorsten",
    "Lüneburg",
    "Troisdorf",
    "Detmold",
    "Bayreuth",
    "Castrop-Rauxel",
    "Arnsberg",
    "Lüdenscheid",
    "Brandenburg an der Havel",
    "Landshut",
    "Bocholt",
    "Aschaffenburg",
    "Celle",
    "Kempten (Allgäu)",
    "Fulda",
    "Lippstadt",
    "Aalen",
    "Dinslaken",
    "Herford",
    "Kerpen",
    "Plauen",
    "Rüsselsheim am Main",
    "Neuwied",
    "Sindelfingen",
    "Weimar",
    "Neubrandenburg",
    "Dormagen",
    "Grevenbroich",
    "Rosenheim",
    "Herten",
    "Bergheim",
    "Schwäbisch Gmünd",
    "Garbsen",
    "Wesel",
    "Friedrichshafen",
    "Hürth",
    "Stralsund",
    "Offenburg",
    "Greifswald",
    "Langenfeld (Rheinland)",
    "Frankfurt (Oder)",
    "Neu-Ulm",
    "Euskirchen",
    "Hameln",
    "Unna",
    "Göppingen",
    "Stolberg (Rheinland)",
    "Görlitz",
    "Eschweiler",
    "Sankt Augustin",
    "Hilden",
    "Meerbusch",
    "Waiblingen",
    "Baden-Baden",
    "Hattingen",
    "Lingen (Ems)",
    "Pulheim",
    "Bad Homburg vor der Höhe",
    "Bad Salzuflen",
    "Langenhagen",
    "Schweinfurt",
    "Neustadt an der Weinstraße",
    "Nordhorn",
    "Menden (Sauerland)",
    "Wetzlar",
    "Ahlen",
    "Wolfenbüttel",
    "Frechen",
    "Ibbenbüren",
    "Passau",
    "Kleve",
    "Willich",
    "Goslar",
    "Speyer",
    "Emden",
    "Gummersbach",
    "Bad Kreuznach",
    "Ravensburg",
    "Böblingen",
    "Peine",
    "Erftstadt",
    "Elmshorn",
    "Heidenheim an der Brenz",
    "Lörrach",
    "Rastatt",
    "Bergkamen",
    "Bad Oeynhausen",
    "Rheda-Wiedenbrück",
    "Cuxhaven",
    "Frankenthal (Pfalz)",
    "Freising",
    "Leonberg",
    "Bornheim",
    "Singen (Hohentwiel)",
    "Gronau (Westf.)",
    "Straubing",
    "Soest",
    "Stade",
    "Hennef (Sieg)",
    "Dachau",
    "Alsdorf",
    "Neunkirchen",
    "Schwerte",
    "Dülmen",
    "Herzogenrath",
    "Melle",
    "Landau in der Pfalz",
    "Lutherstadt Wittenberg",
    "Lahr/Schwarzwald",
    "Oberursel (Taunus)",
    "Hof",
    "Filderstadt",
    "Fellbach",
    "Bünde",
    "Gotha",
    "Weinheim",
    "Albstadt",
    "Rodgau",
    "Bruchsal",
    "Erkrath",
    "Brühl",
    "Oranienburg",
    "Neustadt am Rübenberge",
    "Lehrte",
    "Rottenburg am Neckar",
    "Falkensee",
    "Kaufbeuren",
    "Memmingen",
    "Erkelenz",
    "Kamen",
    "Bietigheim-Bissingen",
    "Kaarst",
    "Pinneberg",
    "Wismar",
    "Eisenach",
    "Weiden in der Oberpfalz",
    "Borken",
    "Nettetal",
    "Amberg",
    "Gifhorn",
    "Nordhausen",
    "Homburg",
    "Aurich",
    "Heinsberg",
    "Ansbach",
    "Dreieich",
    "Wunstorf",
    "Freiberg",
    "Laatzen",
    "Siegburg",
    "Seevetal ",
    "Coburg",
    "Königswinter",
    "Nürtingen",
    "Weißenfels",
    "Halberstadt",
    "Lemgo",
    "Schwabach",
    "Pirmasens",
    "Monheim am Rhein",
    "Kirchheim unter Teck",
    "Bensheim",
    "Germering",
    "Eberswalde",
    "Löhne",
    "Leinfelden-Echterdingen",
    "Stendal",
    "Neumarkt in der Oberpfalz",
    "Schwäbisch Hall",
    "Buxtehude",
    "Hofheim am Taunus",
    "Schorndorf",
    "Hückelhoven",
    "Bautzen",
    "Völklingen",
    "Ettlingen",
    "Freital",
    "Ostfildern",
    "Ahaus",
    "Bitterfeld-Wolfen",
    "Buchholz in der Nordheide",
    "Würselen",
    "Maintal",
    "Mettmann",
    "Pirna",
    "Bernau bei Berlin",
    "Niederkassel",
    "Haltern am See",
    "Langen",
    "Neu-Isenburg",
    "Greven",
    "Kamp-Lintfort",
    "Warendorf",
    "Fürstenfeldbruck",
    "Papenburg",
    "Backnang",
    "Königs Wusterhausen",
    "Beckum",
    "Erding",
    "Coesfeld",
    "Voerde (Niederrhein)",
    "Emsdetten",
    "Wesseling",
    "Sankt Ingbert",
    "Kehl",
    "Porta Westfalica",
    "Tuttlingen",
    "Sinsheim",
    "Meppen",
    "Suhl",
    "Lage",
    "Limburg an der Lahn",
    "Kempen",
    "Wermelskirchen",
    "Winsen (Luhe)",
    "Cloppenburg",
    "Datteln",
    "Saarlouis",
    "Mörfelden-Walldorf",
    "Zweibrücken",
    "Leer",
    "Merseburg",
    "Crailsheim",
    "Balingen",
    "Dietzenbach",
    "Seelze",
    "Hemer",
    "Viernheim",
    "Barsinghausen",
    "Radebeul",
    "Steinfurt",
    "Geldern",
    "Kornwestheim",
    "Bad Vilbel",
    "Uelzen",
    "Goch",
    "Stuhr",
    "Deggendorf",
    "Wedel",
    "Ahrensburg",
    "Mühlhausen/Thüringen",
    "Hoyerswerda",
    "Korschenbroich",
    "Bernburg (Saale)",
    "Rheinfelden (Baden)",
    "Wernigerode",
    "Biberach an der Riß",
    "Naumburg (Saale)",
    "Lampertheim",
    "Jülich",
    "Altenburg",
    "Vechta",
    "Forchheim",
    "Bad Nauheim",
    "Fürstenwalde/Spree",
    "Delbrück",
    "Itzehoe",
    "Achim",
    "Georgsmarienhütte",
    "Nienburg/Weser",
    "Herrenberg",
    "Oer-Erkenschwick",
    "Rheinberg",
    "Ganderkesee",
    "Radolfzell am Bodensee",
    "Schönebeck",
    "Kreuztal",
    "Bramsche",
    "Einbeck",
    "Gevelsberg",
    "Neuruppin",
    "Geestland",
    "Emmerich am Rhein",
    "Werl",
    "Weyhe ",
    "Haan",
    "Burgdorf",
    "Lohmar",
    "Geesthacht",
    "Riesa",
    "Osterholz-Scharmbeck",
    "Weil am Rhein",
    "Meschede",
    "Schwedt/Oder",
    "Ennepetal",
    "Andernach",
    "Merzig",
    "Friedberg",
    "Bad Hersfeld",
    "Taunusstein",
    "Werne",
    "Gaggenau",
    "Neuburg an der Donau",
    "Wedemark ",
    "Rietberg",
    "Güstrow",
    "Bretten",
    "Vaihingen an der Enz",
    "Tönisvorst",
    "Waltrop",
    "Oelde",
    "Höxter",
    "Northeim",
    "Bühl",
    "Friedberg (Hessen)",
    "Springe",
    "Landsberg am Lech",
    "Kelkheim (Taunus)",
    "Unterschleißheim",
    "Rendsburg",
    "Schwandorf",
    "Rösrath",
    "Bad Zwischenahn ",
    "Schwelm",
    "Zeitz",
    "Idar-Oberstein",
    "Winnenden",
    "Mühlheim am Main",
    "Leichlingen (Rheinland)",
    "Kevelaer",
    "Grimma",
    "Meißen",
    "Henstedt-Ulzburg",
    "Bad Neuenahr-Ahrweiler",
    "Geislingen an der Steige",
    "Wegberg",
    "Sundern (Sauerland)",
    "Königsbrunn",
    "Rödermark",
    "Verden (Aller)",
    "Aschersleben",
    "Baunatal",
    "Emmendingen",
    "Wetter (Ruhr)",
    "Olching",
    "Hattersheim am Main",
    "Reinbek",
    "Blankenfelde-Mahlow ",
    "Mechernich",
    "Griesheim",
    "Rheinbach",
    "Wangen im Allgäu",
    "Geilenkirchen",
    "Overath",
    "Leimen",
    "Garmisch-Partenkirchen",
    "Baesweiler",
    "Neukirchen-Vluyn",
    "Weinstadt",
    "Sangerhausen",
    "Wiesloch",
    "Schloß Holte-Stukenbrock",
    "Hamminkeln",
    "Lauf an der Pegnitz",
    "Strausberg",
    "Lohne (Oldenburg)",
    "Neckarsulm",
    "Hennigsdorf",
    "Nordenham",
    "Remseck am Neckar",
    "Köthen (Anhalt)",
    "Heiligenhaus",
    "Butzbach",
    "Mühlacker",
    "Kulmbach",
    "Hohen Neuendorf",
    "Ilmenau",
    "St. Wendel",
    "Ehingen",
    "Weiterstadt",
    "Staßfurt",
    "Selm",
    "Helmstedt",
    "Pfaffenhofen an der Ilm",
    "Teltow",
    "Heppenheim (Bergstraße)",
    "Bad Honnef",
    "Werder (Havel)",
    "Ludwigsfelde",
    "Lennestadt",
    "Rinteln",
    "Zittau",
    "Brilon",
    "Lübbecke",
    "Achern",
    "Bingen am Rhein",
    "Plettenberg",
    "Verl"
};

}