/*
----
This file is part of SECONDO.

Copyright (C) 2004, University in Hagen, Department of Computer Science,
Database Systems for New Applications.

SECONDO is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation; either version 2 of the License, or
(at your option) any later version.

SECONDO is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with SECONDO; if not, write to the Free Software
Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
----

//paragraph [1] Title: [{\Large \bf \begin{center}] [\end{center}}]
//characters [1] Type: [] []
//characters [2] Type: [] []
//[ae] [\"{a}]
//[oe] [\"{o}]
//[ue] [\"{u}]
//[ss] [{\ss}]
//[Ae] [\"{A}]
//[Oe] [\"{O}]
//[Ue] [\"{U}]
//[x] [$\times $]
//[->] [$\rightarrow $]
//[toc] [\tableofcontents]

[1] Implementation of operation foreverStream.

[toc]

1 Operation foreverStream implementation

Produces an optionally never ending stream of tuples of the 
format...

*/

#include <stdlib.h>
#include <string>

namespace continuousqueries {

struct ForeverHelper {
    static std::string smallStringList[12];
    static std::string bigStringList[500];

    static std::string getUniqueId(const int len=40)
    {
        static const char alphanum[] = "0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ"
                                       "abcdefghijklmnopqrstuvwxyz";

        std::string s;

        for (int i = 0; i < len; ++i) {
            s = s + alphanum[rand() % (sizeof(alphanum) - 1)];
        }

        return s;
    }

    static int getInt(int upto=100)
    {
        if (upto <= 0) upto = 100; 
        return rand() % upto + 1;
    }
    
    static std::string getSmallString(int upto=12)
    {
        if (upto > 12) upto = 12;
        if (upto <= 0) upto = 12; 
        return smallStringList[rand() % upto];
    }

    static std::string getBigString(int upto=500)
    {
        if (upto > 500) upto = 500;
        if (upto <=  0) upto = 500; 

        return smallStringList[rand() % upto];
    }

    static double getDouble(int upto=10)
    {
        if (upto <= 0) upto = 10; 
        
        double f = (double) rand() / RAND_MAX;
        return 0 + f * (upto);
    }

    static bool getBool(int chanceOfFalse=50)
    {
        if (chanceOfFalse <= 0) return true;
        return (rand() % 100 + 1) > chanceOfFalse;
    }
};

std::string ForeverHelper::smallStringList[12] = {
    "January", "February", "March", "April", "May", "June", "July",
    "August", "September", "October", "November", "December"
};

std::string ForeverHelper::bigStringList[500] = { 
    "Berlin", 
    "Hamburg", 
    "Muenchen", 
    "Koeln", 
    "Frankfurt am Main", 
    "Stuttgart", 
    "Duesseldorf", 
    "Dortmund", 
    "Essen", 
    "Leipzig", 
    "Bremen",
    "Dresden",
    "Hannover",
    "Nuernberg",
    "Duisburg",
    "Bochum",
    "Wuppertal",
    "Bielefeld",
    "Bonn",
    "Muenster",
    "Karlsruhe",
    "Mannheim",
    "Augsburg",
    "Wiesbaden",
    "Moenchengladbach",
    "Gelsenkirchen",
    "Braunschweig",
    "Kiel",
    "Chemnitz",
    "Aachen",
    "Halle (Saale)",
    "Magdeburg",
    "Freiburg im Breisgau",
    "Krefeld",
    "Luebeck",
    "Mainz",
    "Erfurt",
    "Oberhausen",
    "Rostock",
    "Kassel",
    "Hagen",
    "Saarbruecken",
    "Hamm",
    "Potsdam",
    "Muelheim an der Ruhr",
    "Ludwigshafen am Rhein",
    "Oldenburg",
    "Osnabrueck",
    "Leverkusen",
    "Heidelberg",
    "Solingen",
    "Darmstadt",
    "Herne",
    "Neuss",
    "Regensburg",
    "Paderborn",
    "Ingolstadt",
    "Offenbach am Main",
    "Wuerzburg",
    "Fuerth",
    "Ulm",
    "Heilbronn",
    "Pforzheim",
    "Wolfsburg",
    "Goettingen",
    "Bottrop",
    "Reutlingen",
    "Koblenz",
    "Recklinghausen",
    "Bremerhaven",
    "Bergisch Gladbach",
    "Jena",
    "Erlangen",
    "Remscheid",
    "Trier",
    "Salzgitter",
    "Moers",
    "Siegen",
    "Hildesheim",
    "Cottbus",
    "Kaiserslautern",
    "Guetersloh",
    "Witten",
    "Hanau",
    "Schwerin",
    "Gera",
    "Ludwigsburg",
    "Esslingen am Neckar",
    "Iserlohn",
    "Dueren",
    "Zwickau",
    "Tuebingen",
    "Flensburg",
    "Giessen",
    "Ratingen",
    "Luenen",
    "Villingen-Schwenningen",
    "Konstanz",
    "Marl",
    "Worms",
    "Dessau-Rosslau",
    "Velbert",
    "Minden",
    "Neumuenster",
    "Norderstedt",
    "Delmenhorst",
    "Bamberg",
    "Viersen",
    "Wilhelmshaven",
    "Marburg",
    "Rheine",
    "Gladbeck",
    "Dorsten",
    "Lueneburg",
    "Troisdorf",
    "Detmold",
    "Bayreuth",
    "Castrop-Rauxel",
    "Arnsberg",
    "Luedenscheid",
    "Brandenburg an der Havel",
    "Landshut",
    "Bocholt",
    "Aschaffenburg",
    "Celle",
    "Kempten (Allgaeu)",
    "Fulda",
    "Lippstadt",
    "Aalen",
    "Dinslaken",
    "Herford",
    "Kerpen",
    "Plauen",
    "Ruesselsheim am Main",
    "Neuwied",
    "Sindelfingen",
    "Weimar",
    "Neubrandenburg",
    "Dormagen",
    "Grevenbroich",
    "Rosenheim",
    "Herten",
    "Bergheim",
    "Schwaebisch Gmuend",
    "Garbsen",
    "Wesel",
    "Friedrichshafen",
    "Huerth",
    "Stralsund",
    "Offenburg",
    "Greifswald",
    "Langenfeld (Rheinland)",
    "Frankfurt (Oder)",
    "Neu-Ulm",
    "Euskirchen",
    "Hameln",
    "Unna",
    "Goeppingen",
    "Stolberg (Rheinland)",
    "Goerlitz",
    "Eschweiler",
    "Sankt Augustin",
    "Hilden",
    "Meerbusch",
    "Waiblingen",
    "Baden-Baden",
    "Hattingen",
    "Lingen (Ems)",
    "Pulheim",
    "Bad Homburg vor der Hoehe",
    "Bad Salzuflen",
    "Langenhagen",
    "Schweinfurt",
    "Neustadt an der Weinstrasse",
    "Nordhorn",
    "Menden (Sauerland)",
    "Wetzlar",
    "Ahlen",
    "Wolfenbuettel",
    "Frechen",
    "Ibbenbueren",
    "Passau",
    "Kleve",
    "Willich",
    "Goslar",
    "Speyer",
    "Emden",
    "Gummersbach",
    "Bad Kreuznach",
    "Ravensburg",
    "Boeblingen",
    "Peine",
    "Erftstadt",
    "Elmshorn",
    "Heidenheim an der Brenz",
    "Loerrach",
    "Rastatt",
    "Bergkamen",
    "Bad Oeynhausen",
    "Rheda-Wiedenbrueck",
    "Cuxhaven",
    "Frankenthal (Pfalz)",
    "Freising",
    "Leonberg",
    "Bornheim",
    "Singen (Hohentwiel)",
    "Gronau (Westf.)",
    "Straubing",
    "Soest",
    "Stade",
    "Hennef (Sieg)",
    "Dachau",
    "Alsdorf",
    "Neunkirchen",
    "Schwerte",
    "Duelmen",
    "Herzogenrath",
    "Melle",
    "Landau in der Pfalz",
    "Lutherstadt Wittenberg",
    "Lahr/Schwarzwald",
    "Oberursel (Taunus)",
    "Hof",
    "Filderstadt",
    "Fellbach",
    "Buende",
    "Gotha",
    "Weinheim",
    "Albstadt",
    "Rodgau",
    "Bruchsal",
    "Erkrath",
    "Bruehl",
    "Oranienburg",
    "Neustadt am Ruebenberge",
    "Lehrte",
    "Rottenburg am Neckar",
    "Falkensee",
    "Kaufbeuren",
    "Memmingen",
    "Erkelenz",
    "Kamen",
    "Bietigheim-Bissingen",
    "Kaarst",
    "Pinneberg",
    "Wismar",
    "Eisenach",
    "Weiden in der Oberpfalz",
    "Borken",
    "Nettetal",
    "Amberg",
    "Gifhorn",
    "Nordhausen",
    "Homburg",
    "Aurich",
    "Heinsberg",
    "Ansbach",
    "Dreieich",
    "Wunstorf",
    "Freiberg",
    "Laatzen",
    "Siegburg",
    "Seevetal ",
    "Coburg",
    "Koenigswinter",
    "Nuertingen",
    "Weissenfels",
    "Halberstadt",
    "Lemgo",
    "Schwabach",
    "Pirmasens",
    "Monheim am Rhein",
    "Kirchheim unter Teck",
    "Bensheim",
    "Germering",
    "Eberswalde",
    "Loehne",
    "Leinfelden-Echterdingen",
    "Stendal",
    "Neumarkt in der Oberpfalz",
    "Schwaebisch Hall",
    "Buxtehude",
    "Hofheim am Taunus",
    "Schorndorf",
    "Hueckelhoven",
    "Bautzen",
    "Voelklingen",
    "Ettlingen",
    "Freital",
    "Ostfildern",
    "Ahaus",
    "Bitterfeld-Wolfen",
    "Buchholz in der Nordheide",
    "Wuerselen",
    "Maintal",
    "Mettmann",
    "Pirna",
    "Bernau bei Berlin",
    "Niederkassel",
    "Haltern am See",
    "Langen",
    "Neu-Isenburg",
    "Greven",
    "Kamp-Lintfort",
    "Warendorf",
    "Fuerstenfeldbruck",
    "Papenburg",
    "Backnang",
    "Koenigs Wusterhausen",
    "Beckum",
    "Erding",
    "Coesfeld",
    "Voerde (Niederrhein)",
    "Emsdetten",
    "Wesseling",
    "Sankt Ingbert",
    "Kehl",
    "Porta Westfalica",
    "Tuttlingen",
    "Sinsheim",
    "Meppen",
    "Suhl",
    "Lage",
    "Limburg an der Lahn",
    "Kempen",
    "Wermelskirchen",
    "Winsen (Luhe)",
    "Cloppenburg",
    "Datteln",
    "Saarlouis",
    "Moerfelden-Walldorf",
    "Zweibruecken",
    "Leer",
    "Merseburg",
    "Crailsheim",
    "Balingen",
    "Dietzenbach",
    "Seelze",
    "Hemer",
    "Viernheim",
    "Barsinghausen",
    "Radebeul",
    "Steinfurt",
    "Geldern",
    "Kornwestheim",
    "Bad Vilbel",
    "Uelzen",
    "Goch",
    "Stuhr",
    "Deggendorf",
    "Wedel",
    "Ahrensburg",
    "Muehlhausen/Thueringen",
    "Hoyerswerda",
    "Korschenbroich",
    "Bernburg (Saale)",
    "Rheinfelden (Baden)",
    "Wernigerode",
    "Biberach an der Riss",
    "Naumburg (Saale)",
    "Lampertheim",
    "Juelich",
    "Altenburg",
    "Vechta",
    "Forchheim",
    "Bad Nauheim",
    "Fuerstenwalde/Spree",
    "Delbrueck",
    "Itzehoe",
    "Achim",
    "Georgsmarienhuette",
    "Nienburg/Weser",
    "Herrenberg",
    "Oer-Erkenschwick",
    "Rheinberg",
    "Ganderkesee",
    "Radolfzell am Bodensee",
    "Schoenebeck",
    "Kreuztal",
    "Bramsche",
    "Einbeck",
    "Gevelsberg",
    "Neuruppin",
    "Geestland",
    "Emmerich am Rhein",
    "Werl",
    "Weyhe ",
    "Haan",
    "Burgdorf",
    "Lohmar",
    "Geesthacht",
    "Riesa",
    "Osterholz-Scharmbeck",
    "Weil am Rhein",
    "Meschede",
    "Schwedt/Oder",
    "Ennepetal",
    "Andernach",
    "Merzig",
    "Friedberg",
    "Bad Hersfeld",
    "Taunusstein",
    "Werne",
    "Gaggenau",
    "Neuburg an der Donau",
    "Wedemark ",
    "Rietberg",
    "Guestrow",
    "Bretten",
    "Vaihingen an der Enz",
    "Toenisvorst",
    "Waltrop",
    "Oelde",
    "Hoexter",
    "Northeim",
    "Buehl",
    "Friedberg (Hessen)",
    "Springe",
    "Landsberg am Lech",
    "Kelkheim (Taunus)",
    "Unterschleissheim",
    "Rendsburg",
    "Schwandorf",
    "Roesrath",
    "Bad Zwischenahn ",
    "Schwelm",
    "Zeitz",
    "Idar-Oberstein",
    "Winnenden",
    "Muehlheim am Main",
    "Leichlingen (Rheinland)",
    "Kevelaer",
    "Grimma",
    "Meissen",
    "Henstedt-Ulzburg",
    "Bad Neuenahr-Ahrweiler",
    "Geislingen an der Steige",
    "Wegberg",
    "Sundern (Sauerland)",
    "Koenigsbrunn",
    "Roedermark",
    "Verden (Aller)",
    "Aschersleben",
    "Baunatal",
    "Emmendingen",
    "Wetter (Ruhr)",
    "Olching",
    "Hattersheim am Main",
    "Reinbek",
    "Blankenfelde-Mahlow ",
    "Mechernich",
    "Griesheim",
    "Rheinbach",
    "Wangen im Allgaeu",
    "Geilenkirchen",
    "Overath",
    "Leimen",
    "Garmisch-Partenkirchen",
    "Baesweiler",
    "Neukirchen-Vluyn",
    "Weinstadt",
    "Sangerhausen",
    "Wiesloch",
    "Schloss Holte-Stukenbrock",
    "Hamminkeln",
    "Lauf an der Pegnitz",
    "Strausberg",
    "Lohne (Oldenburg)",
    "Neckarsulm",
    "Hennigsdorf",
    "Nordenham",
    "Remseck am Neckar",
    "Koethen (Anhalt)",
    "Heiligenhaus",
    "Butzbach",
    "Muehlacker",
    "Kulmbach",
    "Hohen Neuendorf",
    "Ilmenau",
    "St. Wendel",
    "Ehingen",
    "Weiterstadt",
    "Stassfurt",
    "Selm",
    "Helmstedt",
    "Pfaffenhofen an der Ilm",
    "Teltow",
    "Heppenheim (Bergstrasse)",
    "Bad Honnef",
    "Werder (Havel)",
    "Ludwigsfelde",
    "Lennestadt",
    "Rinteln",
    "Zittau",
    "Brilon",
    "Luebbecke",
    "Achern",
    "Bingen am Rhein",
    "Plettenberg",
    "Verl"
};

}