#!/bin/bash
#
# To activate this extensions, some things needs to be done:
#
# 1)
cp auxiliary.pl $SECONDO_BUILD_DIR/Optimizer/
cp calloptimizer.pl $SECONDO_BUILD_DIR/Optimizer/
cp database.pl $SECONDO_BUILD_DIR/Optimizer/
cp operators.pl $SECONDO_BUILD_DIR/Optimizer/
cp opsyntax.pl $SECONDO_BUILD_DIR/Optimizer/
cp optimizer.pl $SECONDO_BUILD_DIR/Optimizer/
cp statistics.pl $SECONDO_BUILD_DIR/Optimizer/

cp subqueries.pl $SECONDO_BUILD_DIR/Optimizer/Subqueries/

# eof
