# filename communication/makefile
#
# last change 10-2003; Thomas Behr

include ../makefile.inc

.PHONY: all #creates the gui and all know viewers
all:
	(cd optimizer;make all)


.PHONY: clean # removes the documentation and all .class files
clean:
	(cd optimizer; make clean)


