#This file is part of SECONDO.
#
#Copyright (C) 2004, University in Hagen, Department of Computer Science, 
#Database Systems for New Applications.
#
#SECONDO is free software; you can redistribute it and/or modify
#it under the terms of the GNU General Public License as published by
#the Free Software Foundation; either version 2 of the License, or
#(at your option) any later version.
#
#SECONDO is distributed in the hope that it will be useful,
#but WITHOUT ANY WARRANTY; without even the implied warranty of
#MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#GNU General Public License for more details.
#
#You should have received a copy of the GNU General Public License
#along with SECONDO; if not, write to the Free Software
#Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
#
########################################################################
#
# SECONDO makefile for the Java Virtual Machine Interface.
#
########################################################################

include ../../makefile.env

APPLOBJECTS=\
	SecondoTTY.o \
	DisplayTTY.o \
	libjvm.a

.PHONY: all
all: libjvm.a


CCFLAGS=  $(PICFLAG) $(DEFAULTCCFLAGS)
CCXFLAGS= $(DEFAULTCCFLAGS)

libjvm.a: jvm.def
	$(DLLTOOL) -k --def jvm.def --dllname jvm.dll --output-lib $(LIBDIR)/libjvm.a

clean:
	$(RM) $(LIBDIR)/libjvm.a
