
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Mon Aug 17 20:01:11 CEST 2015
//----------------------------------------------------

package mmdb.streamprocessing.parser;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int INT = 4;
  public static final int BOOL = 8;
  public static final int SYMBOL = 7;
  public static final int OPEN = 2;
  public static final int EOF = 0;
  public static final int STRING = 6;
  public static final int CLOSE = 3;
  public static final int REAL = 5;
  public static final int error = 1;
}

