#!/bin/bash


if [ $# -lt 3 ]; then
  echo "Usage arlib <ar-tool> <libfile>  <lib_1> ... <lib_n> "
  exit 1
fi

AR=$1
shift

TARGET=$1
shift


SOURCES=$*

SRCOBJECTS=""



rm -rf temp
mkdir temp
cd temp
i=1
for S in $SOURCES; do
  if [[ "$S" == *.o ]]; then
    SRCOBJECTS+=" $S"
  else
    DIRNAME=lib_$i
    mkdir  $DIRNAME 
    cd $DIRNAME 
    $AR x $S
    cd ..
    i=$(expr $i + 1 )
  fi
done


OBJ=$(find . -iname "*.o" )

$AR -qs $TARGET $OBJ


cd ..

rm -rf temp



