# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'importObjectFromQGISDialogView.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(600, 600)
        Dialog.setMinimumSize(QtCore.QSize(600, 600))
        Dialog.setMaximumSize(QtCore.QSize(600, 600))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/objectmap.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Dialog.setWindowIcon(icon)
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.groupBox_2 = QtWidgets.QGroupBox(Dialog)
        self.groupBox_2.setObjectName("groupBox_2")
        self.formLayout = QtWidgets.QFormLayout(self.groupBox_2)
        self.formLayout.setObjectName("formLayout")
        self.labelLayer = QtWidgets.QLabel(self.groupBox_2)
        self.labelLayer.setEnabled(True)
        self.labelLayer.setObjectName("labelLayer")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.labelLayer)
        self.comboBoxLayers = QtWidgets.QComboBox(self.groupBox_2)
        self.comboBoxLayers.setEnabled(True)
        self.comboBoxLayers.setObjectName("comboBoxLayers")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.comboBoxLayers)
        self.lineEditGeometry = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEditGeometry.setReadOnly(True)
        self.lineEditGeometry.setClearButtonEnabled(False)
        self.lineEditGeometry.setObjectName("lineEditGeometry")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lineEditGeometry)
        self.label = QtWidgets.QLabel(self.groupBox_2)
        self.label.setObjectName("label")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label)
        self.lineEditFeaturesCount = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEditFeaturesCount.setReadOnly(True)
        self.lineEditFeaturesCount.setObjectName("lineEditFeaturesCount")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.lineEditFeaturesCount)
        self.label_2 = QtWidgets.QLabel(self.groupBox_2)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.gridLayout.addWidget(self.groupBox_2, 0, 0, 1, 1)
        self.groupBoxFeaturesViewer = QtWidgets.QGroupBox(Dialog)
        self.groupBoxFeaturesViewer.setObjectName("groupBoxFeaturesViewer")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBoxFeaturesViewer)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tableViewFeatures = QtWidgets.QTableView(self.groupBoxFeaturesViewer)
        self.tableViewFeatures.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.tableViewFeatures.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableViewFeatures.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.tableViewFeatures.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableViewFeatures.setObjectName("tableViewFeatures")
        self.verticalLayout.addWidget(self.tableViewFeatures)
        self.gridLayout.addWidget(self.groupBoxFeaturesViewer, 1, 0, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(Dialog)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 0, 0, 1, 1)
        self.lineEditRelationName = QtWidgets.QLineEdit(self.groupBox)
        self.lineEditRelationName.setObjectName("lineEditRelationName")
        self.gridLayout_2.addWidget(self.lineEditRelationName, 0, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 1, 0, 1, 1)
        self.listViewFieldSelection = QtWidgets.QListView(self.groupBox)
        self.listViewFieldSelection.setMaximumSize(QtCore.QSize(16777215, 130))
        self.listViewFieldSelection.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.listViewFieldSelection.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.listViewFieldSelection.setObjectName("listViewFieldSelection")
        self.gridLayout_2.addWidget(self.listViewFieldSelection, 1, 1, 1, 1)
        self.checkBoxImportGeometry = QtWidgets.QCheckBox(self.groupBox)
        self.checkBoxImportGeometry.setChecked(True)
        self.checkBoxImportGeometry.setObjectName("checkBoxImportGeometry")
        self.gridLayout_2.addWidget(self.checkBoxImportGeometry, 2, 1, 1, 1)
        self.gridLayout.addWidget(self.groupBox, 2, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.pushButtonImport = QtWidgets.QPushButton(Dialog)
        self.pushButtonImport.setObjectName("pushButtonImport")
        self.horizontalLayout.addWidget(self.pushButtonImport)
        self.pushButtonCancel = QtWidgets.QPushButton(Dialog)
        self.pushButtonCancel.setObjectName("pushButtonCancel")
        self.horizontalLayout.addWidget(self.pushButtonCancel)
        self.gridLayout.addLayout(self.horizontalLayout, 3, 0, 1, 1)
        self.labelLayer.setBuddy(self.comboBoxLayers)

        self.retranslateUi(Dialog)
        self.pushButtonCancel.clicked.connect(Dialog.close)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Import object from QGIS layer"))
        self.groupBox_2.setTitle(_translate("Dialog", "Layer"))
        self.labelLayer.setText(_translate("Dialog", "Layer"))
        self.label.setText(_translate("Dialog", "Geometry"))
        self.label_2.setText(_translate("Dialog", "Features"))
        self.groupBoxFeaturesViewer.setTitle(_translate("Dialog", "Features Viewer"))
        self.groupBox.setTitle(_translate("Dialog", "Import Properties"))
        self.label_3.setText(_translate("Dialog", "Relation name"))
        self.label_4.setText(_translate("Dialog", "Field selection"))
        self.checkBoxImportGeometry.setText(_translate("Dialog", "Import geometry"))
        self.pushButtonImport.setText(_translate("Dialog", "&Import"))
        self.pushButtonCancel.setText(_translate("Dialog", "&Cancel"))

