# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainWindowView.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(813, 641)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/mainwindow.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setToolButtonStyle(QtCore.Qt.ToolButtonTextOnly)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.splitter = QtWidgets.QSplitter(self.centralwidget)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.splitter)
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.leftArea = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.leftArea.setContentsMargins(0, 0, 0, 0)
        self.leftArea.setObjectName("leftArea")
        self.treeView = QtWidgets.QTreeView(self.horizontalLayoutWidget)
        self.treeView.setMinimumSize(QtCore.QSize(0, 0))
        self.treeView.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.treeView.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.treeView.setObjectName("treeView")
        self.leftArea.addWidget(self.treeView)
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.splitter)
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.rightArea = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.rightArea.setContentsMargins(0, 0, 0, 0)
        self.rightArea.setSpacing(6)
        self.rightArea.setObjectName("rightArea")
        self.tabWidget = QtWidgets.QTabWidget(self.horizontalLayoutWidget_2)
        self.tabWidget.setMinimumSize(QtCore.QSize(0, 0))
        self.tabWidget.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.tabWidget.setBaseSize(QtCore.QSize(0, 0))
        self.tabWidget.setObjectName("tabWidget")
        self.tab1 = QtWidgets.QWidget()
        self.tab1.setObjectName("tab1")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.tab1)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.tabLayout = QtWidgets.QVBoxLayout()
        self.tabLayout.setSpacing(0)
        self.tabLayout.setObjectName("tabLayout")
        self.horizontalLayout.addLayout(self.tabLayout)
        self.tabWidget.addTab(self.tab1, "")
        self.rightArea.addWidget(self.tabWidget)
        self.gridLayout.addWidget(self.splitter, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 813, 21))
        self.menubar.setObjectName("menubar")
        self.menuVerbindung = QtWidgets.QMenu(self.menubar)
        self.menuVerbindung.setObjectName("menuVerbindung")
        self.menuImport = QtWidgets.QMenu(self.menubar)
        self.menuImport.setObjectName("menuImport")
        self.menuSettings = QtWidgets.QMenu(self.menubar)
        self.menuSettings.setObjectName("menuSettings")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        self.menuDatabase = QtWidgets.QMenu(self.menubar)
        self.menuDatabase.setObjectName("menuDatabase")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actionConnectToSecondoServer = QtWidgets.QAction(MainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/connectserver.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionConnectToSecondoServer.setIcon(icon1)
        self.actionConnectToSecondoServer.setObjectName("actionConnectToSecondoServer")
        self.actionExit = QtWidgets.QAction(MainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/shutdown.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionExit.setIcon(icon2)
        self.actionExit.setObjectName("actionExit")
        self.actionConnect_to_Database = QtWidgets.QAction(MainWindow)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/connect.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionConnect_to_Database.setIcon(icon3)
        self.actionConnect_to_Database.setObjectName("actionConnect_to_Database")
        self.actionDisconnect = QtWidgets.QAction(MainWindow)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icons/disconnect.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionDisconnect.setIcon(icon4)
        self.actionDisconnect.setObjectName("actionDisconnect")
        self.actionRefresh = QtWidgets.QAction(MainWindow)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/icons/refresh.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionRefresh.setIcon(icon5)
        self.actionRefresh.setObjectName("actionRefresh")
        self.actionAdd_New_Database = QtWidgets.QAction(MainWindow)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/icons/adddatabase.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionAdd_New_Database.setIcon(icon6)
        self.actionAdd_New_Database.setObjectName("actionAdd_New_Database")
        self.actionDelete_Database = QtWidgets.QAction(MainWindow)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/icons/deletedatabase.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionDelete_Database.setIcon(icon7)
        self.actionDelete_Database.setObjectName("actionDelete_Database")
        self.actionCreateNewRelation = QtWidgets.QAction(MainWindow)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/icons/objectrel.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionCreateNewRelation.setIcon(icon8)
        self.actionCreateNewRelation.setObjectName("actionCreateNewRelation")
        self.actionFrom_QGIS_Layer = QtWidgets.QAction(MainWindow)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/icons/objectmap.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionFrom_QGIS_Layer.setIcon(icon9)
        self.actionFrom_QGIS_Layer.setObjectName("actionFrom_QGIS_Layer")
        self.actionSettings = QtWidgets.QAction(MainWindow)
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(":/icons/settings.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSettings.setIcon(icon10)
        self.actionSettings.setObjectName("actionSettings")
        self.actionAbout_SecondoDB_for_QGIS = QtWidgets.QAction(MainWindow)
        self.actionAbout_SecondoDB_for_QGIS.setIcon(icon)
        self.actionAbout_SecondoDB_for_QGIS.setObjectName("actionAbout_SecondoDB_for_QGIS")
        self.actionQuery = QtWidgets.QAction(MainWindow)
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(":/icons/query.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionQuery.setIcon(icon11)
        self.actionQuery.setObjectName("actionQuery")
        self.actionFrom_Selected_Feature_in_Active_QGIS_Layer = QtWidgets.QAction(MainWindow)
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap(":/icons/objectpoints.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionFrom_Selected_Feature_in_Active_QGIS_Layer.setIcon(icon12)
        self.actionFrom_Selected_Feature_in_Active_QGIS_Layer.setObjectName("actionFrom_Selected_Feature_in_Active_QGIS_Layer")
        self.actionDisconnectFromServer = QtWidgets.QAction(MainWindow)
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap(":/icons/objectedge.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionDisconnectFromServer.setIcon(icon13)
        self.actionDisconnectFromServer.setObjectName("actionDisconnectFromServer")
        self.actionDeleteObject = QtWidgets.QAction(MainWindow)
        icon14 = QtGui.QIcon()
        icon14.addPixmap(QtGui.QPixmap(":/icons/deleteobject.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionDeleteObject.setIcon(icon14)
        self.actionDeleteObject.setObjectName("actionDeleteObject")
        self.actionUser_Documentation = QtWidgets.QAction(MainWindow)
        icon15 = QtGui.QIcon()
        icon15.addPixmap(QtGui.QPixmap(":/icons/userdoc.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionUser_Documentation.setIcon(icon15)
        self.actionUser_Documentation.setObjectName("actionUser_Documentation")
        self.menuVerbindung.addAction(self.actionConnectToSecondoServer)
        self.menuVerbindung.addAction(self.actionDisconnectFromServer)
        self.menuVerbindung.addSeparator()
        self.menuVerbindung.addAction(self.actionExit)
        self.menuImport.addAction(self.actionFrom_QGIS_Layer)
        self.menuImport.addAction(self.actionFrom_Selected_Feature_in_Active_QGIS_Layer)
        self.menuSettings.addAction(self.actionSettings)
        self.menuHelp.addAction(self.actionUser_Documentation)
        self.menuHelp.addSeparator()
        self.menuHelp.addAction(self.actionAbout_SecondoDB_for_QGIS)
        self.menuDatabase.addAction(self.actionConnect_to_Database)
        self.menuDatabase.addAction(self.actionDisconnect)
        self.menuDatabase.addAction(self.actionRefresh)
        self.menuDatabase.addSeparator()
        self.menuDatabase.addAction(self.actionAdd_New_Database)
        self.menuDatabase.addAction(self.actionDelete_Database)
        self.menuDatabase.addSeparator()
        self.menuDatabase.addAction(self.actionCreateNewRelation)
        self.menuDatabase.addAction(self.actionDeleteObject)
        self.menuDatabase.addSeparator()
        self.menuDatabase.addAction(self.actionQuery)
        self.menubar.addAction(self.menuVerbindung.menuAction())
        self.menubar.addAction(self.menuDatabase.menuAction())
        self.menubar.addAction(self.menuImport.menuAction())
        self.menubar.addAction(self.menuSettings.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())
        self.toolBar.addAction(self.actionConnect_to_Database)
        self.toolBar.addAction(self.actionDisconnect)
        self.toolBar.addAction(self.actionRefresh)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionAdd_New_Database)
        self.toolBar.addAction(self.actionDelete_Database)
        self.toolBar.addSeparator()
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionCreateNewRelation)
        self.toolBar.addAction(self.actionDeleteObject)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionQuery)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionFrom_QGIS_Layer)
        self.toolBar.addAction(self.actionFrom_Selected_Feature_in_Active_QGIS_Layer)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        self.actionExit.triggered.connect(MainWindow.close)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "SecondoDB"))
        self.menuVerbindung.setTitle(_translate("MainWindow", "Server Connection"))
        self.menuImport.setTitle(_translate("MainWindow", "Import"))
        self.menuSettings.setTitle(_translate("MainWindow", "Settings"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.menuDatabase.setTitle(_translate("MainWindow", "Database"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.actionConnectToSecondoServer.setText(_translate("MainWindow", "Connect to Secondo Server"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))
        self.actionConnect_to_Database.setText(_translate("MainWindow", "Connect to Database"))
        self.actionConnect_to_Database.setIconText(_translate("MainWindow", "Connect to Database"))
        self.actionDisconnect.setText(_translate("MainWindow", "Disconnect from Database"))
        self.actionRefresh.setText(_translate("MainWindow", "Refresh Database Objects"))
        self.actionAdd_New_Database.setText(_translate("MainWindow", "Add New Database"))
        self.actionDelete_Database.setText(_translate("MainWindow", "Delete Database"))
        self.actionCreateNewRelation.setText(_translate("MainWindow", "Create New Relation"))
        self.actionCreateNewRelation.setToolTip(_translate("MainWindow", "Creates a new relation on the opened database."))
        self.actionFrom_QGIS_Layer.setText(_translate("MainWindow", "From QGIS-Layer..."))
        self.actionSettings.setText(_translate("MainWindow", "Settings..."))
        self.actionAbout_SecondoDB_for_QGIS.setText(_translate("MainWindow", "About SecondoDB for QGIS"))
        self.actionQuery.setText(_translate("MainWindow", "Execute Query"))
        self.actionQuery.setToolTip(_translate("MainWindow", "Formulate a query on the current database."))
        self.actionFrom_Selected_Feature_in_Active_QGIS_Layer.setText(_translate("MainWindow", "From Selected Feature in Active QGIS-Layer..."))
        self.actionDisconnectFromServer.setText(_translate("MainWindow", "Disconnect"))
        self.actionDeleteObject.setText(_translate("MainWindow", "Delete Selected Object"))
        self.actionUser_Documentation.setText(_translate("MainWindow", "User Documentation"))

