
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Sat Feb 23 21:04:08 CET 2013
//----------------------------------------------------

package sj.lang.JavaListExpr;

import java.io.Reader;
import sj.lang.ListExpr;
//import sj.lang.JavaListExpr.NLTokenizer;

/** CUP v0.10k generated parser.
  * @version Sat Feb 23 21:04:08 CET 2013
  */
public class NLParser extends lib.java_cup10.runtime.lr_parser {

  /** Default constructor. */
  public NLParser() {super();}

  /** Constructor which sets the default scanner. */
  public NLParser(lib.java_cup10.runtime.Scanner s) {super(s);}

  /** Production table. */
  protected static final short _production_table[][] = 
    unpackFromStrings(new String[] {
    "\000\013\000\002\002\004\000\002\004\003\000\002\003" +
    "\005\000\002\003\003\000\002\003\003\000\002\003\003" +
    "\000\002\003\003\000\002\003\003\000\002\003\003\000" +
    "\002\005\004\000\002\005\002" });

  /** Access to production table. */
  public short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static final short[][] _action_table = 
    unpackFromStrings(new String[] {
    "\000\016\000\020\004\013\005\005\006\004\007\006\010" +
    "\010\011\014\012\011\001\002\000\024\002\ufffc\004\ufffc" +
    "\005\ufffc\006\ufffc\007\ufffc\010\ufffc\011\ufffc\012\ufffc\013" +
    "\ufffc\001\002\000\024\002\ufffd\004\ufffd\005\ufffd\006\ufffd" +
    "\007\ufffd\010\ufffd\011\ufffd\012\ufffd\013\ufffd\001\002\000" +
    "\024\002\ufffb\004\ufffb\005\ufffb\006\ufffb\007\ufffb\010\ufffb" +
    "\011\ufffb\012\ufffb\013\ufffb\001\002\000\004\002\000\001" +
    "\002\000\024\002\ufffa\004\ufffa\005\ufffa\006\ufffa\007\ufffa" +
    "\010\ufffa\011\ufffa\012\ufffa\013\ufffa\001\002\000\022\004" +
    "\ufff7\005\ufff7\006\ufff7\007\ufff7\010\ufff7\011\ufff7\012\ufff7" +
    "\013\ufff7\001\002\000\004\002\015\001\002\000\024\002" +
    "\ufffe\004\ufffe\005\ufffe\006\ufffe\007\ufffe\010\ufffe\011\ufffe" +
    "\012\ufffe\013\ufffe\001\002\000\024\002\ufff9\004\ufff9\005" +
    "\ufff9\006\ufff9\007\ufff9\010\ufff9\011\ufff9\012\ufff9\013\ufff9" +
    "\001\002\000\004\002\001\001\002\000\022\004\013\005" +
    "\005\006\004\007\006\010\010\011\014\012\011\013\020" +
    "\001\002\000\022\004\ufff8\005\ufff8\006\ufff8\007\ufff8\010" +
    "\ufff8\011\ufff8\012\ufff8\013\ufff8\001\002\000\024\002\uffff" +
    "\004\uffff\005\uffff\006\uffff\007\uffff\010\uffff\011\uffff\012" +
    "\uffff\013\uffff\001\002" });

  /** Access to parse-action table. */
  public short[][] action_table() {return _action_table;}

  /** <code>reduce_goto</code> table. */
  protected static final short[][] _reduce_table = 
    unpackFromStrings(new String[] {
    "\000\016\000\006\003\006\004\011\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\004\005\015\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\004\003\016\001\001\000\002\001\001\000\002\001" +
    "\001" });

  /** Access to <code>reduce_goto</code> table. */
  public short[][] reduce_table() {return _reduce_table;}

  /** Instance of action encapsulation class. */
  protected CUP$NLParser$actions action_obj;

  /** Action encapsulation object initializer. */
  protected void init_actions()
    {
      action_obj = new CUP$NLParser$actions(this);
    }

  /** Invoke a user supplied parse action. */
  public lib.java_cup10.runtime.Symbol do_action(
    int                        act_num,
    lib.java_cup10.runtime.lr_parser parser,
    java.util.Stack            stack,
    int                        top)
    throws java.lang.Exception
  {
    /* call code in generated class */
    return action_obj.CUP$NLParser$do_action(act_num, parser, stack, top);
  }

  /** Indicates start state. */
  public int start_state() {return 0;}
  /** Indicates start production. */
  public int start_production() {return 0;}

  /** <code>EOF</code> Symbol index. */
  public int EOF_sym() {return 0;}

  /** <code>error</code> Symbol index. */
  public int error_sym() {return 1;}


  /** User initialization code. */
  public void user_init() throws java.lang.Exception
    {

    // If the tokenizer was not initialized, then the parser was created
    // using the standard constructor (with no parameters), what means that
    // the tokenizer (scaner) must read from the standard input.
    // So, it creates the tokenizer using the standard input as argument.
    if (this.tokenizer == null){
      this.tokenizer = new NLTokenizer(System.in);
    }
  
    }

  /** Scan to get the next Symbol. */
  public lib.java_cup10.runtime.Symbol scan()
    throws java.lang.Exception
    {

    NLToken result = this.tokenizer.nextToken();
    this.linePos = result.linePos;
    this.charPos = result.charPos;
    return result;
  
    }


    // NLTokenizer object to be used as tokenizer in this NLParser object.
    public NLTokenizer tokenizer = null;

    // The number of line of the input where the parser is reading.
    // It considers the first line is line 1.
    public int linePos;
    // The number of character of the input where the parser is reading.
    // It considers the first character as character 1.
    public int charPos;
    // Defines a constructor for this class,which gets the input Reader as
    // argument.
    // The parser class must have the name ~NLParser~.
    public NLParser(Reader inputReader){
      // Calls the code of the predefined constructor.
      this();
      // Creates the tokenizer and setups it to read from the given Reader
      // object.
      this.tokenizer = new NLTokenizer(inputReader);
    }
  
}

/** Cup generated class to encapsulate user supplied action code.*/
class CUP$NLParser$actions {
  private final NLParser parser;

  /** Constructor */
  CUP$NLParser$actions(NLParser parser) {
    this.parser = parser;
  }

  /** Method with the actual generated action code. */
  public final lib.java_cup10.runtime.Symbol CUP$NLParser$do_action(
    int                        CUP$NLParser$act_num,
    lib.java_cup10.runtime.lr_parser CUP$NLParser$parser,
    java.util.Stack            CUP$NLParser$stack,
    int                        CUP$NLParser$top)
    throws java.lang.Exception
    {
      /* Symbol object for return from actions */
      lib.java_cup10.runtime.Symbol CUP$NLParser$result;

      /* select the action based on the action number */
      switch (CUP$NLParser$act_num)
        {
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 10: // list_expr_seq ::= 
            {
              Stack RESULT = null;
		
		    RESULT = new Stack();
                  
              CUP$NLParser$result = new lib.java_cup10.runtime.Symbol(3/*list_expr_seq*/, ((lib.java_cup10.runtime.Symbol)CUP$NLParser$stack.elementAt(CUP$NLParser$top-0)).right, ((lib.java_cup10.runtime.Symbol)CUP$NLParser$stack.elementAt(CUP$NLParser$top-0)).right, RESULT);
            }
          return CUP$NLParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 9: // list_expr_seq ::= list_expr_seq list_expr 
            {
              Stack RESULT = null;
		int listSeqleft = ((lib.java_cup10.runtime.Symbol)CUP$NLParser$stack.elementAt(CUP$NLParser$top-1)).left;
		int listSeqright = ((lib.java_cup10.runtime.Symbol)CUP$NLParser$stack.elementAt(CUP$NLParser$top-1)).right;
		Stack listSeq = (Stack)((lib.java_cup10.runtime.Symbol) CUP$NLParser$stack.elementAt(CUP$NLParser$top-1)).value;
		int listExprleft = ((lib.java_cup10.runtime.Symbol)CUP$NLParser$stack.elementAt(CUP$NLParser$top-0)).left;
		int listExprright = ((lib.java_cup10.runtime.Symbol)CUP$NLParser$stack.elementAt(CUP$NLParser$top-0)).right;
		ListExpr listExpr = (ListExpr)((lib.java_cup10.runtime.Symbol) CUP$NLParser$stack.elementAt(CUP$NLParser$top-0)).value;
		
                    // The value of a ~list_expr_seq~ is stored as a stack,
                    // because for using the ~cons()~ method of the ~ListExpr~
                    // class we need to use the elements in reverse order to
                    // the one with which we get them. So we store all them
                    // and when we find apply the rule 1 we build the
                    // equivalent ListExpr value.
                    listSeq.push(listExpr);
                    RESULT = listSeq;
                  
              CUP$NLParser$result = new lib.java_cup10.runtime.Symbol(3/*list_expr_seq*/, ((lib.java_cup10.runtime.Symbol)CUP$NLParser$stack.elementAt(CUP$NLParser$top-1)).left, ((lib.java_cup10.runtime.Symbol)CUP$NLParser$stack.elementAt(CUP$NLParser$top-0)).right, RESULT);
            }
          return CUP$NLParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 8: // list_expr ::= TT_TEXT_ATOM 
            {
              ListExpr RESULT = null;
		int atomleft = ((lib.java_cup10.runtime.Symbol)CUP$NLParser$stack.elementAt(CUP$NLParser$top-0)).left;
		int atomright = ((lib.java_cup10.runtime.Symbol)CUP$NLParser$stack.elementAt(CUP$NLParser$top-0)).right;
		ListExpr atom = (ListExpr)((lib.java_cup10.runtime.Symbol) CUP$NLParser$stack.elementAt(CUP$NLParser$top-0)).value;
		
                RESULT = atom;
              
              CUP$NLParser$result = new lib.java_cup10.runtime.Symbol(1/*list_expr*/, ((lib.java_cup10.runtime.Symbol)CUP$NLParser$stack.elementAt(CUP$NLParser$top-0)).left, ((lib.java_cup10.runtime.Symbol)CUP$NLParser$stack.elementAt(CUP$NLParser$top-0)).right, RESULT);
            }
          return CUP$NLParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 7: // list_expr ::= TT_SYMBOL_ATOM 
            {
              ListExpr RESULT = null;
		int atomleft = ((lib.java_cup10.runtime.Symbol)CUP$NLParser$stack.elementAt(CUP$NLParser$top-0)).left;
		int atomright = ((lib.java_cup10.runtime.Symbol)CUP$NLParser$stack.elementAt(CUP$NLParser$top-0)).right;
		ListExpr atom = (ListExpr)((lib.java_cup10.runtime.Symbol) CUP$NLParser$stack.elementAt(CUP$NLParser$top-0)).value;
		
                RESULT = atom;
              
              CUP$NLParser$result = new lib.java_cup10.runtime.Symbol(1/*list_expr*/, ((lib.java_cup10.runtime.Symbol)CUP$NLParser$stack.elementAt(CUP$NLParser$top-0)).left, ((lib.java_cup10.runtime.Symbol)CUP$NLParser$stack.elementAt(CUP$NLParser$top-0)).right, RESULT);
            }
          return CUP$NLParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 6: // list_expr ::= TT_STRING_ATOM 
            {
              ListExpr RESULT = null;
		int atomleft = ((lib.java_cup10.runtime.Symbol)CUP$NLParser$stack.elementAt(CUP$NLParser$top-0)).left;
		int atomright = ((lib.java_cup10.runtime.Symbol)CUP$NLParser$stack.elementAt(CUP$NLParser$top-0)).right;
		ListExpr atom = (ListExpr)((lib.java_cup10.runtime.Symbol) CUP$NLParser$stack.elementAt(CUP$NLParser$top-0)).value;
		
                RESULT = atom;
              
              CUP$NLParser$result = new lib.java_cup10.runtime.Symbol(1/*list_expr*/, ((lib.java_cup10.runtime.Symbol)CUP$NLParser$stack.elementAt(CUP$NLParser$top-0)).left, ((lib.java_cup10.runtime.Symbol)CUP$NLParser$stack.elementAt(CUP$NLParser$top-0)).right, RESULT);
            }
          return CUP$NLParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 5: // list_expr ::= TT_REAL_ATOM 
            {
              ListExpr RESULT = null;
		int atomleft = ((lib.java_cup10.runtime.Symbol)CUP$NLParser$stack.elementAt(CUP$NLParser$top-0)).left;
		int atomright = ((lib.java_cup10.runtime.Symbol)CUP$NLParser$stack.elementAt(CUP$NLParser$top-0)).right;
		ListExpr atom = (ListExpr)((lib.java_cup10.runtime.Symbol) CUP$NLParser$stack.elementAt(CUP$NLParser$top-0)).value;
		
                RESULT = atom;
              
              CUP$NLParser$result = new lib.java_cup10.runtime.Symbol(1/*list_expr*/, ((lib.java_cup10.runtime.Symbol)CUP$NLParser$stack.elementAt(CUP$NLParser$top-0)).left, ((lib.java_cup10.runtime.Symbol)CUP$NLParser$stack.elementAt(CUP$NLParser$top-0)).right, RESULT);
            }
          return CUP$NLParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 4: // list_expr ::= TT_BOOL_ATOM 
            {
              ListExpr RESULT = null;
		int atomleft = ((lib.java_cup10.runtime.Symbol)CUP$NLParser$stack.elementAt(CUP$NLParser$top-0)).left;
		int atomright = ((lib.java_cup10.runtime.Symbol)CUP$NLParser$stack.elementAt(CUP$NLParser$top-0)).right;
		ListExpr atom = (ListExpr)((lib.java_cup10.runtime.Symbol) CUP$NLParser$stack.elementAt(CUP$NLParser$top-0)).value;
		
                RESULT = atom;
              
              CUP$NLParser$result = new lib.java_cup10.runtime.Symbol(1/*list_expr*/, ((lib.java_cup10.runtime.Symbol)CUP$NLParser$stack.elementAt(CUP$NLParser$top-0)).left, ((lib.java_cup10.runtime.Symbol)CUP$NLParser$stack.elementAt(CUP$NLParser$top-0)).right, RESULT);
            }
          return CUP$NLParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 3: // list_expr ::= TT_INT_ATOM 
            {
              ListExpr RESULT = null;
		int atomleft = ((lib.java_cup10.runtime.Symbol)CUP$NLParser$stack.elementAt(CUP$NLParser$top-0)).left;
		int atomright = ((lib.java_cup10.runtime.Symbol)CUP$NLParser$stack.elementAt(CUP$NLParser$top-0)).right;
		ListExpr atom = (ListExpr)((lib.java_cup10.runtime.Symbol) CUP$NLParser$stack.elementAt(CUP$NLParser$top-0)).value;
		
                RESULT = atom;
              
              CUP$NLParser$result = new lib.java_cup10.runtime.Symbol(1/*list_expr*/, ((lib.java_cup10.runtime.Symbol)CUP$NLParser$stack.elementAt(CUP$NLParser$top-0)).left, ((lib.java_cup10.runtime.Symbol)CUP$NLParser$stack.elementAt(CUP$NLParser$top-0)).right, RESULT);
            }
          return CUP$NLParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 2: // list_expr ::= TT_OPEN_PAR list_expr_seq TT_CLOSE_PAR 
            {
              ListExpr RESULT = null;
		int listSeqleft = ((lib.java_cup10.runtime.Symbol)CUP$NLParser$stack.elementAt(CUP$NLParser$top-1)).left;
		int listSeqright = ((lib.java_cup10.runtime.Symbol)CUP$NLParser$stack.elementAt(CUP$NLParser$top-1)).right;
		Stack listSeq = (Stack)((lib.java_cup10.runtime.Symbol) CUP$NLParser$stack.elementAt(CUP$NLParser$top-1)).value;
		
                 // It takes the Stack in ~listSeq~ and builds the
                 // equivalent ListExpr.
                 ListExpr auxList = ListExpr.theEmptyList();
		 while(!listSeq.isEmpty())
                    auxList= ListExpr.cons((ListExpr)listSeq.pop(), auxList);
                 RESULT = auxList;
              
              CUP$NLParser$result = new lib.java_cup10.runtime.Symbol(1/*list_expr*/, ((lib.java_cup10.runtime.Symbol)CUP$NLParser$stack.elementAt(CUP$NLParser$top-2)).left, ((lib.java_cup10.runtime.Symbol)CUP$NLParser$stack.elementAt(CUP$NLParser$top-0)).right, RESULT);
            }
          return CUP$NLParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 1: // ok ::= list_expr 
            {
              ListExpr RESULT = null;
		int list1left = ((lib.java_cup10.runtime.Symbol)CUP$NLParser$stack.elementAt(CUP$NLParser$top-0)).left;
		int list1right = ((lib.java_cup10.runtime.Symbol)CUP$NLParser$stack.elementAt(CUP$NLParser$top-0)).right;
		ListExpr list1 = (ListExpr)((lib.java_cup10.runtime.Symbol) CUP$NLParser$stack.elementAt(CUP$NLParser$top-0)).value;
		 
            RESULT = list1;
         
              CUP$NLParser$result = new lib.java_cup10.runtime.Symbol(2/*ok*/, ((lib.java_cup10.runtime.Symbol)CUP$NLParser$stack.elementAt(CUP$NLParser$top-0)).left, ((lib.java_cup10.runtime.Symbol)CUP$NLParser$stack.elementAt(CUP$NLParser$top-0)).right, RESULT);
            }
          return CUP$NLParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 0: // $START ::= ok EOF 
            {
              Object RESULT = null;
		int start_valleft = ((lib.java_cup10.runtime.Symbol)CUP$NLParser$stack.elementAt(CUP$NLParser$top-1)).left;
		int start_valright = ((lib.java_cup10.runtime.Symbol)CUP$NLParser$stack.elementAt(CUP$NLParser$top-1)).right;
		ListExpr start_val = (ListExpr)((lib.java_cup10.runtime.Symbol) CUP$NLParser$stack.elementAt(CUP$NLParser$top-1)).value;
		RESULT = start_val;
              CUP$NLParser$result = new lib.java_cup10.runtime.Symbol(0/*$START*/, ((lib.java_cup10.runtime.Symbol)CUP$NLParser$stack.elementAt(CUP$NLParser$top-1)).left, ((lib.java_cup10.runtime.Symbol)CUP$NLParser$stack.elementAt(CUP$NLParser$top-0)).right, RESULT);
            }
          /* ACCEPT */
          CUP$NLParser$parser.done_parsing();
          return CUP$NLParser$result;

          /* . . . . . .*/
          default:
            throw new Exception(
               "Invalid action number found in internal parse table");

        }
    }
}

