
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Wed Oct 31 04:42:02 PDT 2012
//----------------------------------------------------

package sj.lang.JavaListExpr;

/** CUP generated interface containing symbol constants. */
public interface NLSymbol {
  /* terminals */
  public static final int TT_REAL_ATOM = 4;
  public static final int TT_BOOL_ATOM = 3;
  public static final int TT_STRING_ATOM = 5;
  public static final int EOF = 0;
  public static final int TT_CLOSE_PAR = 9;
  public static final int TT_SYMBOL_ATOM = 6;
  public static final int TT_OPEN_PAR = 8;
  public static final int error = 1;
  public static final int TT_INT_ATOM = 2;
  public static final int TT_TEXT_ATOM = 7;
}
