#!/bin/bash 
#
# pd2dvi <file> - Converts a PD file to a TEX file
#
# May 2004, M. Spiekermann

pdFile="$1"
texFile="$1.tex"
dviFile="$1.dvi"
logFile="$1.log"
auxFile="$1.aux"

if { ! pd2tex $1; }; then
   exit 1
fi

if { ! latex --interaction="nonstopmode" $texFile; }; then

   printf "\n LaTeX-Error: Could not create $dviFile! "
   printf "\n              Study LaTeX's messages above and correct"
   printf "\n              the error in the PD-file $pdFile. \n\n"
   rm -f $texFile $auxFile $dviFile
   exit 2
fi

