#!/bin/sh
#
# pdpreview <file> <suffix> <program> - previews the given file with the given program.  
#
# May 2004, M. Spiekermann

file="$PD_TMP/$1.$2"
progname="$3"
texFile="$PD_TMP/$1.tex"
auxFile="$PD_TMP/$1.aux"
logFile="$PD_TMP/$1.log"

$progname $file 
