#!/bin/bash
#
# pdpreview <file> <suffix> <program> - previews the given file with the given program.  
#
# May 2004, M. Spiekermann

file="$1.$2"
progname="$3"
texFile="$1.tex"
auxFile="$1.aux"
logFile="$1.log"

$progname $file 
rm -f $logFile $texFile $auxFile $file
