#!/bin/sh
# This file is part of the PD system
# Copyright (C) 1998 Ralf Hartmut Gueting, Fachbereich Informatik, FernUniversitaet Hagen

# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# pdview <file> - previews an PD file with LaTeX's DVI previewer
#
# May 2004, M. Spiekermann

# Resolve the other PD tools relative to this script rather than relying on
# PATH, so the toolchain also works when invoked by an absolute path.
pdDir=$(cd "$(dirname "$0")" && pwd)
PATH="$pdDir:$PATH"
export PATH

pd2dvi $1;

pdpreview $1 dvi "${PD_DVI_VIEWER:-$pdDir/pdopen}" &
