/*
 * ConvexHullTreeViewer.java
 *
 * Created on 11. Juli 2007, 00:15
 */

package movingregion;

import java.awt.*;
import javax.swing.*;

/**
 *
 * @author  java
 */
public class ConvexHullTreeViewer extends javax.swing.JPanel
{
    ConvexHullTreeTreeViewer treeView;
    ConvexHullTreePolygonViewer polyView;
    JScrollPane Scroll;
    MatchViewer myMatch=null;
    
    /** Creates new form ConvexHullTreeViewer */
    public ConvexHullTreeViewer(Region node)    
    {
        treeView=new ConvexHullTreeTreeViewer(node,this);
        polyView=new ConvexHullTreePolygonViewer(node);
        setLayout(new BorderLayout());
        Scroll=new JScrollPane( JScrollPane.VERTICAL_SCROLLBAR_AS_NEEDED,JScrollPane.HORIZONTAL_SCROLLBAR_AS_NEEDED );
        Scroll.setViewportView(polyView);
        add(treeView,BorderLayout.WEST);
        add(Scroll,BorderLayout.CENTER);
    }
    
    public ConvexHullTreeViewer(Region node,MatchViewer myMatch)    
    {
        this(node);
        this.myMatch=myMatch;
    }
    
    public void changeSelection(RegionTreeNode[] nodes)
    {
        polyView.setActual(nodes);
        this.treeView.setActual(nodes);
        if(myMatch!=null)
        {            
            myMatch.changeSelection(nodes);
        }
    }
    
    public void setActual(RegionTreeNode[] nodes)
    {
        polyView.setActual(nodes);
        treeView.setActual(nodes);
    }
    
    
    public void setHei(int height)
    {
        int height2= height-this.Scroll.getHorizontalScrollBar().getHeight();
        polyView.setHei(height2-10);
        treeView.setHeig(height2-10);
    }
    
    
    public void setWid(int width)
    {
        int width2=width-10;
        polyView.setWid((int)Math.ceil(width2*2.0/3.0));
        treeView.setWid((int)Math.floor(width2*1.0/3.0));
    }
    
    public boolean contains(RegionTreeNode node)
    {
        return(treeView.findTreeNode(node)!=null);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        setLayout(new java.awt.GridLayout());

    }// </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
    
}
