

package movingregion;

import java.awt.*;
import javax.swing.*;
/**
 *
 * @author  java
 */
public class SectionViewer extends javax.swing.JPanel
{
    int wid=500;
    int hei=400;
    mLineRep myTri;
    
    public SectionViewer(mLineRep myTri)
    {
        this.myTri=myTri;
        
        initComponents();        
        TimesSpinner.setModel(new SpinnerNumberModel(3,2,100,1));
        SectionMain.setLayout(new GridLayout(3,1));
        SectionMain.add(new oneSectionViewer(myTri,0,2));
        SectionMain.add(new oneSectionViewer(myTri,1,2));
        SectionMain.add(new oneSectionViewer(myTri,2,2));
    }        
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents()
    {
        JustALayoutPanel = new javax.swing.JPanel();
        TimesSpinner = new javax.swing.JSpinner();
        Scroller = new javax.swing.JScrollPane();
        SectionMain = new javax.swing.JPanel();

        setLayout(new java.awt.BorderLayout());

        TimesSpinner.addChangeListener(new javax.swing.event.ChangeListener()
        {
            public void stateChanged(javax.swing.event.ChangeEvent evt)
            {
                TimesSpinnerStateChanged(evt);
            }
        });

        JustALayoutPanel.add(TimesSpinner);

        add(JustALayoutPanel, java.awt.BorderLayout.NORTH);

        SectionMain.setLayout(new java.awt.GridLayout());

        Scroller.setViewportView(SectionMain);

        add(Scroller, java.awt.BorderLayout.CENTER);

    }// </editor-fold>//GEN-END:initComponents
    
    private void TimesSpinnerStateChanged(javax.swing.event.ChangeEvent evt)//GEN-FIRST:event_TimesSpinnerStateChanged
    {//GEN-HEADEREND:event_TimesSpinnerStateChanged
        int times=((Integer)TimesSpinner.getValue()).intValue();
        SectionMain.removeAll();
        SectionMain.setLayout(new GridLayout(times,1));
        for(int i=0;i<times;i++)
        {      
            SectionMain.add(new oneSectionViewer(myTri,i,times-1));
        }
        Scroller.setViewportView(SectionMain);
        this.setHei(hei);
        this.setWid(wid);
    }//GEN-LAST:event_TimesSpinnerStateChanged
    
        public void setHei(int height)
    {
        this.hei=height;
        Component[] tmp=SectionMain.getComponents();
        Scroller.setViewportView(SectionMain);
        for(int i=0;i<tmp.length;i++)
        {
            if(tmp[i] instanceof oneSectionViewer)
                ((oneSectionViewer)tmp[i]).setHei((height-this.JustALayoutPanel.getHeight()-this.Scroller.getHorizontalScrollBar().getHeight())/3);
        }        
    }
    
    
    public void setWid(int width)
    {
        this.wid=width;
        Component[] tmp=SectionMain.getComponents();
        Scroller.setViewportView(SectionMain);
        for(int i=0;i<tmp.length;i++)
        {
            if(tmp[i] instanceof oneSectionViewer)
                ((oneSectionViewer)tmp[i]).setWid(width-this.Scroller.getVerticalScrollBar().getWidth()-12);
        }        
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel JustALayoutPanel;
    private javax.swing.JScrollPane Scroller;
    private javax.swing.JPanel SectionMain;
    private javax.swing.JSpinner TimesSpinner;
    // End of variables declaration//GEN-END:variables
    
}
