#line 2 "WebFlex.cc"
#define  YY_INT_ALIGNED short int


/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5
#define YY_FLEX_SUBMINOR_VERSION 27
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined __STDC_VERSION__ && __STDC_VERSION__ >= 199901L
#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;
#endif /* ! C99 */

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif


#endif /* ! FLEXINT_H */


/* begin standard C++ headers. */
#include <iostream> 
#include <errno.h>
#include <stdlib.h>
/* end standard C++ headers. */

#ifdef __cplusplus

/* C++ compilers don't understand traditional function definitions. */
#ifdef YY_TRADITIONAL_FUNC_DEFS
#undef YY_TRADITIONAL_FUNC_DEFS
#endif

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* We're not in a C++ compiler, so by default,
   we generate C99 function defs, unless you explicitly ask
   for traditional defs by defining YY_TRADITIONAL_FUNC_DEFS */

#if __STDC__

#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* For compilers that can't handle prototypes.
 * e.g.,
 * The function prototype
 *    int foo(int x, char* y);
 *
 * ...should be written as
 *    int foo YY_PARAMS((int x, char* y));
 *
 * ...which could possibly generate
 *    int foo ();
 */
#ifdef YY_NO_PROTOS
#define YY_PARAMS(proto) ()
#else
#define YY_PARAMS(proto) proto
#endif


/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)



/* Define these macros to be no-ops. */
#define YY_G(var) (var)
#define YY_PROTO_LAST_ARG
#define YY_PROTO_ONLY_ARG void
#define YY_DEF_LAST_ARG
#ifdef YY_TRADITIONAL_FUNC_DEFS
#define YY_DEF_ONLY_ARG
#else
#define YY_DEF_ONLY_ARG void
#endif
#define YY_DECL_LAST_ARG
#define YY_CALL_LAST_ARG
#define YY_CALL_ONLY_ARG



/* For compilers that need traditional function definitions.
 * e.g.,
 * The function prototype taking 2 arguments
 *    int foo (int x, char* y)
 *
 * ...should be written as
 *    int foo YYFARGS2(int,x, char*,y)
 *
 * ...which could possibly generate
 *    int foo (x,y,yyscanner)
 *        int x;
 *        char * y;
 *        yyscan_t yyscanner;
 */
#ifdef YY_TRADITIONAL_FUNC_DEFS
/* Generate traditional function defs */
#define YYFARGS0(v) (YY_DEF_ONLY_ARG) YY_DECL_LAST_ARG
#define YYFARGS1(t1,n1) (n1 YY_DEF_LAST_ARG) t1 n1; YY_DECL_LAST_ARG
#define YYFARGS2(t1,n1,t2,n2) (n1,n2 YY_DEF_LAST_ARG) t1 n1; t2 n2; YY_DECL_LAST_ARG
#define YYFARGS3(t1,n1,t2,n2,t3,n3) (n1,n2,n3 YY_DEF_LAST_ARG) t1 n1; t2 n2; t3 n3; YY_DECL_LAST_ARG
#else
/* Generate C99 function defs. */
#define YYFARGS0(v) (YY_DEF_ONLY_ARG)
#define YYFARGS1(t1,n1) (t1 n1 YY_DEF_LAST_ARG)
#define YYFARGS2(t1,n1,t2,n2) (t1 n1,t2 n2 YY_DEF_LAST_ARG)
#define YYFARGS3(t1,n1,t2,n2,t3,n3) (t1 n1,t2 n2,t3 n3 YY_DEF_LAST_ARG)
#endif

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN YY_G(yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((YY_G(yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin YY_CALL_LAST_ARG )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#define YY_BUF_SIZE 16384
#endif


#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

extern int yyleng;


#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

#ifdef YY_USE_LINENO
/* Note: We specifically omit the test for yy_rule_can_match_eol because it requires
 *       access to the local variable yy_act. Since yyless() is a macro, it would break
 *       existing scanners that call yyless() from OUTSIDE yylex. 
 *       One obvious solution it to make yy_act a global. I tried that, and saw
 *       a 5% performance hit in a non-yylineno scanner, because yy_act is
 *       normally declared as a register variable-- so it's not worth it.
 */
#define  YY_LESS_LINENO(n) \
        do { \
			int yyl;\
			for ( yyl = n; yyl < yyleng; ++yyl )\
				if ( yytext[yyl] == '\n' )\
					--yylineno;\
        }while(0)
#else
#define YY_LESS_LINENO(n)
#endif

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = YY_G(yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		YY_G(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, YY_G(yytext_ptr) YY_CALL_LAST_ARG )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef unsigned int yy_size_t;
#endif

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{

	std::istream* yy_input_file;


	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

#ifndef yyIN_HEADER /* YY-DISCARD-FROM-HEADER */
#endif /* !yyIN_HEADER YY-END-DISCARD-FROM-HEADER */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer

#ifndef yyIN_HEADER /* YY-DISCARD-FROM-HEADER */
#endif /* !yyIN_HEADER YY-END-DISCARD-FROM-HEADER */

void *yyalloc YY_PARAMS(( yy_size_t YY_PROTO_LAST_ARG ));
void *yyrealloc YY_PARAMS(( void *, yy_size_t YY_PROTO_LAST_ARG ));
void yyfree YY_PARAMS(( void * YY_PROTO_LAST_ARG ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_G(yy_current_buffer) ) \
		YY_G(yy_current_buffer) =    \
            yy_create_buffer( yyin, YY_BUF_SIZE YY_CALL_LAST_ARG); \
	YY_G(yy_current_buffer)->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_G(yy_current_buffer) ) \
		YY_G(yy_current_buffer) =    \
            yy_create_buffer( yyin, YY_BUF_SIZE YY_CALL_LAST_ARG); \
	YY_G(yy_current_buffer)->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_G(yy_current_buffer)->yy_at_bol)

/* Begin user sect3 */

#define yywrap(n) 1
#define YY_SKIP_YYWRAP
#ifndef yyIN_HEADER /* YY-DISCARD-FROM-HEADER */
typedef unsigned char YY_CHAR;
#endif /* !yyIN_HEADER YY-END-DISCARD-FROM-HEADER */
#define yytext_ptr yytext
#define YY_INTERACTIVE
#ifndef yyIN_HEADER /* YY-DISCARD-FROM-HEADER */
#endif /* !yyIN_HEADER YY-END-DISCARD-FROM-HEADER */

#include <FlexLexer.h>

#ifndef yyIN_HEADER /* YY-DISCARD-FROM-HEADER */
#endif /* !yyIN_HEADER YY-END-DISCARD-FROM-HEADER */

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	YY_G(yytext_ptr) = yy_bp; \
	YY_G(yytext_ptr) -= YY_G(yy_more_len); \
	yyleng = (size_t) (yy_cp - YY_G(yytext_ptr)); \
	YY_G(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	YY_G(yy_c_buf_p) = yy_cp;

#ifndef yyIN_HEADER /* YY-DISCARD-FROM-HEADER */
#define YY_NUM_RULES 31
#define YY_END_OF_BUFFER 32
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[449] =
    {   0,
       29,   29,    2,    2,   29,   29,   29,   29,    5,    5,
       29,   29,   29,   29,   29,   29,   10,   10,   29,   29,
       29,   29,   29,   29,   29,   29,   29,   29,   29,   29,
       29,   29,   29,   29,   32,   30,   29,   29,    2,    2,
       30,    2,    2,    2,    2,   30,   30,    5,    5,    5,
       28,   28,   27,   30,   29,   29,   30,   20,   15,   10,
       10,    8,   11,   15,    9,   14,   25,   25,   26,   24,
       18,   18,   18,   18,    6,    6,    6,    7,   13,   30,
       21,   21,   22,   21,   29,    2,    2,    0,    2,    2,
        2,    2,    0,    2,    0,    2,    0,    2,    2,    2,

        0,    2,    2,    2,    1,    0,    3,    4,    5,    0,
        5,    5,    5,    0,    5,    5,    5,    5,    0,    5,
        0,   20,   29,    0,   16,   10,    9,    8,    9,    0,
       13,    0,   12,    0,    2,    0,    2,    0,    2,    0,
        2,    0,    2,    2,    2,    2,    2,    2,    2,    0,
        1,    1,    0,    1,    1,    1,    4,    0,    4,    4,
        4,    4,    4,    4,    0,    0,    0,    0,    0,   16,
       19,    0,    0,    0,    2,    0,    2,    0,    2,    0,
        2,    2,    2,    2,    2,    2,    0,    0,    0,    2,
        2,    0,    2,    2,    2,    2,    2,    1,    1,    0,

        1,    0,    1,    0,    1,    1,    1,    0,    1,    0,
        4,    4,    4,    4,    4,    0,    0,    0,    4,    4,
        0,    4,    4,    4,    4,    4,   16,   17,    0,    0,
        0,    0,    0,    2,    2,    2,    0,    0,    2,    2,
        2,    2,    2,    2,    1,    0,    1,    0,    1,    0,
        1,    0,    1,    1,    1,    1,    1,    1,    1,    0,
        4,    4,    4,    0,    0,    4,    4,    4,    4,    4,
        4,    0,    0,    0,    2,    2,    2,    2,    2,    2,
        2,    2,    0,    1,    0,    1,    0,    1,    0,    1,
        1,    1,    1,    1,    1,    0,    0,    0,    1,    1,

        0,    1,    1,    1,    1,    1,    4,    4,    4,    4,
        4,    4,    4,    4,    0,    0,    0,    2,    2,    2,
        2,    2,    2,    2,    2,    0,    0,    1,    1,    1,
        0,    0,    1,    1,    1,    1,    1,    1,    4,    4,
        4,    4,    4,    4,    4,    4,    0,    0,    0,    2,
        2,    2,    2,    2,    2,    2,    2,    1,    1,    1,
        1,    1,    1,    1,    1,    4,    4,    4,    4,    4,
        4,    4,    4,   23,    2,    2,    2,    2,    2,    2,
        2,    2,    1,    1,    1,    1,    1,    1,    1,    1,
        4,    4,    4,    4,    4,    4,    4,    4,    2,    2,

        2,    2,    2,    2,    2,    1,    1,    1,    1,    1,
        1,    1,    1,    4,    4,    4,    4,    4,    4,    4,
        2,    2,    2,    2,    1,    1,    1,    1,    1,    1,
        1,    1,    4,    4,    4,    4,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    0
    } ;

static yyconst flex_int32_t yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    4,    5,    6,    7,    8,    9,   10,   11,
       12,   13,   14,   15,   16,   17,   18,   19,   20,   21,
       19,   19,   22,   23,   23,   23,   23,   24,   25,   26,
       27,   28,   29,   30,   31,   31,   32,   31,   31,   31,
       33,   33,   34,   33,   33,   33,   33,   33,   33,   35,
       33,   36,   37,   38,   33,   33,   33,   33,   33,   33,
        1,    1,    1,    1,   39,    1,   31,   31,   40,   31,

       31,   31,   33,   33,   41,   33,   33,   33,   33,   33,
       33,   42,   33,   43,   44,   45,   33,   33,   33,   33,
       33,   33,    1,    1,    1,   46,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst flex_int32_t yy_meta[47] =
    {   0,
        1,    2,    2,    3,    2,    4,    1,    1,    1,    1,
        1,    1,    1,    5,    1,    6,    6,    7,    8,    8,
        8,    8,    8,    6,    1,    9,    1,   10,    7,    1,
       11,   11,    6,    6,    6,    6,    6,    6,    3,   11,
        6,    6,    6,    6,    6,    1
    } ;

static yyconst flex_int16_t yy_base[521] =
    {   0,
        0,    2,    5,    0,   50,    0,   52,   54,   60,   94,
       56,   58,   62,   65,   73,   77,  123,    0,  168,  170,
       71,  104,  106,  172,  108,  111,  113,  115,  174,  176,
      178,  182,  187,  189,  587, 3105,  117,  195,  212,  255,
        0,    0,  298,  341,  384,  517,  521,  427,  470,  513,
     3105,  201,  205,  490,  558,  560,  494, 3105, 3105,  209,
      562,    0, 3105,  492,  258, 3105, 3105,  430,  564, 3105,
     3105,  566,  568,  459, 3105,  570,  572, 3105,    0,  450,
     3105,  574,  576,  435,  578,    0,    0,    0,    0,  586,
        0,    0,    0,    0,    0,  394,    0,  392,  629,    0,

        0,    0,    0,    0,  672,  365, 3105,  715,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
      341, 3105,  741,  351,    0,  760,  580,    0,  582,  318,
        0,  321, 3105,  149,    0,    0,    0,    0,  784,    0,
      745,    0,  751,  827,  758,  857,  864,  884,  927,    0,
      306,  970,    0,  285, 1013, 1056,  763,    0, 1084, 1091,
     1098, 1105, 1125, 1168,    0,    0,    0,  267,  265,    0,
     3105,   37,  200,    0,    0,    0,    0,    0,    0,    0,
        0, 1196, 1203, 1210, 1217, 1224, 1242,    0,    0,    0,
     1230,    0, 1235, 1253, 1260, 1267, 1125, 1287,    0,    0,

        0,    0,  220,    0,  199, 1330,    0,    0,    0,    0,
     1358, 1365, 1372, 1379, 1386, 1391,    0, 1396,    0, 1401,
        0, 1406, 1413, 1420, 1427, 1432,    0, 3105,  178,  166,
      162,    0,    0, 1439, 1446, 1453,    0,    0, 1458, 1465,
     1472, 1479, 1486, 1168,    0,    0,    0,    0, 1506,    0,
     1534,    0, 1539, 1559, 1589, 1596, 1603, 1623, 1666,    0,
     1696, 1703, 1710,    0,    0, 1715, 1722, 1729, 1736, 1743,
     1748,  167,  158,  154, 1753, 1760, 1767, 1774, 1781, 1788,
     1795, 1802,    0,    0,    0,    0,    0,    0,    0,    0,
     1807, 1814, 1821, 1828, 1835, 1853,    0,    0,    0, 1841,

        0, 1846, 1864, 1871, 1878, 1890, 1883, 1890, 1901, 1908,
     1915, 1922, 1929, 1936,  147,   79,   62, 1943, 1950, 1957,
     1962, 1969, 1976, 1983, 1990,    0,    0, 1997, 2004, 2011,
        0,    0, 2016, 2023, 2030, 2037, 2044, 2056, 2056, 2067,
     2074, 2049, 2081, 2088, 2095, 2102,   64,   53,   26, 2107,
     2114, 2121, 2128, 2135, 2142, 2149, 2156, 2161, 2168, 2175,
     2182, 2189, 2196, 2203, 2210, 2215, 2222, 2229, 2236, 2243,
     2250, 2257, 2264, 3105, 2269, 2274, 2279, 2284, 2291, 2298,
     2305, 2312, 2319, 2326, 2333, 2338, 2345, 2352, 2359, 2366,
     2371, 2376, 2381, 2386, 2393, 2400, 2407, 2414, 2419, 2424,

     2429, 2434, 2439, 2444, 2449, 2454, 2461, 2468, 2475, 2482,
     2489, 2496, 2503, 2508, 2513, 2518, 2523, 2528, 2533, 2538,
     2543, 2548, 2553, 2558, 2563, 2568, 2573, 2578, 2585, 2592,
     2599, 2606, 2611, 2616, 2621, 2626, 2631, 2636, 2641, 2646,
     2651, 2656, 2661, 2666, 2671, 2676, 2681, 3105, 2704, 2715,
     2726, 2737, 2748, 2759, 2770, 2781, 2785, 2792, 2803, 2812,
     2818, 2829, 2840, 2844, 2848, 2852, 2856, 2860, 2864, 2868,
     2879, 2885, 2889, 2893, 2897, 2901, 2905, 2909, 2913, 2917,
     2921, 2925, 2936, 2947, 2951, 2955, 2959, 2963, 2967, 2971,
     2979, 2980, 2984, 2988, 2992, 2996, 3000, 3004, 3008, 3012,

     3016, 3020, 3024, 3028, 3032, 3036, 3040, 3044, 3048, 3052,
     3056, 3060, 3064, 3068, 3072, 3080, 3081, 3085, 3089, 3093
    } ;

static yyconst flex_int16_t yy_def[521] =
    {   0,
      449,  449,  448,    3,  449,    5,  449,  449,  449,  449,
      450,  450,  449,  449,  451,  451,  448,   17,  452,  452,
      449,  449,  453,  453,  449,  449,  449,  449,  454,  454,
      455,  455,  456,  456,  448,  448,  448,  448,  448,  448,
      457,   39,  448,  448,  448,  458,  448,  448,  448,  448,
      448,  448,  448,  459,  459,  459,  460,  448,  448,  448,
      448,  461,  448,  460,  448,  448,  448,  448,  448,  448,
      448,  448,  448,  448,  448,  448,  448,  448,  462,  463,
      448,  448,  448,  448,  448,   39,   40,  457,   39,  448,
       44,   40,  464,   40,  465,   43,  466,   43,  448,   44,

      467,   44,   45,   45,  448,  458,  448,  448,   48,  468,
       48,   49,   48,  469,   49,   49,   50,   50,  470,   50,
      459,  448,  459,  471,  472,  448,  448,  461,  448,  448,
      462,  463,  448,  448,   90,  473,   90,  474,  448,  475,
       99,  476,   99,  448,   99,   99,   99,  448,  448,  477,
      105,  448,  478,  105,  448,  448,  108,  479,  108,  108,
      108,  108,  448,  448,  480,  481,  482,  483,  484,  472,
      448,  448,  448,  485,  139,  486,  139,  487,  144,  488,
      144,   99,   99,   99,   99,   99,  148,  489,  187,  148,
      149,  490,  149,  149,  149,  149,  491,  448,  152,  492,

      152,  493,  155,  494,  155,  448,  156,  495,  156,  496,
      108,  108,  108,  108,  108,  163,  497,  163,  163,  164,
      498,  164,  164,  164,  164,  448,  472,  448,  448,  448,
      448,  499,  500,   99,   99,   99,  501,  502,  149,  149,
      149,  149,  149,  491,  198,  503,  198,  504,  448,  505,
      206,  506,  206,  448,  206,  206,  206,  448,  448,  507,
      108,  108,  108,  508,  509,  164,  164,  164,  164,  164,
      448,  448,  448,  448,   99,   99,   99,   99,   99,  149,
      149,  149,  510,  249,  511,  249,  512,  254,  513,  254,
      206,  206,  206,  206,  206,  258,  514,  296,  258,  259,

      515,  259,  259,  259,  259,  516,  108,  108,  108,  108,
      108,  164,  164,  164,  448,  448,  448,   99,   99,   99,
      149,  149,  149,  149,  149,  517,  518,  206,  206,  206,
      519,  520,  259,  259,  259,  259,  259,  516,  108,  108,
      108,  164,  164,  164,  164,  164,  448,  448,  448,   99,
       99,   99,   99,   99,  149,  149,  149,  206,  206,  206,
      206,  206,  259,  259,  259,  108,  108,  108,  108,  108,
      164,  164,  164,  448,   99,   99,   99,  149,  149,  149,
      149,  149,  206,  206,  206,  259,  259,  259,  259,  259,
      108,  108,  108,  164,  164,  164,  164,  164,   99,   99,

       99,   99,  149,  149,  149,  206,  206,  206,  206,  206,
      259,  259,  259,  108,  108,  108,  108,  164,  164,  164,
      149,  149,  149,  149,  206,  206,  206,  259,  259,  259,
      259,  259,  164,  164,  164,  164,  206,  206,  206,  206,
      259,  259,  259,  259,  259,  259,  259,    0,  448,  448,
      448,  448,  448,  448,  448,  448,  448,  448,  448,  448,
      448,  448,  448,  448,  448,  448,  448,  448,  448,  448,
      448,  448,  448,  448,  448,  448,  448,  448,  448,  448,
      448,  448,  448,  448,  448,  448,  448,  448,  448,  448,
      448,  448,  448,  448,  448,  448,  448,  448,  448,  448,

      448,  448,  448,  448,  448,  448,  448,  448,  448,  448,
      448,  448,  448,  448,  448,  448,  448,  448,  448,  448
    } ;

static yyconst flex_int16_t yy_nxt[3152] =
    {   0,
      448,   37,   38,   37,   38,   36,   37,   38,   39,   36,
       40,   39,   41,   39,   39,   39,   39,   39,   39,   39,
       42,   42,   43,   42,   42,   42,   42,   42,   36,   39,
       36,   39,   36,   44,   42,   45,   45,   45,   45,   45,
       45,   45,   45,   42,   45,   45,   45,   45,   45,   45,
       42,   37,   38,   37,   38,   37,   38,   52,   53,   52,
       53,   37,   38,   37,   38,   48,   37,   38,  229,   47,
      374,   47,   37,   38,   55,   56,  230,   49,   55,   56,
       46,   46,   46,   46,   46,   46,   46,   46,   50,   46,
       46,   46,   46,   46,   46,   37,   38,  374,   57,   48,

       58,  374,   57,  349,   58,   37,   38,   72,   73,   37,
       38,   49,   37,   38,   37,   38,   37,   38,   85,   85,
      348,   74,   50,   59,   60,   61,   59,   59,   59,   59,
       59,   59,   59,   59,   59,   59,   59,   59,   62,   62,
       63,   59,   59,   59,   59,   59,   62,   59,   64,   65,
       66,   59,   59,   62,   62,   62,   62,   62,   62,   62,
       62,   62,   62,   62,   62,   62,   62,   62,   59,   68,
       69,   68,   69,   72,   73,   76,   77,   76,   77,   37,
       38,  347,   80,   37,   38,  172,   80,   74,   82,   83,
       82,   83,  173,   70,  317,   70,   85,   85,  316,   78,

      315,   78,   85,   85,  274,   36,   85,   85,  273,   36,
      126,  126,   84,  272,   84,   86,  249,   87,   86,   88,
       86,   86,   86,   86,   86,   86,   86,   89,   89,   90,
       89,   89,   89,   89,   89,  127,   86,  249,   86,  231,
       91,   89,   89,   89,   89,   89,   89,   89,   89,   89,
       89,   89,   89,   89,   89,   89,   89,   89,   92,  129,
      129,   92,   93,   92,   92,   92,   92,   92,   92,   92,
       94,   94,   94,   94,   94,   94,   94,   94,   94,   92,
      228,   92,  125,   94,   94,   94,   94,   94,   94,   94,
       94,   94,   94,   94,   94,   94,   94,   94,   94,   94,

       94,   96,  198,   87,   96,   97,   96,   96,   96,   96,
       96,   96,   96,   98,   98,   99,   98,   98,   98,   98,
       98,   98,   96,  198,   96,  133,   91,   98,   98,   98,
       98,   98,   98,   98,   98,   98,   98,   98,   98,   98,
       98,   98,   98,   98,  100,  171,   87,  100,  101,  100,
      100,  100,  100,  100,  100,  100,  102,  102,  102,  102,
      102,  102,  102,  102,  102,  100,  169,  100,  122,  102,
      102,  102,  102,  102,  102,  102,  102,  102,  102,  102,
      102,  102,  102,  102,  102,  102,  102,   86,  107,   87,
       86,   88,   86,   86,   86,   86,   86,  103,   86,  104,

      104,   90,  104,  104,  104,  104,  104,  105,   86,  139,
       86,  139,   91,   89,  104,  104,  104,  104,  104,  104,
      104,  104,   89,  104,  104,  104,  104,  104,  104,   89,
      109,   85,   85,  109,  110,  109,  109,  109,  109,  109,
      109,  109,  111,  111,  111,  111,  111,  111,  111,  111,
      111,  109,  134,  109,  133,  111,  111,  111,  111,  111,
      111,  111,  111,  111,  111,  111,  111,  111,  111,  111,
      111,  111,  111,  112,  130,  113,  112,  114,  112,  112,
      112,  112,  112,  112,  112,  115,  115,  116,  115,  115,
      115,  115,  115,  115,  112,  124,  112,  124,  117,  115,

      115,  115,  115,  115,  115,  115,  115,  115,  115,  115,
      115,  115,  115,  115,  115,  115,  118,  122,  113,  118,
      119,  118,  118,  118,  118,  118,  118,  118,  120,  120,
      120,  120,  120,  120,  120,  120,  120,  118,  108,  118,
      107,  120,  120,  120,  120,  120,  120,  120,  120,  120,
      120,  120,  120,  120,  120,  120,  120,  120,  120,  123,
      123,  123,  123,  126,  126,   85,   85,   85,   85,   85,
       85,   85,   85,   85,   85,   85,   85,   85,   85,   85,
       85,  129,  129,  129,  129,  122,  448,  122,  127,  135,
      448,   87,  135,  136,  135,  135,  135,  135,  135,  135,

      135,  137,  137,   90,  137,  137,  137,  137,  137,  137,
      135,  448,  135,  448,   91,  137,  137,  137,  137,  137,
      137,  137,  137,  137,  137,  137,  137,  137,  137,  137,
      137,  137,  141,  448,   87,  141,  142,  141,  141,  141,
      141,  141,  141,  141,  143,  143,  144,  145,  146,  147,
      145,  145,  148,  141,  448,  141,  448,   91,  149,  143,
      143,  143,  143,  143,  143,  143,  143,  143,  143,  143,
      143,  143,  143,  143,  143,  151,  448,  152,  151,  153,
      151,  151,  151,  151,  151,  151,  151,  154,  154,  155,
      154,  154,  154,  154,  154,  154,  151,  448,  151,  448,

      156,  154,  154,  154,  154,  154,  154,  154,  154,  154,
      154,  154,  154,  154,  154,  154,  154,  154,  157,  448,
      448,  157,  158,  157,  157,  157,  157,  157,  157,  157,
      159,  159,  448,  160,  161,  162,  160,  160,  163,  157,
      448,  157,  123,  123,  164,  159,  159,  159,  159,  159,
      159,  159,  159,  159,  159,  159,  159,  159,  159,  159,
      159,  126,  126,  143,  143,  143,  143,  143,  122,  143,
      143,  143,  143,  143,  182,  448,  183,  183,  183,  183,
      183,  159,  159,  159,  159,  159,  127,  175,  448,   87,
      175,  176,  175,  175,  175,  175,  175,  175,  175,  177,

      177,  139,  177,  177,  177,  177,  177,  177,  175,  448,
      175,  448,   91,  177,  177,  177,  177,  177,  177,  177,
      177,  177,  177,  177,  177,  177,  177,  177,  177,  177,
      179,  448,   87,  179,  180,  179,  179,  179,  179,  179,
      179,  179,  181,  181,  144,  181,  181,  181,  181,  181,
      181,  179,  448,  179,  448,   91,  181,  181,  181,  181,
      181,  181,  181,  181,  181,  181,  181,  181,  181,  181,
      181,  181,  181,  182,  448,  184,  184,  184,  184,  184,
      182,  448,  185,  185,  185,  186,  183,  187,  448,   87,
      187,  188,  187,  187,  187,  187,  187,  187,  187,  189,

      189,  144,  190,  190,  190,  190,  190,  189,  187,  448,
      187,  448,   91,  149,  189,  189,  189,  189,  189,  189,
      189,  189,  189,  189,  189,  189,  189,  189,  189,  189,
      191,  448,   87,  191,  192,  191,  191,  191,  191,  191,
      191,  191,  193,  193,  144,  194,  195,  196,  194,  194,
      197,  191,  448,  191,  448,   91,  448,  193,  193,  193,
      193,  193,  193,  193,  193,  193,  193,  193,  193,  193,
      193,  193,  193,  199,  448,  448,  199,  200,  199,  199,
      199,  199,  199,  199,  199,  201,  201,  201,  201,  201,
      201,  201,  201,  201,  199,  448,  199,  448,  201,  201,

      201,  201,  201,  201,  201,  201,  201,  201,  201,  201,
      201,  201,  201,  201,  201,  201,  203,  448,  152,  203,
      204,  203,  203,  203,  203,  203,  203,  203,  205,  205,
      206,  205,  205,  205,  205,  205,  205,  203,  448,  203,
      448,  156,  205,  205,  205,  205,  205,  205,  205,  205,
      205,  205,  205,  205,  205,  205,  205,  205,  205,  207,
      448,  152,  207,  208,  207,  207,  207,  207,  207,  207,
      207,  209,  209,  209,  209,  209,  209,  209,  209,  209,
      207,  448,  207,  448,  209,  209,  209,  209,  209,  209,
      209,  209,  209,  209,  209,  209,  209,  209,  209,  209,

      209,  209,  159,  159,  159,  159,  159,  211,  448,  212,
      212,  212,  212,  212,  211,  448,  213,  213,  213,  213,
      213,  211,  448,  214,  214,  214,  215,  212,  216,  448,
       87,  216,  217,  216,  216,  216,  216,  216,  216,  216,
      218,  218,  144,  219,  219,  219,  219,  219,  218,  216,
      448,  216,  448,   91,  164,  218,  218,  218,  218,  218,
      218,  218,  218,  218,  218,  218,  218,  218,  218,  218,
      218,  220,  448,   87,  220,  221,  220,  220,  220,  220,
      220,  220,  220,  222,  222,  144,  223,  224,  225,  223,
      223,  226,  220,  448,  220,  448,   91,  448,  222,  222,

      222,  222,  222,  222,  222,  222,  222,  222,  222,  222,
      222,  222,  222,  222,  234,  235,  236,  234,  234,  182,
      448,  143,  143,  143,  143,  143,  182,  448,  183,  183,
      183,  183,  183,  182,  448,  183,  183,  183,  183,  183,
      182,  448,  183,  183,  183,  183,  143,  448,  193,  193,
      193,  193,  193,  193,  193,  193,  193,  193,  448,  448,
      189,  189,  189,  189,  189,  448,  448,  448,  448,  239,
      448,  240,  240,  240,  240,  240,  239,  448,  241,  241,
      241,  241,  241,  239,  448,  242,  242,  242,  243,  240,
      245,  448,  152,  245,  246,  245,  245,  245,  245,  245,

      245,  245,  247,  247,  198,  247,  247,  247,  247,  247,
      247,  245,  448,  245,  448,  156,  247,  247,  247,  247,
      247,  247,  247,  247,  247,  247,  247,  247,  247,  247,
      247,  247,  247,  251,  448,  152,  251,  252,  251,  251,
      251,  251,  251,  251,  251,  253,  253,  254,  255,  256,
      257,  255,  255,  258,  251,  448,  251,  448,  156,  259,
      253,  253,  253,  253,  253,  253,  253,  253,  253,  253,
      253,  253,  253,  253,  253,  253,  261,  262,  263,  261,
      261,  211,  448,  159,  159,  159,  159,  159,  211,  448,
      212,  212,  212,  212,  212,  211,  448,  212,  212,  212,

      212,  212,  211,  448,  212,  212,  212,  212,  159,  218,
      218,  218,  218,  218,  218,  218,  218,  218,  218,  222,
      222,  222,  222,  222,  222,  222,  222,  222,  222,  266,
      448,  267,  267,  267,  267,  267,  266,  448,  268,  268,
      268,  268,  268,  266,  448,  269,  269,  269,  270,  267,
      271,  271,  271,  271,  271,  275,  448,  276,  276,  276,
      276,  276,  275,  448,  277,  277,  277,  277,  277,  275,
      448,  278,  278,  278,  279,  276,  280,  281,  282,  280,
      280,  239,  448,  193,  193,  193,  193,  193,  239,  448,
      240,  240,  240,  240,  240,  239,  448,  240,  240,  240,

      240,  240,  239,  448,  240,  240,  240,  240,  193,  284,
      448,  152,  284,  285,  284,  284,  284,  284,  284,  284,
      284,  286,  286,  249,  286,  286,  286,  286,  286,  286,
      284,  448,  284,  448,  156,  286,  286,  286,  286,  286,
      286,  286,  286,  286,  286,  286,  286,  286,  286,  286,
      286,  286,  253,  253,  253,  253,  253,  253,  253,  253,
      253,  253,  288,  448,  152,  288,  289,  288,  288,  288,
      288,  288,  288,  288,  290,  290,  254,  290,  290,  290,
      290,  290,  290,  288,  448,  288,  448,  156,  290,  290,
      290,  290,  290,  290,  290,  290,  290,  290,  290,  290,

      290,  290,  290,  290,  290,  291,  448,  292,  292,  292,
      292,  292,  291,  448,  293,  293,  293,  293,  293,  291,
      448,  294,  294,  294,  295,  292,  296,  448,  152,  296,
      297,  296,  296,  296,  296,  296,  296,  296,  298,  298,
      254,  299,  299,  299,  299,  299,  298,  296,  448,  296,
      448,  156,  259,  298,  298,  298,  298,  298,  298,  298,
      298,  298,  298,  298,  298,  298,  298,  298,  298,  300,
      448,  152,  300,  301,  300,  300,  300,  300,  300,  300,
      300,  302,  302,  254,  303,  304,  305,  303,  303,  306,
      300,  448,  300,  448,  156,  448,  302,  302,  302,  302,

      302,  302,  302,  302,  302,  302,  302,  302,  302,  302,
      302,  302,  307,  448,  308,  308,  308,  308,  308,  307,
      448,  309,  309,  309,  309,  309,  307,  448,  310,  310,
      310,  311,  308,  312,  313,  314,  312,  312,  266,  448,
      222,  222,  222,  222,  222,  266,  448,  267,  267,  267,
      267,  267,  266,  448,  267,  267,  267,  267,  267,  266,
      448,  267,  267,  267,  267,  222,  271,  271,  271,  271,
      271,  318,  319,  320,  318,  318,  275,  448,  143,  143,
      143,  143,  143,  275,  448,  276,  276,  276,  276,  276,
      275,  448,  276,  276,  276,  276,  276,  275,  448,  276,

      276,  276,  276,  143,  321,  448,  322,  322,  322,  322,
      322,  321,  448,  323,  323,  323,  323,  323,  321,  448,
      324,  324,  324,  325,  322,  328,  329,  330,  328,  328,
      291,  448,  253,  253,  253,  253,  253,  291,  448,  292,
      292,  292,  292,  292,  291,  448,  292,  292,  292,  292,
      292,  291,  448,  292,  292,  292,  292,  253,  448,  302,
      302,  302,  302,  302,  302,  302,  302,  302,  302,  448,
      448,  298,  298,  298,  298,  298,  448,  448,  448,  448,
      333,  448,  334,  334,  334,  334,  334,  333,  448,  335,
      335,  335,  335,  335,  333,  152,  336,  336,  336,  337,

      334,  339,  340,  341,  339,  339,  307,  254,  159,  159,
      159,  159,  159,  448,  448,  448,  448,  307,  156,  308,
      308,  308,  308,  308,  307,  448,  308,  308,  308,  308,
      308,  307,  448,  308,  308,  308,  308,  159,  342,  448,
      343,  343,  343,  343,  343,  342,  448,  344,  344,  344,
      344,  344,  342,  448,  345,  345,  345,  346,  343,  350,
      448,  351,  351,  351,  351,  351,  350,  448,  352,  352,
      352,  352,  352,  350,  448,  353,  353,  353,  354,  351,
      355,  356,  357,  355,  355,  321,  448,  193,  193,  193,
      193,  193,  321,  448,  322,  322,  322,  322,  322,  321,

      448,  322,  322,  322,  322,  322,  321,  448,  322,  322,
      322,  322,  193,  358,  448,  359,  359,  359,  359,  359,
      358,  448,  360,  360,  360,  360,  360,  358,  448,  361,
      361,  361,  362,  359,  363,  364,  365,  363,  363,  333,
      448,  302,  302,  302,  302,  302,  333,  448,  334,  334,
      334,  334,  334,  333,  448,  334,  334,  334,  334,  334,
      333,  152,  334,  334,  334,  334,  302,  371,  372,  373,
      371,  371,  366,  254,  367,  367,  367,  367,  367,  448,
      448,  448,  448,  366,  156,  368,  368,  368,  368,  368,
      366,  448,  369,  369,  369,  370,  367,  342,  448,  222,

      222,  222,  222,  222,  342,  448,  343,  343,  343,  343,
      343,  342,  448,  343,  343,  343,  343,  343,  342,  448,
      343,  343,  343,  343,  222,  375,  376,  377,  375,  375,
      350,  448,  143,  143,  143,  143,  143,  350,  448,  351,
      351,  351,  351,  351,  350,  448,  351,  351,  351,  351,
      351,  350,  448,  351,  351,  351,  351,  143,  378,  448,
      379,  379,  379,  379,  379,  378,  448,  380,  380,  380,
      380,  380,  378,  448,  381,  381,  381,  382,  379,  383,
      384,  385,  383,  383,  358,  448,  253,  253,  253,  253,
      253,  358,  448,  359,  359,  359,  359,  359,  358,  448,

      359,  359,  359,  359,  359,  358,  448,  359,  359,  359,
      359,  253,  386,  448,  387,  387,  387,  387,  387,  386,
      448,  388,  388,  388,  388,  388,  386,  448,  389,  389,
      389,  390,  387,  391,  392,  393,  391,  391,  366,  448,
      159,  159,  159,  159,  159,  366,  448,  367,  367,  367,
      367,  367,  366,  448,  367,  367,  367,  367,  367,  366,
      448,  367,  367,  367,  367,  159,  394,  448,  395,  395,
      395,  395,  395,  394,  448,  396,  396,  396,  396,  396,
      394,  448,  397,  397,  397,  398,  395,  399,  399,  399,
      399,  399,  400,  400,  400,  400,  400,  401,  401,  401,

      402,  399,  403,  404,  405,  403,  403,  378,  448,  193,
      193,  193,  193,  193,  378,  448,  379,  379,  379,  379,
      379,  378,  448,  379,  379,  379,  379,  379,  378,  448,
      379,  379,  379,  379,  193,  406,  448,  407,  407,  407,
      407,  407,  406,  448,  408,  408,  408,  408,  408,  406,
      448,  409,  409,  409,  410,  407,  411,  412,  413,  411,
      411,  386,  448,  302,  302,  302,  302,  302,  386,  448,
      387,  387,  387,  387,  387,  386,  448,  387,  387,  387,
      387,  387,  386,  448,  387,  387,  387,  387,  302,  414,
      414,  414,  414,  414,  415,  415,  415,  415,  415,  416,

      416,  416,  417,  414,  418,  419,  420,  418,  418,  394,
      448,  222,  222,  222,  222,  222,  394,  448,  395,  395,
      395,  395,  395,  394,  448,  395,  395,  395,  395,  395,
      394,  448,  395,  395,  395,  395,  222,  143,  143,  143,
      143,  143,  399,  399,  399,  399,  399,  399,  399,  399,
      399,  399,  399,  399,  399,  399,  143,  421,  421,  421,
      421,  421,  422,  422,  422,  422,  422,  423,  423,  423,
      424,  421,  425,  426,  427,  425,  425,  406,  448,  253,
      253,  253,  253,  253,  406,  448,  407,  407,  407,  407,
      407,  406,  448,  407,  407,  407,  407,  407,  406,  448,

      407,  407,  407,  407,  253,  428,  448,  429,  429,  429,
      429,  429,  428,  448,  430,  430,  430,  430,  430,  428,
      448,  431,  431,  431,  432,  429,  159,  159,  159,  159,
      159,  414,  414,  414,  414,  414,  414,  414,  414,  414,
      414,  414,  414,  414,  414,  159,  433,  433,  433,  433,
      433,  434,  434,  434,  434,  434,  435,  435,  435,  436,
      433,  193,  193,  193,  193,  193,  421,  421,  421,  421,
      421,  421,  421,  421,  421,  421,  421,  421,  421,  421,
      193,  437,  437,  437,  437,  437,  438,  438,  438,  438,
      438,  439,  439,  439,  440,  437,  441,  442,  443,  441,

      441,  428,  448,  302,  302,  302,  302,  302,  428,  448,
      429,  429,  429,  429,  429,  428,  448,  429,  429,  429,
      429,  429,  428,  448,  429,  429,  429,  429,  302,  222,
      222,  222,  222,  222,  433,  433,  433,  433,  433,  433,
      433,  433,  433,  433,  433,  433,  433,  433,  222,  253,
      253,  253,  253,  253,  437,  437,  437,  437,  437,  437,
      437,  437,  437,  437,  437,  437,  437,  437,  253,  444,
      444,  444,  444,  444,  445,  445,  445,  445,  445,  446,
      446,  446,  447,  444,  302,  302,  302,  302,  302,  444,
      444,  444,  444,  444,  444,  444,  444,  444,  444,  444,

      444,  444,  444,  302,   36,   36,   36,   36,   36,   36,
       36,   36,   36,   36,   36,   51,   51,   51,   51,   51,
       51,   51,   51,   51,   51,   51,   54,   54,   54,   54,
       54,   54,   54,   54,   54,   54,   54,   67,   67,   67,
       67,   67,   67,   67,   67,   67,   67,   67,   71,   71,
       71,   71,   71,   71,   71,   71,   71,   71,   71,   75,
       75,   75,   75,   75,   75,   75,   75,   75,   75,   75,
       79,   79,   79,   79,   79,   79,   79,   79,   79,   79,
       79,   81,   81,   81,   81,   81,   81,   81,   81,   81,
       81,   81,   95,  448,  448,   95,  106,  106,  448,  106,

      448,  448,  106,  121,  121,  121,  121,  121,  121,  121,
      121,  448,  121,  121,  125,  448,  448,  125,  125,  448,
      448,  448,  125,  128,  448,  128,  448,  448,  128,  131,
      448,  131,  131,  131,  131,  131,  131,  131,  448,  131,
      132,  132,  132,  132,  132,  132,  132,  132,  132,  132,
      132,  138,  448,  448,  138,   89,  448,  448,   89,  140,
      448,  448,  140,  150,  448,  448,  150,  165,  448,  448,
      165,  166,  448,  448,  166,  167,  448,  448,  167,  168,
      168,  168,  168,  168,  168,  168,  168,  168,  448,  168,
      170,  448,  170,  448,  448,  170,  174,  448,  448,  174,

       94,  448,  448,   94,   98,  448,  448,   98,  178,  448,
      448,  178,  102,  448,  448,  102,  202,  448,  448,  202,
      210,  448,  448,  210,  111,  448,  448,  111,  115,  448,
      448,  115,  120,  448,  448,  120,  227,  227,  227,  227,
      227,  227,  227,  227,  227,  448,  227,  125,  125,  125,
      125,  125,  125,  125,  125,  125,  448,  125,  137,  448,
      448,  137,  232,  448,  448,  232,  143,  448,  448,  143,
      233,  448,  448,  233,  237,  448,  448,  237,  238,  448,
      448,  238,  244,  448,  448,  244,  244,  248,  448,  448,
      248,  154,  448,  448,  154,  250,  448,  448,  250,  260,

      448,  448,  260,  159,  448,  448,  159,  264,  448,  448,
      264,  265,  448,  448,  265,  177,  448,  448,  177,  181,
      448,  448,  181,  189,  448,  448,  189,  193,  448,  448,
      193,  283,  448,  448,  283,  201,  448,  448,  201,  205,
      448,  448,  205,  287,  448,  448,  287,  209,  448,  448,
      209,  218,  448,  448,  218,  222,  448,  448,  222,  247,
      448,  448,  247,  326,  448,  448,  326,  253,  448,  448,
      253,  327,  448,  448,  327,  331,  448,  448,  331,  332,
      448,  448,  332,  338,  448,  448,  338,  338,  286,  448,
      448,  286,  290,  448,  448,  290,  298,  448,  448,  298,

      302,  448,  448,  302,   35,  448,  448,  448,  448,  448,
      448,  448,  448,  448,  448,  448,  448,  448,  448,  448,
      448,  448,  448,  448,  448,  448,  448,  448,  448,  448,
      448,  448,  448,  448,  448,  448,  448,  448,  448,  448,
      448,  448,  448,  448,  448,  448,  448,  448,  448,  448,
      448
    } ;

static yyconst flex_int16_t yy_chk[3152] =
    {   0,
        0,    1,    1,    2,    2,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    5,    5,    7,    7,    8,    8,   11,   11,   12,
       12,    9,    9,   13,   13,    9,   14,   14,  172,    7,
      349,    8,   21,   21,   15,   15,  172,    9,   16,   16,
        5,    5,    5,    5,    5,    5,    5,    5,    9,    5,
        5,    5,    5,    5,    5,   10,   10,  348,   15,   10,

       15,  347,   16,  317,   16,   22,   22,   23,   23,   25,
       25,   10,   26,   26,   27,   27,   28,   28,   37,   37,
      316,   23,   10,   17,   17,   17,   17,   17,   17,   17,
       17,   17,   17,   17,   17,   17,   17,   17,   17,   17,
       17,   17,   17,   17,   17,   17,   17,   17,   17,   17,
       17,   17,   17,   17,   17,   17,   17,   17,   17,   17,
       17,   17,   17,   17,   17,   17,   17,   17,   17,   19,
       19,   20,   20,   24,   24,   29,   29,   30,   30,   31,
       31,  315,   31,   32,   32,  134,   32,   24,   33,   33,
       34,   34,  134,   19,  274,   20,   38,   38,  273,   29,

      272,   30,   52,   52,  231,   31,   53,   53,  230,   32,
       60,   60,   33,  229,   34,   39,  205,   39,   39,   39,
       39,   39,   39,   39,   39,   39,   39,   39,   39,   39,
       39,   39,   39,   39,   39,   60,   39,  203,   39,  173,
       39,   39,   39,   39,   39,   39,   39,   39,   39,   39,
       39,   39,   39,   39,   39,   39,   39,   39,   40,   65,
       65,   40,   40,   40,   40,   40,   40,   40,   40,   40,
       40,   40,   40,   40,   40,   40,   40,   40,   40,   40,
      169,   40,  168,   40,   40,   40,   40,   40,   40,   40,
       40,   40,   40,   40,   40,   40,   40,   40,   40,   40,

       40,   43,  154,   43,   43,   43,   43,   43,   43,   43,
       43,   43,   43,   43,   43,   43,   43,   43,   43,   43,
       43,   43,   43,  151,   43,  132,   43,   43,   43,   43,
       43,   43,   43,   43,   43,   43,   43,   43,   43,   43,
       43,   43,   43,   43,   44,  130,   44,   44,   44,   44,
       44,   44,   44,   44,   44,   44,   44,   44,   44,   44,
       44,   44,   44,   44,   44,   44,  124,   44,  121,   44,
       44,   44,   44,   44,   44,   44,   44,   44,   44,   44,
       44,   44,   44,   44,   44,   44,   44,   45,  106,   45,
       45,   45,   45,   45,   45,   45,   45,   45,   45,   45,

       45,   45,   45,   45,   45,   45,   45,   45,   45,   98,
       45,   96,   45,   45,   45,   45,   45,   45,   45,   45,
       45,   45,   45,   45,   45,   45,   45,   45,   45,   45,
       48,   68,   68,   48,   48,   48,   48,   48,   48,   48,
       48,   48,   48,   48,   48,   48,   48,   48,   48,   48,
       48,   48,   84,   48,   80,   48,   48,   48,   48,   48,
       48,   48,   48,   48,   48,   48,   48,   48,   48,   48,
       48,   48,   48,   49,   74,   49,   49,   49,   49,   49,
       49,   49,   49,   49,   49,   49,   49,   49,   49,   49,
       49,   49,   49,   49,   49,   64,   49,   57,   49,   49,

       49,   49,   49,   49,   49,   49,   49,   49,   49,   49,
       49,   49,   49,   49,   49,   49,   50,   54,   50,   50,
       50,   50,   50,   50,   50,   50,   50,   50,   50,   50,
       50,   50,   50,   50,   50,   50,   50,   50,   47,   50,
       46,   50,   50,   50,   50,   50,   50,   50,   50,   50,
       50,   50,   50,   50,   50,   50,   50,   50,   50,   55,
       55,   56,   56,   61,   61,   69,   69,   72,   72,   73,
       73,   76,   76,   77,   77,   82,   82,   83,   83,   85,
       85,  127,  127,  129,  129,   55,   35,   56,   61,   90,
        0,   90,   90,   90,   90,   90,   90,   90,   90,   90,

       90,   90,   90,   90,   90,   90,   90,   90,   90,   90,
       90,    0,   90,    0,   90,   90,   90,   90,   90,   90,
       90,   90,   90,   90,   90,   90,   90,   90,   90,   90,
       90,   90,   99,    0,   99,   99,   99,   99,   99,   99,
       99,   99,   99,   99,   99,   99,   99,   99,   99,   99,
       99,   99,   99,   99,    0,   99,    0,   99,   99,   99,
       99,   99,   99,   99,   99,   99,   99,   99,   99,   99,
       99,   99,   99,   99,   99,  105,    0,  105,  105,  105,
      105,  105,  105,  105,  105,  105,  105,  105,  105,  105,
      105,  105,  105,  105,  105,  105,  105,    0,  105,    0,

      105,  105,  105,  105,  105,  105,  105,  105,  105,  105,
      105,  105,  105,  105,  105,  105,  105,  105,  108,    0,
        0,  108,  108,  108,  108,  108,  108,  108,  108,  108,
      108,  108,    0,  108,  108,  108,  108,  108,  108,  108,
        0,  108,  123,  123,  108,  108,  108,  108,  108,  108,
      108,  108,  108,  108,  108,  108,  108,  108,  108,  108,
      108,  126,  126,  141,  141,  141,  141,  141,  123,  143,
      143,  143,  143,  143,  145,    0,  145,  145,  145,  145,
      145,  157,  157,  157,  157,  157,  126,  139,    0,  139,
      139,  139,  139,  139,  139,  139,  139,  139,  139,  139,

      139,  139,  139,  139,  139,  139,  139,  139,  139,    0,
      139,    0,  139,  139,  139,  139,  139,  139,  139,  139,
      139,  139,  139,  139,  139,  139,  139,  139,  139,  139,
      144,    0,  144,  144,  144,  144,  144,  144,  144,  144,
      144,  144,  144,  144,  144,  144,  144,  144,  144,  144,
      144,  144,    0,  144,    0,  144,  144,  144,  144,  144,
      144,  144,  144,  144,  144,  144,  144,  144,  144,  144,
      144,  144,  144,  146,    0,  146,  146,  146,  146,  146,
      147,    0,  147,  147,  147,  147,  147,  148,    0,  148,
      148,  148,  148,  148,  148,  148,  148,  148,  148,  148,

      148,  148,  148,  148,  148,  148,  148,  148,  148,    0,
      148,    0,  148,  148,  148,  148,  148,  148,  148,  148,
      148,  148,  148,  148,  148,  148,  148,  148,  148,  148,
      149,    0,  149,  149,  149,  149,  149,  149,  149,  149,
      149,  149,  149,  149,  149,  149,  149,  149,  149,  149,
      149,  149,    0,  149,    0,  149,    0,  149,  149,  149,
      149,  149,  149,  149,  149,  149,  149,  149,  149,  149,
      149,  149,  149,  152,    0,    0,  152,  152,  152,  152,
      152,  152,  152,  152,  152,  152,  152,  152,  152,  152,
      152,  152,  152,  152,  152,    0,  152,    0,  152,  152,

      152,  152,  152,  152,  152,  152,  152,  152,  152,  152,
      152,  152,  152,  152,  152,  152,  155,    0,  155,  155,
      155,  155,  155,  155,  155,  155,  155,  155,  155,  155,
      155,  155,  155,  155,  155,  155,  155,  155,    0,  155,
        0,  155,  155,  155,  155,  155,  155,  155,  155,  155,
      155,  155,  155,  155,  155,  155,  155,  155,  155,  156,
        0,  156,  156,  156,  156,  156,  156,  156,  156,  156,
      156,  156,  156,  156,  156,  156,  156,  156,  156,  156,
      156,    0,  156,    0,  156,  156,  156,  156,  156,  156,
      156,  156,  156,  156,  156,  156,  156,  156,  156,  156,

      156,  156,  159,  159,  159,  159,  159,  160,    0,  160,
      160,  160,  160,  160,  161,    0,  161,  161,  161,  161,
      161,  162,    0,  162,  162,  162,  162,  162,  163,    0,
      197,  163,  163,  163,  163,  163,  163,  163,  163,  163,
      163,  163,  197,  163,  163,  163,  163,  163,  163,  163,
        0,  163,    0,  197,  163,  163,  163,  163,  163,  163,
      163,  163,  163,  163,  163,  163,  163,  163,  163,  163,
      163,  164,    0,  244,  164,  164,  164,  164,  164,  164,
      164,  164,  164,  164,  164,  244,  164,  164,  164,  164,
      164,  164,  164,    0,  164,    0,  244,    0,  164,  164,

      164,  164,  164,  164,  164,  164,  164,  164,  164,  164,
      164,  164,  164,  164,  182,  182,  182,  182,  182,  183,
        0,  183,  183,  183,  183,  183,  184,    0,  184,  184,
      184,  184,  184,  185,    0,  185,  185,  185,  185,  185,
      186,    0,  186,  186,  186,  186,  186,  187,  191,  191,
      191,  191,  191,  193,  193,  193,  193,  193,    0,  187,
      187,  187,  187,  187,  187,    0,    0,    0,    0,  194,
      187,  194,  194,  194,  194,  194,  195,    0,  195,  195,
      195,  195,  195,  196,    0,  196,  196,  196,  196,  196,
      198,    0,  198,  198,  198,  198,  198,  198,  198,  198,

      198,  198,  198,  198,  198,  198,  198,  198,  198,  198,
      198,  198,    0,  198,    0,  198,  198,  198,  198,  198,
      198,  198,  198,  198,  198,  198,  198,  198,  198,  198,
      198,  198,  198,  206,    0,  206,  206,  206,  206,  206,
      206,  206,  206,  206,  206,  206,  206,  206,  206,  206,
      206,  206,  206,  206,  206,    0,  206,    0,  206,  206,
      206,  206,  206,  206,  206,  206,  206,  206,  206,  206,
      206,  206,  206,  206,  206,  206,  211,  211,  211,  211,
      211,  212,    0,  212,  212,  212,  212,  212,  213,    0,
      213,  213,  213,  213,  213,  214,    0,  214,  214,  214,

      214,  214,  215,    0,  215,  215,  215,  215,  215,  216,
      216,  216,  216,  216,  218,  218,  218,  218,  218,  220,
      220,  220,  220,  220,  222,  222,  222,  222,  222,  223,
        0,  223,  223,  223,  223,  223,  224,    0,  224,  224,
      224,  224,  224,  225,    0,  225,  225,  225,  225,  225,
      226,  226,  226,  226,  226,  234,    0,  234,  234,  234,
      234,  234,  235,    0,  235,  235,  235,  235,  235,  236,
        0,  236,  236,  236,  236,  236,  239,  239,  239,  239,
      239,  240,    0,  240,  240,  240,  240,  240,  241,    0,
      241,  241,  241,  241,  241,  242,    0,  242,  242,  242,

      242,  242,  243,    0,  243,  243,  243,  243,  243,  249,
        0,  249,  249,  249,  249,  249,  249,  249,  249,  249,
      249,  249,  249,  249,  249,  249,  249,  249,  249,  249,
      249,    0,  249,    0,  249,  249,  249,  249,  249,  249,
      249,  249,  249,  249,  249,  249,  249,  249,  249,  249,
      249,  249,  251,  251,  251,  251,  251,  253,  253,  253,
      253,  253,  254,    0,  254,  254,  254,  254,  254,  254,
      254,  254,  254,  254,  254,  254,  254,  254,  254,  254,
      254,  254,  254,  254,    0,  254,    0,  254,  254,  254,
      254,  254,  254,  254,  254,  254,  254,  254,  254,  254,

      254,  254,  254,  254,  254,  255,    0,  255,  255,  255,
      255,  255,  256,    0,  256,  256,  256,  256,  256,  257,
        0,  257,  257,  257,  257,  257,  258,    0,  258,  258,
      258,  258,  258,  258,  258,  258,  258,  258,  258,  258,
      258,  258,  258,  258,  258,  258,  258,  258,    0,  258,
        0,  258,  258,  258,  258,  258,  258,  258,  258,  258,
      258,  258,  258,  258,  258,  258,  258,  258,  258,  259,
        0,  259,  259,  259,  259,  259,  259,  259,  259,  259,
      259,  259,  259,  259,  259,  259,  259,  259,  259,  259,
      259,    0,  259,    0,  259,    0,  259,  259,  259,  259,

      259,  259,  259,  259,  259,  259,  259,  259,  259,  259,
      259,  259,  261,    0,  261,  261,  261,  261,  261,  262,
        0,  262,  262,  262,  262,  262,  263,    0,  263,  263,
      263,  263,  263,  266,  266,  266,  266,  266,  267,    0,
      267,  267,  267,  267,  267,  268,    0,  268,  268,  268,
      268,  268,  269,    0,  269,  269,  269,  269,  269,  270,
        0,  270,  270,  270,  270,  270,  271,  271,  271,  271,
      271,  275,  275,  275,  275,  275,  276,    0,  276,  276,
      276,  276,  276,  277,    0,  277,  277,  277,  277,  277,
      278,    0,  278,  278,  278,  278,  278,  279,    0,  279,

      279,  279,  279,  279,  280,    0,  280,  280,  280,  280,
      280,  281,    0,  281,  281,  281,  281,  281,  282,    0,
      282,  282,  282,  282,  282,  291,  291,  291,  291,  291,
      292,    0,  292,  292,  292,  292,  292,  293,    0,  293,
      293,  293,  293,  293,  294,    0,  294,  294,  294,  294,
      294,  295,    0,  295,  295,  295,  295,  295,  296,  300,
      300,  300,  300,  300,  302,  302,  302,  302,  302,    0,
      296,  296,  296,  296,  296,  296,    0,    0,    0,    0,
      303,  296,  303,  303,  303,  303,  303,  304,    0,  304,
      304,  304,  304,  304,  305,  306,  305,  305,  305,  305,

      305,  307,  307,  307,  307,  307,  308,  306,  308,  308,
      308,  308,  308,    0,    0,    0,    0,  309,  306,  309,
      309,  309,  309,  309,  310,    0,  310,  310,  310,  310,
      310,  311,    0,  311,  311,  311,  311,  311,  312,    0,
      312,  312,  312,  312,  312,  313,    0,  313,  313,  313,
      313,  313,  314,    0,  314,  314,  314,  314,  314,  318,
        0,  318,  318,  318,  318,  318,  319,    0,  319,  319,
      319,  319,  319,  320,    0,  320,  320,  320,  320,  320,
      321,  321,  321,  321,  321,  322,    0,  322,  322,  322,
      322,  322,  323,    0,  323,  323,  323,  323,  323,  324,

        0,  324,  324,  324,  324,  324,  325,    0,  325,  325,
      325,  325,  325,  328,    0,  328,  328,  328,  328,  328,
      329,    0,  329,  329,  329,  329,  329,  330,    0,  330,
      330,  330,  330,  330,  333,  333,  333,  333,  333,  334,
        0,  334,  334,  334,  334,  334,  335,    0,  335,  335,
      335,  335,  335,  336,    0,  336,  336,  336,  336,  336,
      337,  338,  337,  337,  337,  337,  337,  342,  342,  342,
      342,  342,  339,  338,  339,  339,  339,  339,  339,    0,
        0,    0,    0,  340,  338,  340,  340,  340,  340,  340,
      341,    0,  341,  341,  341,  341,  341,  343,    0,  343,

      343,  343,  343,  343,  344,    0,  344,  344,  344,  344,
      344,  345,    0,  345,  345,  345,  345,  345,  346,    0,
      346,  346,  346,  346,  346,  350,  350,  350,  350,  350,
      351,    0,  351,  351,  351,  351,  351,  352,    0,  352,
      352,  352,  352,  352,  353,    0,  353,  353,  353,  353,
      353,  354,    0,  354,  354,  354,  354,  354,  355,    0,
      355,  355,  355,  355,  355,  356,    0,  356,  356,  356,
      356,  356,  357,    0,  357,  357,  357,  357,  357,  358,
      358,  358,  358,  358,  359,    0,  359,  359,  359,  359,
      359,  360,    0,  360,  360,  360,  360,  360,  361,    0,

      361,  361,  361,  361,  361,  362,    0,  362,  362,  362,
      362,  362,  363,    0,  363,  363,  363,  363,  363,  364,
        0,  364,  364,  364,  364,  364,  365,    0,  365,  365,
      365,  365,  365,  366,  366,  366,  366,  366,  367,    0,
      367,  367,  367,  367,  367,  368,    0,  368,  368,  368,
      368,  368,  369,    0,  369,  369,  369,  369,  369,  370,
        0,  370,  370,  370,  370,  370,  371,    0,  371,  371,
      371,  371,  371,  372,    0,  372,  372,  372,  372,  372,
      373,    0,  373,  373,  373,  373,  373,  375,  375,  375,
      375,  375,  376,  376,  376,  376,  376,  377,  377,  377,

      377,  377,  378,  378,  378,  378,  378,  379,    0,  379,
      379,  379,  379,  379,  380,    0,  380,  380,  380,  380,
      380,  381,    0,  381,  381,  381,  381,  381,  382,    0,
      382,  382,  382,  382,  382,  383,    0,  383,  383,  383,
      383,  383,  384,    0,  384,  384,  384,  384,  384,  385,
        0,  385,  385,  385,  385,  385,  386,  386,  386,  386,
      386,  387,    0,  387,  387,  387,  387,  387,  388,    0,
      388,  388,  388,  388,  388,  389,    0,  389,  389,  389,
      389,  389,  390,    0,  390,  390,  390,  390,  390,  391,
      391,  391,  391,  391,  392,  392,  392,  392,  392,  393,

      393,  393,  393,  393,  394,  394,  394,  394,  394,  395,
        0,  395,  395,  395,  395,  395,  396,    0,  396,  396,
      396,  396,  396,  397,    0,  397,  397,  397,  397,  397,
      398,    0,  398,  398,  398,  398,  398,  399,  399,  399,
      399,  399,  400,  400,  400,  400,  400,  401,  401,  401,
      401,  401,  402,  402,  402,  402,  402,  403,  403,  403,
      403,  403,  404,  404,  404,  404,  404,  405,  405,  405,
      405,  405,  406,  406,  406,  406,  406,  407,    0,  407,
      407,  407,  407,  407,  408,    0,  408,  408,  408,  408,
      408,  409,    0,  409,  409,  409,  409,  409,  410,    0,

      410,  410,  410,  410,  410,  411,    0,  411,  411,  411,
      411,  411,  412,    0,  412,  412,  412,  412,  412,  413,
        0,  413,  413,  413,  413,  413,  414,  414,  414,  414,
      414,  415,  415,  415,  415,  415,  416,  416,  416,  416,
      416,  417,  417,  417,  417,  417,  418,  418,  418,  418,
      418,  419,  419,  419,  419,  419,  420,  420,  420,  420,
      420,  421,  421,  421,  421,  421,  422,  422,  422,  422,
      422,  423,  423,  423,  423,  423,  424,  424,  424,  424,
      424,  425,  425,  425,  425,  425,  426,  426,  426,  426,
      426,  427,  427,  427,  427,  427,  428,  428,  428,  428,

      428,  429,    0,  429,  429,  429,  429,  429,  430,    0,
      430,  430,  430,  430,  430,  431,    0,  431,  431,  431,
      431,  431,  432,    0,  432,  432,  432,  432,  432,  433,
      433,  433,  433,  433,  434,  434,  434,  434,  434,  435,
      435,  435,  435,  435,  436,  436,  436,  436,  436,  437,
      437,  437,  437,  437,  438,  438,  438,  438,  438,  439,
      439,  439,  439,  439,  440,  440,  440,  440,  440,  441,
      441,  441,  441,  441,  442,  442,  442,  442,  442,  443,
      443,  443,  443,  443,  444,  444,  444,  444,  444,  445,
      445,  445,  445,  445,  446,  446,  446,  446,  446,  447,

      447,  447,  447,  447,  449,  449,  449,  449,  449,  449,
      449,  449,  449,  449,  449,  450,  450,  450,  450,  450,
      450,  450,  450,  450,  450,  450,  451,  451,  451,  451,
      451,  451,  451,  451,  451,  451,  451,  452,  452,  452,
      452,  452,  452,  452,  452,  452,  452,  452,  453,  453,
      453,  453,  453,  453,  453,  453,  453,  453,  453,  454,
      454,  454,  454,  454,  454,  454,  454,  454,  454,  454,
      455,  455,  455,  455,  455,  455,  455,  455,  455,  455,
      455,  456,  456,  456,  456,  456,  456,  456,  456,  456,
      456,  456,  457,    0,    0,  457,  458,  458,    0,  458,

        0,    0,  458,  459,  459,  459,  459,  459,  459,  459,
      459,    0,  459,  459,  460,    0,    0,  460,  460,    0,
        0,    0,  460,  461,    0,  461,    0,    0,  461,  462,
        0,  462,  462,  462,  462,  462,  462,  462,    0,  462,
      463,  463,  463,  463,  463,  463,  463,  463,  463,  463,
      463,  464,    0,    0,  464,  465,    0,    0,  465,  466,
        0,    0,  466,  467,    0,    0,  467,  468,    0,    0,
      468,  469,    0,    0,  469,  470,    0,    0,  470,  471,
      471,  471,  471,  471,  471,  471,  471,  471,    0,  471,
      472,    0,  472,    0,    0,  472,  473,    0,    0,  473,

      474,    0,    0,  474,  475,    0,    0,  475,  476,    0,
        0,  476,  477,    0,    0,  477,  478,    0,    0,  478,
      479,    0,    0,  479,  480,    0,    0,  480,  481,    0,
        0,  481,  482,    0,    0,  482,  483,  483,  483,  483,
      483,  483,  483,  483,  483,    0,  483,  484,  484,  484,
      484,  484,  484,  484,  484,  484,    0,  484,  485,    0,
        0,  485,  486,    0,    0,  486,  487,    0,    0,  487,
      488,    0,    0,  488,  489,    0,    0,  489,  490,    0,
        0,  490,  491,    0,    0,  491,  491,  492,    0,    0,
      492,  493,    0,    0,  493,  494,    0,    0,  494,  495,

        0,    0,  495,  496,    0,    0,  496,  497,    0,    0,
      497,  498,    0,    0,  498,  499,    0,    0,  499,  500,
        0,    0,  500,  501,    0,    0,  501,  502,    0,    0,
      502,  503,    0,    0,  503,  504,    0,    0,  504,  505,
        0,    0,  505,  506,    0,    0,  506,  507,    0,    0,
      507,  508,    0,    0,  508,  509,    0,    0,  509,  510,
        0,    0,  510,  511,    0,    0,  511,  512,    0,    0,
      512,  513,    0,    0,  513,  514,    0,    0,  514,  515,
        0,    0,  515,  516,    0,    0,  516,  516,  517,    0,
        0,  517,  518,    0,    0,  518,  519,    0,    0,  519,

      520,    0,    0,  520,  448,  448,  448,  448,  448,  448,
      448,  448,  448,  448,  448,  448,  448,  448,  448,  448,
      448,  448,  448,  448,  448,  448,  448,  448,  448,  448,
      448,  448,  448,  448,  448,  448,  448,  448,  448,  448,
      448,  448,  448,  448,  448,  448,  448,  448,  448,  448,
      448
    } ;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() (YY_G(yy_more_flag) = 1)
#define YY_MORE_ADJ YY_G(yy_more_len)
#define YY_RESTORE_YY_MORE_OFFSET
#line 1 "web.l"
#define INITIAL 0
#line 3 "web.l"
	#include <iostream>
	#include "web.h"
	#include "string.h"
	#define YY_DECL int WebLex::yylex(int switchcond)

	
	using namespace std;

	//This just a stub. It will never be called because of YY_DECL. 
	int yyFlexLexer::yylex()
	{
		return 0;
	}
	
	string element;
	int myleng;
	//if we read a script element we have to use _RSCRIPT instead of _RCONTENT because in the content of script elements "<" and ">" is allowed
	int script_element=0;
	

	
#define _MURI 1

#define _MSCHEME 2

#define _MAUTHORITY 3

#define _MPATH 4

#define _PHTML 5

#define _HREF 6

#define _RELEM_WA 7

#define _RELEM 8

#define _RCONTENT 9

#define _COMMENT 10

#define _COMMENT_NEU 11

#define _RCOMMENT 12

#define _EXTRACT 13

#define _FINDELEMSTART 14

#define _ATTVALUE 15

#define _RSCRIPT 16

#define YY_STACK_USED 1
#line 1405 "WebFlex.cc"
#endif /* !yyIN_HEADER YY-END-DISCARD-FROM-HEADER */

/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#ifndef YY_NO_UNISTD_H
#include <unistd.h>
#endif /* !YY_NO_UNISTD_H */

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

#ifndef yyIN_HEADER /* YY-DISCARD-FROM-HEADER */
#endif /* !yyIN_HEADER YY-END-DISCARD-FROM-HEADER */
#ifndef yyIN_HEADER /* YY-DISCARD-FROM-HEADER */
#endif /* !yyIN_HEADER YY-END-DISCARD-FROM-HEADER */
#ifndef yyIN_HEADER /* YY-DISCARD-FROM-HEADER */
#endif /* !yyIN_HEADER YY-END-DISCARD-FROM-HEADER */
#ifndef yyIN_HEADER /* YY-DISCARD-FROM-HEADER */
#endif /* !yyIN_HEADER YY-END-DISCARD-FROM-HEADER */

#ifndef yytext_ptr
static void yy_flex_strncpy YY_PARAMS(( char *, yyconst char *, int YY_PROTO_LAST_ARG));
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen YY_PARAMS(( yyconst char * YY_PROTO_LAST_ARG));
#endif

#ifndef YY_NO_INPUT
#ifndef yyIN_HEADER /* YY-DISCARD-FROM-HEADER */
#endif /* !yyIN_HEADER YY-END-DISCARD-FROM-HEADER */
#endif


#ifndef yyIN_HEADER /* YY-DISCARD-FROM-HEADER */
#endif /* !yyIN_HEADER YY-END-DISCARD-FROM-HEADER */

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
#define ECHO LexerOutput( yytext, yyleng )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
\
	if ( (result = LexerInput( (char *) buf, max_size )) < 0 ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) LexerError( msg )
#endif

#ifndef yyIN_HEADER /* YY-DISCARD-FROM-HEADER */
#endif /* !yyIN_HEADER YY-END-DISCARD-FROM-HEADER */
#ifndef yyIN_HEADER /* YY-DISCARD-FROM-HEADER */
/* end tables serialization structures and prototypes */

#endif /* !yyIN_HEADER YY-END-DISCARD-FROM-HEADER */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yyFlexLexer::yylex()
#endif


/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

#ifndef yyIN_HEADER /* YY-DISCARD-FROM-HEADER */
YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;

#line 91 "web.l"
#define YY_TABLES_VERIFY 0

	{
		
		
		
		
		switch (switchcond){
			case MURI:
				switchcond = -1;
				BEGIN(_MURI);
				break;
				
			case MSCHEME:
				switchcond = -1;
				BEGIN (_MSCHEME);
				break;

			
			case FINDELEMSTART:
				switchcond = -1;
				BEGIN  (_FINDELEMSTART);
				break;
				
			case RELEM_WA:
				switchcond = -1;
				BEGIN  (_RELEM_WA);
				break;

			case RSCRIPT:
				switchcond = -1;
				yy_push_state(_RSCRIPT);
				break;
				
			
			case -1:
				break;
				
			default: 
				cout << "Ungültige Startbedingung" << endl;
				return ERROR;
				
			}
	}
	
				

#line 1570 "WebFlex.cc"


	if ( YY_G(yy_init) )
		{
		YY_G(yy_init) = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

#ifdef YY_USES_REJECT
        if ( ! YY_G(yy_state_buf) )
            YY_G(yy_state_buf) = (yy_state_type *)yyalloc(YY_BUF_SIZE + 2  YY_CALL_LAST_ARG);
#endif

		if ( ! YY_G(yy_start) )
			YY_G(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = & std::cin;

		if ( ! yyout )
			yyout = & std::cout;

		if ( ! YY_G(yy_current_buffer) )
			YY_G(yy_current_buffer) =
				yy_create_buffer( yyin, YY_BUF_SIZE YY_CALL_LAST_ARG);

		yy_load_buffer_state( YY_CALL_ONLY_ARG );
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		YY_G(yy_more_len) = 0;
		if ( YY_G(yy_more_flag) )
			{
			YY_G(yy_more_len) = YY_G(yy_c_buf_p) - YY_G(yytext_ptr);
			YY_G(yy_more_flag) = 0;
			}
		yy_cp = YY_G(yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = YY_G(yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = YY_G(yy_start);
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				YY_G(yy_last_accepting_state) = yy_current_state;
				YY_G(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 449 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 3105 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = YY_G(yy_last_accepting_cpos);
			yy_current_state = YY_G(yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

#ifdef YY_USE_LINENO
		if ( yy_act != YY_END_OF_BUFFER && yy_rule_can_match_eol[yy_act] )
			{
			int yyl;
			for ( yyl = (yy_more_len); yyl < yyleng; ++yyl )
				if ( yytext[yyl] == '\n' )
					++yylineno;
			}
#endif

do_action:	/* This label is used only to access EOF actions. */


		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = YY_G(yy_hold_char);
			yy_cp = YY_G(yy_last_accepting_cpos);
			yy_current_state = YY_G(yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 137 "web.l"
return URI;
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 138 "web.l"
return RURI;
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 139 "web.l"
{BEGIN(_MAUTHORITY);return SCHEME;}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 140 "web.l"
{BEGIN(_MPATH);return AUTHORITY;}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 141 "web.l"
return PATH;
	YY_BREAK
case 6:
/* rule 6 can match eol */
YY_RULE_SETUP
#line 144 "web.l"
{return SEARCH_ELEMENT_START;}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 145 "web.l"
{BEGIN (_RELEM);
							//cout << "_FINDELEMSTART  yytext: " << yytext << "  yyin->tellg(): " << (unsigned long)yyin->tellg() << " yyleng: " << yyleng << " pos: " << endl;
							
						}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 149 "web.l"
{pos= ((unsigned long)yyin->tellg())- yyleng ;
							//cout << "_RELEM1 yytext: " << yytext << "  yyin->tellg(): " << (unsigned long)yyin->tellg() << " yyleng: " << yyleng << " pos: " << endl;
							//string tmp = yytext;
							if (isEqual(yytext,"script"))
								script_element=1;
							return EIDENTIFIER;
						}
	YY_BREAK
case 9:
/* rule 9 can match eol */
YY_RULE_SETUP
#line 159 "web.l"
{BEGIN (_ATTVALUE);}
	YY_BREAK
case 10:
/* rule 10 can match eol */
YY_RULE_SETUP
#line 160 "web.l"

	YY_BREAK
case 11:
YY_RULE_SETUP
#line 161 "web.l"
//eat up
	YY_BREAK
case 12:
/* rule 12 can match eol */
YY_RULE_SETUP
#line 162 "web.l"
{pos= ((unsigned long)yyin->tellg())- yyleng +1;BEGIN(_RELEM);return ATTVALUE;}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 163 "web.l"
{pos= ((unsigned long)yyin->tellg())- yyleng +1;BEGIN(_RELEM);return ATTVALUE;}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 164 "web.l"
{if (script_element){
				yy_push_state(_RSCRIPT);
				script_element=0;
			}else
				BEGIN(_RCONTENT);
			return CLOSE_TAG;
			}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 171 "web.l"
//eat up
	YY_BREAK
case 16:
/* rule 16 can match eol */
YY_RULE_SETUP
#line 174 "web.l"
{
																	
																	pos= ((unsigned long)yyin->tellg())- yyleng ;
																	yy_push_state(YY_START);
																	//cout << " _RELEM2 yytext: " << yytext << "  yyin->tellg(): " << yyin->tellg() << " yyleng: " << yyleng << " pos: " << endl;
																	
																	if (YY_START == _RELEM_WA){
																		//cout << "_RELEMWA";
																		myleng= yyleng;
																		yymore();
																	} else {
																	 
																	 yytext=yytext+1;
																	 pos= (((unsigned long)yyin->tellg()))- yyleng;
																	 //cout << "<_RELEM_WA,_RELEM>" << YYText() << endl;
																	 return EIDENTIFIER;

																	 
																	}
																}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 195 "web.l"
{yy_push_state(_COMMENT_NEU);}
	YY_BREAK
case 18:
/* rule 18 can match eol */
YY_RULE_SETUP
#line 197 "web.l"
//eat up
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 198 "web.l"
{BEGIN(_RCONTENT);return COMMENT;}
	YY_BREAK
case 20:
/* rule 20 can match eol */
YY_RULE_SETUP
#line 200 "web.l"
{
											
											//cout << "Lexer: " << YYText() << endl;
											pos= ((unsigned long)yyin->tellg())- yyleng;
											
											
											yytext[myleng]='\0';
											yytext= yytext+1;
											//cout << yytext[0] << endl;
											
											myleng= yyleng;
											//yyleng= strlen(yytext);
											
											//cout << "Prüfe treffer ********** " << yytext << endl;



											if (isEqual(yytext, "script")){
												//cout << "*******TREFFER**********" << endl;
												yy_push_state(_RSCRIPT);
												return ELEMENT;
											}


											yy_push_state(_RCONTENT);

											if (yytext[0] == '/'){
												return ELEMENT_CLOSE;
											}
											

											
											
											if (yytext[myleng -1] == '/' || yytext[0] == '!' or yytext[0] == '?')
												return ELEMENT_SA;
											else{
												return ELEMENT;
											}
							}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 242 "web.l"
{return CONTENT;}
	YY_BREAK
case 22:
/* rule 22 can match eol */
YY_RULE_SETUP
#line 243 "web.l"
{return CONTENT;}
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 244 "web.l"
{yyless(0);yy_pop_state();return CONTENT_END;}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 246 "web.l"
{yyless(0);yy_pop_state();return CONTENT_END;}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 247 "web.l"
{return CONTENT;}
	YY_BREAK
case 26:
/* rule 26 can match eol */
YY_RULE_SETUP
#line 248 "web.l"
{return CONTENT;}
	YY_BREAK
case 27:
/* rule 27 can match eol */
YY_RULE_SETUP
#line 252 "web.l"
//eat up word wrap
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 253 "web.l"
//eat up arbitrary character
	YY_BREAK
case 29:
/* rule 29 can match eol */
YY_RULE_SETUP
#line 254 "web.l"
//eat up
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 255 "web.l"
{return ERROR;}
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 258 "web.l"
ECHO;
	YY_BREAK
#line 1912 "WebFlex.cc"
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(_MURI):
case YY_STATE_EOF(_MSCHEME):
case YY_STATE_EOF(_MAUTHORITY):
case YY_STATE_EOF(_MPATH):
case YY_STATE_EOF(_PHTML):
case YY_STATE_EOF(_HREF):
case YY_STATE_EOF(_RELEM_WA):
case YY_STATE_EOF(_RELEM):
case YY_STATE_EOF(_RCONTENT):
case YY_STATE_EOF(_COMMENT):
case YY_STATE_EOF(_COMMENT_NEU):
case YY_STATE_EOF(_RCOMMENT):
case YY_STATE_EOF(_EXTRACT):
case YY_STATE_EOF(_FINDELEMSTART):
case YY_STATE_EOF(_ATTVALUE):
case YY_STATE_EOF(_RSCRIPT):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - YY_G(yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = YY_G(yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_G(yy_current_buffer)->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			YY_G(yy_n_chars) = YY_G(yy_current_buffer)->yy_n_chars;
			YY_G(yy_current_buffer)->yy_input_file = yyin;
			YY_G(yy_current_buffer)->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( YY_G(yy_c_buf_p) <= &YY_G(yy_current_buffer)->yy_ch_buf[YY_G(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			YY_G(yy_c_buf_p) = YY_G(yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state( YY_CALL_ONLY_ARG );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state YY_CALL_LAST_ARG);

			yy_bp = YY_G(yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++YY_G(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = YY_G(yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer( YY_CALL_ONLY_ARG ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				YY_G(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap( YY_CALL_ONLY_ARG ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					YY_G(yy_c_buf_p) = YY_G(yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! YY_G(yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				YY_G(yy_c_buf_p) =
					YY_G(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state( YY_CALL_ONLY_ARG );

				yy_cp = YY_G(yy_c_buf_p);
				yy_bp = YY_G(yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				YY_G(yy_c_buf_p) =
				&YY_G(yy_current_buffer)->yy_ch_buf[YY_G(yy_n_chars)];

				yy_current_state = yy_get_previous_state( YY_CALL_ONLY_ARG );

				yy_cp = YY_G(yy_c_buf_p);
				yy_bp = YY_G(yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */
#endif /* !yyIN_HEADER YY-END-DISCARD-FROM-HEADER */

#ifndef yyIN_HEADER /* YY-DISCARD-FROM-HEADER */
yyFlexLexer::yyFlexLexer( std::istream* arg_yyin, std::ostream* arg_yyout )
	{
	yyin = arg_yyin;
	yyout = arg_yyout;
	yy_c_buf_p = 0;
	yy_init = 1;
	yy_start = 0;
	yy_flex_debug = 0;
	yylineno = 1;	// this will only get updated if %option yylineno

	yy_did_buffer_switch_on_eof = 0;

	yy_looking_for_trail_begin = 0;
	yy_more_flag = 0;
	yy_more_len = 0;
	yy_more_offset = yy_prev_more_offset = 0;

	yy_start_stack_ptr = yy_start_stack_depth = 0;
	yy_start_stack = 0;

	yy_current_buffer = 0;

#ifdef YY_USES_REJECT
	yy_state_buf = new yy_state_type[YY_BUF_SIZE + 2];
#else
	yy_state_buf = 0;
#endif
	}

yyFlexLexer::~yyFlexLexer()
	{
	delete [] yy_state_buf;
	yyfree( yy_start_stack YY_CALL_LAST_ARG );
	yy_delete_buffer( yy_current_buffer YY_CALL_LAST_ARG);
	}

void yyFlexLexer::switch_streams( std::istream* new_in, std::ostream* new_out )
	{
	if ( new_in )
		{
		yy_delete_buffer( yy_current_buffer  YY_CALL_LAST_ARG);
		yy_switch_to_buffer( yy_create_buffer( new_in, YY_BUF_SIZE  YY_CALL_LAST_ARG) YY_CALL_LAST_ARG);
		}

	if ( new_out )
		yyout = new_out;
	}

#ifdef YY_INTERACTIVE
int yyFlexLexer::LexerInput( char* buf, int /* max_size */ )
#else
int yyFlexLexer::LexerInput( char* buf, int max_size )
#endif
	{
	if ( yyin->eof() || yyin->fail() )
		return 0;

#ifdef YY_INTERACTIVE
	yyin->get( buf[0] );

	if ( yyin->eof() )
		return 0;

	if ( yyin->bad() )
		return -1;

	return 1;

#else
	(void) yyin->read( buf, max_size );

	if ( yyin->bad() )
		return -1;
	else
		return yyin->gcount();
#endif
	}

void yyFlexLexer::LexerOutput( const char* buf, int size )
	{
	(void) yyout->write( buf, size );
	}
#endif /* !yyIN_HEADER YY-END-DISCARD-FROM-HEADER */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

#ifndef yyIN_HEADER /* YY-DISCARD-FROM-HEADER */
int yyFlexLexer::yy_get_next_buffer()
	{
	register char *dest = YY_G(yy_current_buffer)->yy_ch_buf;
	register char *source = YY_G(yytext_ptr);
	register int number_to_move, i;
	int ret_val;

	if ( YY_G(yy_c_buf_p) > &YY_G(yy_current_buffer)->yy_ch_buf[YY_G(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_G(yy_current_buffer)->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( YY_G(yy_c_buf_p) - YY_G(yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (YY_G(yy_c_buf_p) - YY_G(yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_G(yy_current_buffer)->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_G(yy_current_buffer)->yy_n_chars = YY_G(yy_n_chars) = 0;

	else
		{
			size_t num_to_read =
			YY_G(yy_current_buffer)->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_G(yy_current_buffer);

			int yy_c_buf_p_offset =
				(int) (YY_G(yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2 YY_CALL_LAST_ARG );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			YY_G(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_G(yy_current_buffer)->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_G(yy_current_buffer)->yy_ch_buf[number_to_move]),
			YY_G(yy_n_chars), num_to_read );

		YY_G(yy_current_buffer)->yy_n_chars = YY_G(yy_n_chars);
		}

	if ( YY_G(yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  YY_CALL_LAST_ARG);
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_G(yy_current_buffer)->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	YY_G(yy_n_chars) += number_to_move;
	YY_G(yy_current_buffer)->yy_ch_buf[YY_G(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_G(yy_current_buffer)->yy_ch_buf[YY_G(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	YY_G(yytext_ptr) = &YY_G(yy_current_buffer)->yy_ch_buf[0];

	return ret_val;
	}
#endif /* !yyIN_HEADER YY-END-DISCARD-FROM-HEADER */

/* yy_get_previous_state - get the state just before the EOB char was reached */

#ifndef yyIN_HEADER /* YY-DISCARD-FROM-HEADER */
    yy_state_type yyFlexLexer::yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = YY_G(yy_start);

	for ( yy_cp = YY_G(yytext_ptr) + YY_MORE_ADJ; yy_cp < YY_G(yy_c_buf_p); ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			YY_G(yy_last_accepting_state) = yy_current_state;
			YY_G(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 449 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    yy_state_type yyFlexLexer::yy_try_NUL_trans( yy_state_type yy_current_state )
	{
	register int yy_is_jam;
	register char *yy_cp = YY_G(yy_c_buf_p);

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		YY_G(yy_last_accepting_state) = yy_current_state;
		YY_G(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 449 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 448);

	return yy_is_jam ? 0 : yy_current_state;
	}


    void yyFlexLexer::yyunput( int c, register char* yy_bp)
	{
	register char *yy_cp = YY_G(yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = YY_G(yy_hold_char);

	if ( yy_cp < YY_G(yy_current_buffer)->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = YY_G(yy_n_chars) + 2;
		register char *dest = &YY_G(yy_current_buffer)->yy_ch_buf[
					YY_G(yy_current_buffer)->yy_buf_size + 2];
		register char *source =
				&YY_G(yy_current_buffer)->yy_ch_buf[number_to_move];

		while ( source > YY_G(yy_current_buffer)->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_G(yy_current_buffer)->yy_n_chars =
			YY_G(yy_n_chars) = YY_G(yy_current_buffer)->yy_buf_size;

		if ( yy_cp < YY_G(yy_current_buffer)->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

#ifdef YY_USE_LINENO
    if ( c == '\n' )
        --yylineno;
#endif
	YY_G(yytext_ptr) = yy_bp;
	YY_G(yy_hold_char) = *yy_cp;
	YY_G(yy_c_buf_p) = yy_cp;
	}

    int yyFlexLexer::yyinput()

	{
	int c;

	*YY_G(yy_c_buf_p) = YY_G(yy_hold_char);

	if ( *YY_G(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( YY_G(yy_c_buf_p) < &YY_G(yy_current_buffer)->yy_ch_buf[YY_G(yy_n_chars)] )
			/* This was really a NUL. */
			*YY_G(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = YY_G(yy_c_buf_p) - YY_G(yytext_ptr);
			++YY_G(yy_c_buf_p);

			switch ( yy_get_next_buffer( YY_CALL_ONLY_ARG ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin YY_CALL_LAST_ARG);

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap( YY_CALL_ONLY_ARG ) )
						return EOF;

					if ( ! YY_G(yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput(YY_CALL_ONLY_ARG);
#else
					return input(YY_CALL_ONLY_ARG);
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					YY_G(yy_c_buf_p) = YY_G(yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) YY_G(yy_c_buf_p);	/* cast for 8-bit char's */
	*YY_G(yy_c_buf_p) = '\0';	/* preserve yytext */
	YY_G(yy_hold_char) = *++YY_G(yy_c_buf_p);


	return c;
	}

    void yyFlexLexer::yyrestart( std::istream* input_file )
	{
	if ( ! YY_G(yy_current_buffer) )
		YY_G(yy_current_buffer) =
            yy_create_buffer( yyin, YY_BUF_SIZE YY_CALL_LAST_ARG);

	yy_init_buffer( YY_G(yy_current_buffer), input_file YY_CALL_LAST_ARG);
	yy_load_buffer_state( YY_CALL_ONLY_ARG );
	}

    void yyFlexLexer::yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
	{
	if ( YY_G(yy_current_buffer) == new_buffer )
		return;

	if ( YY_G(yy_current_buffer) )
		{
		/* Flush out information for old buffer. */
		*YY_G(yy_c_buf_p) = YY_G(yy_hold_char);
		YY_G(yy_current_buffer)->yy_buf_pos = YY_G(yy_c_buf_p);
		YY_G(yy_current_buffer)->yy_n_chars = YY_G(yy_n_chars);
		}

	YY_G(yy_current_buffer) = new_buffer;
	yy_load_buffer_state( YY_CALL_ONLY_ARG );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	YY_G(yy_did_buffer_switch_on_eof) = 1;
	}


    void yyFlexLexer::yy_load_buffer_state()
	{
	YY_G(yy_n_chars) = YY_G(yy_current_buffer)->yy_n_chars;
	YY_G(yytext_ptr) = YY_G(yy_c_buf_p) = YY_G(yy_current_buffer)->yy_buf_pos;
	yyin = YY_G(yy_current_buffer)->yy_input_file;
	YY_G(yy_hold_char) = *YY_G(yy_c_buf_p);
	}

    YY_BUFFER_STATE yyFlexLexer::yy_create_buffer( std::istream* file, int size )
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state ) YY_CALL_LAST_ARG );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( b->yy_buf_size + 2 YY_CALL_LAST_ARG );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file YY_CALL_LAST_ARG);

	return b;
	}

    void yyFlexLexer::yy_delete_buffer( YY_BUFFER_STATE b )
	{
	if ( ! b )
		return;

	if ( b == YY_G(yy_current_buffer) )
		YY_G(yy_current_buffer) = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf YY_CALL_LAST_ARG );

	yyfree( (void *) b YY_CALL_LAST_ARG );
	}



#ifndef YY_NEVER_INTERACTIVE
extern "C" int isatty YY_PARAMS(( int ));
#endif
void yyFlexLexer::yy_init_buffer( YY_BUFFER_STATE b, std::istream* file )

	{
	int oerrno = errno;

	yy_flush_buffer( b YY_CALL_LAST_ARG);

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

	b->yy_is_interactive = 0;
	errno = oerrno;
	}

    void yyFlexLexer::yy_flush_buffer( YY_BUFFER_STATE b )
	{
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_G(yy_current_buffer) )
		yy_load_buffer_state( YY_CALL_ONLY_ARG );
	}


#ifndef YY_NO_SCAN_BUFFER
#endif


#ifndef YY_NO_SCAN_STRING
#endif


#ifndef YY_NO_SCAN_BYTES
#endif


#ifndef YY_NO_PUSH_STATE
    void yyFlexLexer::yy_push_state( int new_state )
	{
	if ( YY_G(yy_start_stack_ptr) >= YY_G(yy_start_stack_depth) )
		{
		yy_size_t new_size;

		YY_G(yy_start_stack_depth) += YY_START_STACK_INCR;
		new_size = YY_G(yy_start_stack_depth) * sizeof( int );

		if ( ! YY_G(yy_start_stack) )
			YY_G(yy_start_stack) = (int *) yyalloc( new_size YY_CALL_LAST_ARG );

		else
			YY_G(yy_start_stack) = (int *) yyrealloc(
					(void *) YY_G(yy_start_stack), new_size YY_CALL_LAST_ARG );

		if ( ! YY_G(yy_start_stack) )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	YY_G(yy_start_stack)[YY_G(yy_start_stack_ptr)++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
    void yyFlexLexer::yy_pop_state()
	{
	if ( --YY_G(yy_start_stack_ptr) < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(YY_G(yy_start_stack)[YY_G(yy_start_stack_ptr)]);
	}
#endif


#ifndef YY_NO_TOP_STATE
    int yyFlexLexer::yy_top_state()
	{
	return YY_G(yy_start_stack)[YY_G(yy_start_stack_ptr) - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

void yyFlexLexer::LexerError( yyconst char msg[] )
	{
	std::cerr << msg << std::endl;
	exit( YY_EXIT_FAILURE );
	}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = YY_G(yy_hold_char); \
		YY_G(yy_c_buf_p) = yytext + yyless_macro_arg; \
		YY_G(yy_hold_char) = *YY_G(yy_c_buf_p); \
		*YY_G(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )



/* Accessor  methods (get/set functions) to struct members. */





/* Internal utility routines. */

#ifndef yytext_ptr
static void yy_flex_strncpy YYFARGS3( char*,s1, yyconst char *,s2, int,n)
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen YYFARGS1( yyconst char *,s)
	{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
	}
#endif

/* You may override yyalloc by defining YY_NO_FLEX_ALLOC and linking to
 * your own version */
#ifndef YY_NO_FLEX_ALLOC
void *yyalloc YYFARGS1( yy_size_t ,size)
	{
	return (void *) malloc( size );
	}
#endif

/* You may override yyrealloc by defining YY_NO_FLEX_REALLOC and linking
 * to your own version. */
#ifndef YY_NO_FLEX_REALLOC
void *yyrealloc  YYFARGS2( void *,ptr, yy_size_t ,size)
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}
#endif

/* You may override yyfree by defining YY_NO_FLEX_FREE and linking to
 * your own version.*/
#ifndef YY_NO_FLEX_FREE
void yyfree YYFARGS1( void *,ptr)
	{
	free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
	}
#endif

#define YYTABLES_NAME "yytables"

#if YY_MAIN
int main YY_PARAMS((void));

int main ()
	{

	yylex();

	return 0;
	}
#endif
#endif /* !yyIN_HEADER YY-END-DISCARD-FROM-HEADER */
#line 258 "web.l"
#ifndef yyIN_HEADER /* YY-DISCARD-FROM-HEADER */


/*bool isEqual (string s1, string s2){
	transform(s1.begin(), s1.end(), s1.begin(), ::tolower);
	transform(s2.begin(), s2.end(), s2.begin(), ::tolower);
	
	return s1 == s2;
}*/
#endif /* !yyIN_HEADER YY-END-DISCARD-FROM-HEADER */
