optimizer:	optimizerNewProperties.pl calloptimizer.pl database.pl operators.pl boundary.pl searchtree.pl testcases.pl
	cat optimizerNewProperties.pl calloptimizer.pl database.pl operators.pl boundary.pl searchtree.pl testcases.pl > optimizer







