operator lock alias LOCK pattern op(_,_)
operator trylock alias TRYLOCK pattern op(_,_)
operator unlock alias UNLOCK pattern op(_)
operator addworker alias ADDWORKER pattern op(_,_)
operator removeworker alias REMOVEWORKER pattern op(_,_)
operator moveslot alias MOVESLOT pattern op(_,_)
operator getworkerindex alias GETWORKERINDEX pattern op(_,_)
