/* Generated by Together */


public class pp_equal {

    public static void main (String[] args) {

        PointList p1 = null;
        PointList p2 = null;
        //PointList pResult = null;
	boolean pres = false;

	p1 = RPGConv.getPoints ("100points.pts");
        if (!RPGConv.lastConversionSuccessful()){
            System.out.println (RPGConv.lastConversionErrorMsg());
            System.exit(0);
        }
        p2 = RPGConv.getPoints ("100points.pts");
        if (!RPGConv.lastConversionSuccessful()){
            System.out.println (RPGConv.lastConversionErrorMsg());
            System.exit(0);
        }
	long summe = 0;
        for (int n = 0; n < 10; n++) {
	    
	    long millis1 = System.currentTimeMillis();
	    for (int i = 0; i<10; i++) {
	        pres  = Algebra.pp_equal (p1, p2);
	    }//for i
	    
	    long millis2 = System.currentTimeMillis();
	    System.out.println ("Laufzeit: " + (millis2 - millis1));
	    summe = summe + (millis2 - millis1);
	    //        System.out.println ("Point objects equal: " + result);
	    //        System.out.println ("Elapsed time: " + (millis2 - millis1) + " ms");
        }//for n
	//        System.out.println ("Result: " + pResult.toString());
        System.out.println ("Summe: " + summe);
        System.out.println ("Durchschnittliche Laufzeit: " + summe/100 + " ms");
	
    }
    
    
}
