/* Generated by Together */


public class pp_plus {

    public static void main (String[] args) {

        PointList p1 = null;
        PointList p2 = null;
        PointList pResult = null;

	p1 = RPGConv.getPoints ("10points.pts");
        if (!RPGConv.lastConversionSuccessful()){
            System.out.println (RPGConv.lastConversionErrorMsg());
            System.exit(0);
        }
        p2 = RPGConv.getPoints ("50points.pts");
        if (!RPGConv.lastConversionSuccessful()){
            System.out.println (RPGConv.lastConversionErrorMsg());
            System.exit(0);
        }
/*        r1.roundCoords();
        r2.roundCoords();*/


//		System.out.println ("r1:\n" + r1.toString());
//    	System.out.println();
//	    System.out.println ("r2:\n" + r2.toString());
//    	System.out.println();

	long summe = 0;
        for (int n = 0; n < 10; n++) {
	    
	    long millis1 = System.currentTimeMillis();
	    for (int i = 0; i<10; i++) {
	        pResult  = Algebra.pp_plus (p1, p2);
	    }//for i
	    
	    long millis2 = System.currentTimeMillis();
	    System.out.println ("Laufzeit: " + (millis2 - millis1));
	    summe = summe + (millis2 - millis1);
	    //        System.out.println ("Point objects equal: " + result);
	    //        System.out.println ("Elapsed time: " + (millis2 - millis1) + " ms");
        }//for n
	//        System.out.println ("Result: " + pResult.toString());
        System.out.println ("Summe: " + summe);
        System.out.println ("Durchschnittliche Laufzeit: " + summe/100 + " ms");
	
    }
    
    
}
