/* Generated by Together */

public class rr_minus {

    public static void main (String[] args) {

        SegList r1 = null;
        SegList r2 = null;
        TriList rResult = null;

	r1 = RPGConv.getRegions ("poly10_1.ply");
        if (!RPGConv.lastConversionSuccessful()){
            System.out.println (RPGConv.lastConversionErrorMsg());
            System.exit(0);
        }
        r2 = RPGConv.getRegions ("poly10_2.ply");
        if (!RPGConv.lastConversionSuccessful()){
            System.out.println (RPGConv.lastConversionErrorMsg());
            System.exit(0);
        }


	Rational fact = new Rational(80);
	for (int i = 0; i < r1.size(); i++) {
	    ((Segment)r1.get(i)).zoom(fact); }
	for (int i = 0; i < r2.size(); i++) {
	    ((Segment)r2.get(i)).zoom(fact); }
	

        TriList t1 = (new Polygons (r1)).triangles();
        TriList t2 = (new Polygons (r2)).triangles();
	
	/*
	GFXout g = new GFXout();
	g.initWindow();
	g.addList(t1);
	g.addList(r1);
	g.addList(t2);
	g.addList(r2);
	g.showIt();
	*/



	long summe = 0;
        for (int n = 0; n < 10; n++) {
	    
	    long millis1 = System.currentTimeMillis();
	    for (int i = 0; i<1; i++) {
                rResult = Algebra.rr_minus (t1, t2);
            }
	    long millis2 = System.currentTimeMillis();
	    System.out.println ("Laufzeit: " + (millis2 - millis1));
	    summe = summe + (millis2 - millis1);
        }
	
        System.out.println ("Summe: " + summe);
        System.out.println ("Durchschnittliche Laufzeit: " + summe/10 + " ms");
	
    }
    
}
