operator thenetwork alias THENETWORK pattern op ( _, _ )
operator routes alias ROUTES pattern op ( _ )
operator junctions alias JUNCTIONS pattern op ( _ )
operator sections alias SECTIONS pattern op ( _ )
operator shortest_path alias SHORTEST_PATH pattern op ( _, _ )
operator length alias LENGTH pattern op ( _ )
