#!/bin/bash


if [ $# -lt 2 ]; then
  echo "Usage arlib <libfile>  <lib_1> ... <lib_n> "
  exit 1
fi

TARGET=$1
shift

SOURCES=$*

for S in $SOURCES; do
  ar t $S | while read O; do ar x $S "$O"; ar rs $TARGET "$O"; rm "$O";  done
done


