#!/bin/bash

bin=`dirname "$0"`
bin=`cd "$bin"; pwd`
source $bin/ps-functions

ADDPAR="" # Additional startup parameters for each slave
SLONLY=false
# Process the parameters
declare -i numOfArgs=$#
let numOfArgs++

while [ $numOfArgs -ne $OPTIND ]; do
  
  getopts "hso" optKey
  if [ "$optKey" == "?" ]; then
    optKey="h"
  fi

  case $optKey in
    h)
      echo -en "\nUsage of ${0##*/}:\n\n"
      echo -en "Switch off all Secondo Monitors inside the cluster.\n"
      echo -en "Machine's IP addresses are listed in the file\n$PARALLEL_SECONDO_SLAVES \n$PARALLEL_SECONDO_MASTER\n\n"
      echo -en "  -h Print this message and exit. \n\n"
      echo -en "  -s Switch off the monitors only on Slave nodes. \n\n"
      echo -en "  -o Switch off Monitors based on node's Own configuration \n"
      echo -en "     $HOME/.parasecrc \n\n"
      exit 0;;
    s)
      SLONLY=true
      ;;
    o)
      ADDPAR=" -o"
      ;;
  esac
done

if $SLONLY ; then
  IPLIST=$(get_slaveIPs)
else
  IPLIST=$(get_slaveIPs -m)
fi

RT=0
for node in $IPLIST; do
  echo -n "Switch OFF Monitor on $node ... ... "
  ssh $node "ps-stopMonitors ${ADDPAR}" >/dev/null #2>&1
  if [ $? -ne 0 ]; then
    echo "FAIL."
    RT=1
  else
    echo "Done!"
  fi 
done

exit $RT