ALGEBRA_INCLUDE(1,StandardAlgebra,Hybrid)
ALGEBRA_INCLUDE(2,FunctionAlgebra,Executable)
ALGEBRA_INCLUDE(3,RelationAlgebra,Executable)
ALGEBRA_INCLUDE(4,ExtRelationAlgebra,Executable)
ALGEBRA_INCLUDE(9,BTreeAlgebra,Executable)
ALGEBRA_INCLUDE(13,ArrayAlgebra,Executable)
ALGEBRA_INCLUDE(17,FuzzyAlgebra,Executable)
ALGEBRA_INCLUDE(19,OldRelationAlgebra,Executable)
