########################################################################
#
# SECONDO makefile for lists and tables
#
########################################################################

include ../../makefile.config
ifdef platform
include ../../makefile.$(platform)
.SUFFIXES: .exe .res .a .o .c .cpp .cc .cxx .m .rc .p .f .F .r .y .l .s .S .def .h

.PHONY: all
all:
	$(CP) CTable.h $(INCLUDEDIR)
	$(CP) CTable.cpp $(INCLUDEDIR)

.PHONY: clean
clean:
	$(RM) *.o
	$(RM) *.lo

else
# Platform not specified
all:
	@echo *** Platform not specified in makefile.config
endif

