name: Build and test SECONDO 

on: [push, pull_request]

env:
  SECONDO_PLATFORM: linux64
  SECONDO_BUILD_DIR: $GITHUB_WORKSPACE
  BERKELEY_DB_LIB: db_cxx
  BERKELEY_DB_DIR: /usr
  J2SDK_ROOT: /usr/lib/jvm/java-8-openjdk-amd64
  SWI_HOME_DIR: /usr/lib/swi-prolog/
  PL_LIB_DIR: /usr/lib/swi-prolog/lib/amd64/
  PL_INCLUDE_DIR: /usr/lib/swi-prolog/include
  PL_VERSION: 70203
  JPL_DLL: /usr/lib/swi-prolog/lib/amd64/libjpl.so
  JPL_JAR: /usr/lib/swi-prolog/lib/jpl.jar
  PL_LIB: swipl

jobs:
   build:
      runs-on: ubuntu-20.04
      steps:

      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Create build cache dir
        run: |
           mkdir -p ~/build_cache

      - name: Cache SECONDO object files 
        id: cache-secondo-objects
        uses: actions/cache@v3
        with:
          path: ~/build_cache
          key: ${{ runner.os }}-build-${{ hashFiles('/etc/os-release') }}

      - name: Update packages
        run: |
           sudo apt-get update 

      - name: Install packages
        run: |
           sudo apt-get -y install flex bison gcc g++ libdb5.3 libdb5.3-dev libdb5.3++ libdb5.3++-dev db5.3-util libjpeg62 libjpeg62-dev libgsl0-dev libreadline-dev librecode-dev libgmp-dev libncurses-dev libxml2-dev libboost-all-dev build-essential openjdk-8-jdk libxml2 libxml2-dev wget swi-prolog-nox swi-prolog-java swi-prolog libquadmath0 libgmp-dev libgmp10 original-awk libboost-all-dev libbison-dev libfl-dev rsync git-restore-mtime

      - name: Restore mtime
        run: |
           git restore-mtime 
          
      - name: Restore from build cache
        run: |
           rsync -zaruv ~/build_cache/ .
      
      - name: Build SECONDO
        run: |
           make -j 16
      
      - name: Update build cache
        run: |
           rsync -zar --include="*/" --include="*.o" --include="*.dep" --include="*.class" --exclude="*" . ~/build_cache
      
      - name: Test SECONDO
        run: |
           cd CM-Scripts/; ./run-tests.sh -tty /tmp/secondotest 1800
  
